### ISSUE TITLE
Search behaves strangely - does not find entities

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1000]
Should I comment on search in 1.3? If so, the search works in strange ways - (1) does not find "David Zbíral" entity, and (2) does not find a newly duplicated "David Zbíral Jr" P entity.
Related: also Suggester does not find David Zbíral Jr. properly without the ".", i.e. does not suggest this entity upon input "David Zbíral Jr" (without ".").

![obrazek](https://user-images.githubusercontent.com/55400794/166105609-e7112a06-1746-4734-a083-a916e6eb9605.png)

**Comment by Ptrhnk** [comment]
Don't you need wildcard char at the end of word?

**Comment by Ptrhnk** [comment]
Celebrating 1000 issues!

**Comment by davidzbiral** [comment]
@Ptrhnk : immediately, I only need that it works and finds things (whole word on input > whole word in search result). Wildcard can wait.

**Comment by Ptrhnk** [comment]
@davidzbiral But wildcard is already implemented. You have to to use it to find what you need. Or did I get something wrong?

**Comment by davidzbiral** [comment]
Wildcard should be for _optional_ shortening on the right. But I need a different, in fact very, algorithm or what: whole word must match whole word. Both in Suggester and Search.

**Comment by Ptrhnk** [comment]
@jancimertel Ok I think this is on BE then

**Comment by Ptrhnk** [comment]
@davidzbiral Temporary solution is auto adding wildCard silently. So now it searches with wildCard. Your requirement needs more complex regex on BE.

**Comment by jancimertel** [comment]
@davidzbiral as mentioned, wildcards has been implemented here #768 
@Ptrhnk fixed this problem currently by adding the * chat at the end. This fixes:
`David`, `Dav*` but does not fix `Jr.` (`*Jr.` does). But the last case goes against the requirement you mentioned: optional shortening on the right. In this case i would like to play with manually adding '*' char on the left to emphasise expansion on the left.

Searching in the rethink does not work on `word OR/AND word` basis, its just basic `contains` search. To implement it with our current stack i would do several queries or split the label to additional field `TRP yyyy-mm-dd` -> array of `['TRP', 'yyyy', 'mm', 'dd']. I will try some solutions.

**Comment by adammertel** [comment]
Closed in favor of #1009
