### ISSUE TITLE
"Detail" not imported from Actions

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1006]
@tomaham : It seems that the "detail" field (aka "detail" column in gsheets) is not imported. Could you have a look, and perhaps rerun the parsing?
![obrazek](https://user-images.githubusercontent.com/55400794/166110236-fcaf8354-0458-455f-8c59-33745ca46ddd.png)

**Comment by davidzbiral** [comment]
It turns out the problem is broader. What has happened to the imported data? Why legacy ID is gone, the real ID has the form of an old (but also bad, prefixed) legacy ID (prefixed with a spurious R0010), no superclasses are set, metadata for Ts completely empty etc.?

**Comment by tomaham** [comment]
This was a child janci mistake and does not correspond to the state of things now. Closing.
