### ISSUE TITLE
change in datamodel? not working "all-parsed" data on import-data deploy

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#1008]
We have a "situation".  

![image](https://user-images.githubusercontent.com/3739529/166137497-4236dc84-34ab-4907-9083-5f3993b7b7b5.png)

Something changed around the recent updates, which makes the parsed data "all-parsed" dataset invalid and not working.

How we got here - 1) apparently you discovered some error and imported the "scam dataset" to the db on the stage impor-data,  2) David discovered that under his hands are wrong data (issue #1006),  3) i have tried to put there the right one.

Can you investigate the "internal server error"?  (Or it is maybe connected with the #991 ?)

**Comment by jancimertel** [comment]
there are two data-import npm scripts - i've used the bad one unfortunately.
The reason for the import is new indexes without which server could not work.
