### ISSUE TITLE
Test templates

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1040]

**Comment by davidzbiral** [comment]
I think I tested them and they work just fine!
Important observations for editors - but logical ones, and it all works well, are:

1) Sometimes you create the template exactly to assign a prop to an actant. In those cases, of course, you must, in the template, include another entity _template_, not an _entity_; e.g. for "but he did not see heretics", you must create a G-template actant to be able to assign the prop "social category - heretic" to it (see screenshot). Then the user must, in the S prefilled by the S-template, remove the G-template and replace it with an actual new G.
![obrazek](https://user-images.githubusercontent.com/55400794/175825222-b7de6c26-6553-474e-9a44-a1aaa207614e.png)

2) If creating a statement-substatement chain, then again, the substatement (which is an actant) must be created as another S-template. So far, however, we have no way of creating this double-statement derivative anyway by using one template, so it does not help as much as it could - but we are not at this stage, since this would require a new solution; so let's leave statement-substatement(s) templates and multi-statement-chain templates for a future version, depending on priority / requests.

@adammertel : can you read this, ask questions if I haven't explained something enough or tell me if you think I am somehow misusing the templates, and, if closed from your side, close this?

@rljshaw please have a look here as well for the S templates functioning, and at https://dissinet.cz/apps/inkvisitor-data-import/#territory=ae4f30b9-07f0-4bce-ab1c-886d30009c15&detail=c6ee732a-26b4-40ae-bbd9-261303f09150&statement=c6ee732a-26b4-40ae-bbd9-261303f09150 as an example. Tx.

**Comment by davidzbiral** [comment]
@adammertel : No, this will not work at all. Remember that we always have a _different_ G entity for a new group of heretics. Having an actual G would mean that it is the same group in any use of the templat, which is incorrect.
Using a G template is the only way to attach a property.
That removing it is not ideal, is clear - but it is unfortunately the only way how to also prefill the prop.
Don't worry, just count on the fact that template within a template is the way. I know it is.

**Comment by adammertel** [comment]
@davidzbiral just a note - template inside a Statement is valid ONLY in case the statement is a template :)

**Comment by adammertel** [comment]
@davidzbiral Does the `social category` - `hereticus` belongs to the statement prop? Or is it more a meta prop that should go to Detail?

And do not forget that we still have the note, where we can store information about the entity type so the users know what they are supposed to fill.

**Comment by adammertel** [comment]
@davidzbiral sorry for spamming, but there is one more note to make. The planned functionality of the Suggester was that a new Entity will be created after selecting a Template in the list. This was in line with the idea that the actual template shall not be selected from the Suggester in places where the actual entity shall be placed (e.g., actant, prop value/type).

So if you really think that a template may be placed in a position for actual Entities (e.g., actant), we should count with this in UI, so the suggester list item has two functions - (i) select the actual template, and (ii) create a new entity from the selected template.

**Comment by davidzbiral** [comment]
@adammertel : Any follow up on this - the decisions for the two previous posts?

**Comment by davidzbiral** [comment]
@adammertel Reminder of this.

**Comment by adammertel** [comment]
Three new issues were created to solve this problem:
[ ]  #1459
[ ] #1460 
[ ] #1461
