### ISSUE TITLE
Redesign the core semantic relations (superclass/subclass, synonym...), and possibly ontological relations (identification...)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1042]
It turns out it is strange to construct some core semantic relations through metaprops, because metaprops:
- Are sensitive to change (e.g. relabelling by somebody, even removal in the extreme case).
- Have a different UUID in different deploys and projects (bad for interoperability and even semanticity, ensured thus only through a treebank ID of the meaning of the C used as prop type, e.g. C "equivalent"). 

Therefore, we are redesigning the core semantic relations as "reserved" and not done through metaprops. Priority, because it is a blocker for parsing Cs and As and for starting new data work in InkVisitor.

What the new solution must consider:

1. We need "detail" in them to instruct editors.
2. They themselves are arranged in superclass trees (e.g. synonymy and antonymy both have superclass e.g. semantic relation), and the DB should be queryable through these superclass relations. (Mind that users do not know so well what they do not have access to, i.e. attributes are less accessible to them than (meta)props.)
3. They themselves have different semantic relations: e.g. synonym reciprocates synonym.

But the pros are:
- Coherence of these relations between projects.
- Higher semanticity.
- Suggester of the "synonym" relation can prioritize sister terms which also have the "superclass" relation to this.
- !!! We can find a GUI solution which will use superclass, equivalence etc. generally beyond deploys (and projects)!!!
- It is an important step towards solving #870 and #827.

TBD:
1. Is not ontological identification a similar thing and thus should it not be solved n the same way?
E.g.: (en) Paris - has - **identical entity** - (lat) Lutetia Parisiorum is a similar type of relation.
Pro: need to find cross-project GUI solution for helping the choice of entity by showing its superclass, equivalents etc. (3rd and 4th line of mouseouver).
Contra (Adam): but this has certainty, possibly also elvl => needs the (meta)prop machinery.

!!! 2. Problem: this also concerns class/instance, which we make come from within statements, i.e. is not "in" the Entity; how to solve this? @rljshaw I tag you here, I think we have class/instance in the Statement not in the Detail.

DZ subtasks:
- Look at this set of identical entity etc. relations and find their system.
- Get feedback from team on this (reasonably major) change.
- If done, issuize both for dev and legacy data parsing.

**Comment by adammertel** [comment]
Is there a possibility to list all the semantic relations types?

**Comment by davidzbiral** [comment]
@adammertel : this is the matrix - done in the Concepts list still - and there is valuable information there, so it should perhaps be some special clase of "reserved uneditable Cs" rather than something else!!! in their structure:
https://docs.google.com/spreadsheets/d/1nSqnN6cjtdWK-y6iKZlJv4iGdhgtqkRPus8StVgExP4/edit#gid=0&range=BN5:BP5
It is 3 cols with y(es)/n(o). The first captures Actions, the second, Concepts, and the third, PLOGE (physical-world entities).
Blank = N/A, don't look here even. Just look at "y" in fact in a given col.

Does the notation work for you? How to proceed further?

**Comment by davidzbiral** [comment]
@adammertel : 
The direction I am going is to have them as some special class of Cs rather than completely apart, which:
- Will always be part of the InkV / db package under a reserved UUID. The projects may or may not use them, but they will be reserved in case they want to (only displayed in Detail if non-empty => not a big problem).
- Are editable in the same way as normal Cs - but by admins only.
- Are displayed in a special section of Detail, similarly to Metaprops but somewhat apart.
- Can only be used to relate entities at the metalevel, in a similar way as entities.

**Comment by adammertel** [comment]
@davidzbiral I disagree with this idea.
Securing special entities within the same collection as the "normal" entities and having all the special rights and edit sections for them is definitely not a good practice. 
And the argument is only that we can choose custom names and links between these <10 entities?
Let me go through the list of relations and provide a more systematic approach. 
I think this is really important for (i) convenience of the data collection, and (ii) their special importance in the data analysis.

**Comment by adammertel** [comment]
@davidzbiral If I understand correctly, the semantic relations have these types:

 - synonyms, equivalents (including the translation), and troponyms
 - superclasses / subclasses
 - reciprocal, and opposites

Is there something else I forgot about?

**Comment by davidzbiral** [comment]
@adammertel: The main argument is not custom labels but the production of DDB2 relations involving those core semantic relations. I.e., it is interesting to store somehow that if A is synonym of B, then B is synonym of A, and if A is reciprocal of B, then B is reciprocal of A (to symmetrize e.g. kinship relations in DDB2 to a full kinship network rather than just kinship explicitly mentioned). We have all the devices of storing this in Cs, while we would have to develop and maintain them somewhere else if those core semantic relations are removed from C's - that's the issue. (BTW I generally dislike the fact that I cannot access the dictionaries, they are too hidden from me, I feel it as big uncertainty, something I cannot check - could you make it more accessible to editors?)
You might be right and we might want to really remove this from Cs completely, but the issue of production of DDB2 relations from core semantic relations remains - it could fall under the same routine if they are special reserved Cs, while if these are non-Cs, a new routine must be maintained and thought of in between DDB1 and DDB2.
A very typical example is to append the role described by actant slot semantic to any holder of that slot in DDB2.

> I believe "antonyms" are really not necessary to tag manually and the ability to check the cross-language state could be done by the attribute of language.

- Antonyms will be needed in more semantic-based, "literary" projects, where they will analyze less the state of the world and more the state of the text, e.g. whether antonyms have a similar or different syntactic and discursive context. We might need this as well. So antonyms must remain. But our usage can be - and as you have seen, already is - not to add them much.
- Cross-language: I agree.

**Comment by adammertel** [comment]
@davidzbiral I understand that you want to construct everything in the data model and have control over this kind of data, but I believe that this move will make the application more complicated for editors and the data outcome less  data analysts.

Maybe my perspective comes from the argument that InkVisitor data model should be more about modelling texts. For the analysis of this data, we need some semantic relations - but they are more about modelling "world" than the text itself. 

I also do not find good that the editors and analysts are that much dependent on the concept "Synonym" while it is really important in the reconstruction of the reality. 

Also I think that the semantic relations are very much objective, not dependent on the content of the texts and the view of the editor. While the "son-father" relation should be "collected" only from one side which is relevant to the text, the synonym concerns always the reality, does not come from the text and in general, it is indisputable. So if A is synonym of B, we may show the editors that B is synonym of A instantly without the need to check the truth.

**Comment by adammertel** [comment]
> BTW I generally dislike the fact that I cannot access the dictionaries, they are too hidden from me

It is not common that the internal db values are exposed to the users :) The "translations" for dictionaries are in this [file](https://github.com/DISSINET/InkVisitor/blob/dev/packages/shared/enums/index.ts), the list of all dictionaries can be found in this [folder](https://github.com/DISSINET/InkVisitor/tree/dev/packages/shared/dictionaries)

**Comment by davidzbiral** [comment]
Meeting Adam & David 27 May 2022:
- Adam agrees that ontological identification needs to be a reserved core relation (just it needs to have attributes).
- Adam firmly supports that class/instance should be a core reserved relation, and thus: (a) it needs to be reserved and belongs exclusively to Detail; (b) their target should probably be Concepts whose label language is the metalanguage (English in our case; i.e. apple, not pomum) - even if (DZ) this is somewhat mitigated by the fact that we record synonymy and same treebank (WordNet) meaning IDs, and thus are going towards lemma-meaning relation - Latin only when there is no good enough English equivalent C; (c) for textual classifications which are analytically important for a given project, and thus should be absolutely recorded at the textual level and in the Statement, not Detail, definitely another relation should be used than class/instance: e.g. C social category (for social categorization), C "categorization" or something like that (for an O pomum appearing first as "pomum" (-> C pomum) and than as "this beautiful fruit" (-> C fruit, -> C beautiful), where we want to record this textual distinction). This is quite logical, because we should have an option that even if a text considers apples to be, say, animals, we must still be able record them as apples by the reserved class/instance relation (thus in Detail, elvl3 by imposed default), but also to record that the text's textual categorization is C animal. Important to achieve agreement on this with @rljshaw and, if achieved, expand on this in the guidelines. 
- Adam proposes to have those ontological relations in Detail even in case when they are made in the text, i.e. he would revert the logic deal with them Detail and append a T and R reference there × tensions with some basic principles of our approach, @adammertel keep thinking about options, because this really clashes with a very general principle; I would like them to be made either in-statement, with elvl1-3 options, or in Detail at elvl3. Therefore, @adammertel, I propose either to allow it both at elvl1-3 as in-statement relation AND elvl3 general editorial relation, or a solution similar as in class/instance, i.e. making the reserved elvl3 firm identification in Detail only, but also having a prop to mark the same thing at a textual level, which the editor can or need not follow ("believe") in Detail at elvl3.
- I am fine with losing the tree of semantic relations for queries - there is not so many of them and the scenario of searching all semantic relations in the DB of a word (e.g. both antonym and synonym) is not very likely.
(I tag @rljshaw, @davorsalihovic)

**Comment by rljshaw** [comment]
I still strongly disagree with the idea of changing "Class".  Class is about ontology in the way we have used it, yes, but specifically it is a textual ontology - i. e. an ontology from the perspective of a moment in the text. This is fundamental to what we have taught people about our approach too - on questions of ontology, we have thus far leaned towards a certain nominalism I think, since we "model the source first" rather than a fixed "reality", (which is really just an editorial perception of that reality, although we also provide ways of capturing that to provide balance). 

What you speak of here is  "Editorial ontology". And if you need a new reserved relation I would call it just that. It is not "class" in a textual sense, but rather what you think it is. I have no issue with having the option to record something like that and relate it to an English language concept - useful perhaps for editorial disambiguation (e.g. to say an apple called an animal is really ultimately an apple), just as it is useful for us as editors to define Entities in broad ontological types (e.g. as Persons, or Objects). 

There is thus no issue with the idea of recording editorial ontologies. But I think this direction described has the issue the wrong way round. If we are modelling the source first, as we claim, then our editorial decisions on ontology should be as general as possible, only going further into detail as necessary. The more essential part is capturing textual ontologies. These can be textual ontologies of essence (for which we use "class") or more obviously ephemeral classifications (e.g. when we use "social category"), but they bear more in common to one another than fixed editorial ontological classifications. Labels can change - and you can add a new "class" (or "social category" or whatever) when it does so, and again when it changes back or changes to something new. It is a simple system for coders that directly models the source.

**Comment by davidzbiral** [comment]
@rljshaw : I tried to address this here: https://dissinet.slack.com/archives/CFF247QFK/p1653712065311239?thread_ts=1652246862.755069&cid=CFF247QFK, let's discuss there and in person.

**Comment by davidzbiral** [comment]
For my reference: https://docs.google.com/document/d/1cqr-kIF_W6voea7RHjf1vFv-BRKRdcFIiqDLLfjK7BE/edit#

**Comment by davidzbiral** [comment]
@adammertel: please review here the implementation instructions:
https://docs.google.com/document/d/1cqr-kIF_W6voea7RHjf1vFv-BRKRdcFIiqDLLfjK7BE/edit#
Do we need to meet or is it clear? Mind the notation. E.g. if I say "A to C, C to A", it means that "A to A" or "C to C" is _not_ allowed.

**Comment by davidzbiral** [comment]
@Ptrhnk : I don't know what your agreement is with Adam on this, but in any case, this is the utmost priority, because it hinders starting the actual data collection and parsing older data.

**Comment by davidzbiral** [comment]
@adammertel : The possibility is still on the table that this will be basically **properties**, i.e. that these core relations will be signalled as **attributes** (something like "template" attribute, structurally) of several types ("select") under each C, and these will receive special treatment. For my part, this is still something which connects the best to the overall data model. But please propose your preferred way (how it should look like in the technical / JSON-level data model), and let's discuss.

**Comment by davidzbiral** [comment]
@adammertel : I need to add the `C0624	SRP in / superordinate location` to the mix. They mean, in Locations, almost the same thing as superclass in Concepts, and I even thing that they should be just as easily accessible, perhaps in fact the solution could be the same as for superclasses (btw it reciprocates `SRP subordinate location` of course, whose treatment could I hope again be similar to subclass). This is again collected, as with superclasses, only one way, i.e. bottom-up, to superordinates. 
This being said, I am adding this to our gdoc.

**Comment by davidzbiral** [comment]
@adammertel : I think even more that higher accessibility of this should be done through **entity element mouseover** - under detail field. This is the best place to make these core relations more accessible.

**Comment by adammertel** [comment]
@tomaham, the models were updated, including the relations.
You can see the changes here https://app.diagrams.net/#G1bKvqEKr6JzPWryVg-vYudQy_4KvuzHS9

**Comment by davidzbiral** [comment]
@adammertel: I think this is done - the remaining things regard not the data model, but the display of reciprocal Relations. We can close, I think?
