### ISSUE TITLE
Entity creation modal (from suggester): make entity type, not label, the active element

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1044]
Now, the active element is the label (the cursor is there). But the active element should be the entity type select, i.e. on arrowdown, the select should unfold.

Rationale: the label is already written when searching. The modal only opens if the entity type is not selected => makes sense to put its selection in the focus as the active element.

![obrazek](https://user-images.githubusercontent.com/55400794/167771458-d33a4334-91fb-41c3-ab6e-80cc3a5abfc9.png)

**Comment by Ptrhnk** [comment]
@davidzbiral 
I was not able to change everything at once in actant modal so I made checklist in #763

**Comment by davidzbiral** [comment]
OK, thanks, closing as a duplicate.
