### ISSUE TITLE
New reference; changing the parsing notation for references

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1046]
1. Please include a new col. in Actions and Concepts into the parsing: wordnet_sense_key. 
2. I had an inconsistency in the notation of wordnet cols between Actions and Concepts ("special" vs. "reference"). Now unified to "reference".
3. In cols. to be parsed as "reference", I now added the Resource ID (R entity) to the row no. 3, and created those entities in the normal [list of Rs](https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=583750775).

**Comment by davidzbiral** [comment]
@tomaham : tagging you just in case so that you see this.

**Comment by tomaham** [comment]
@davidzbiral  Yes, I see this.

**Comment by tomaham** [comment]
@davidzbiral  The new import batch "Import batch [development] 2022-05-17 19:49:28.471601" should take this into account.
