### ISSUE TITLE
Defaults in metaprops incorrect or incorrectly parsed

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1048]
Unlike normal in-statement props, metaprops have some default values which, @tomaham, are not right in the current parsed data (v. 1.2.0  | data-import | built: Fri 13.05.2022 16:59). Some of them (logical operator) were right in the previous import - what happened to them since, I don't know, but we need to rectify this **in the workflow** (not just in the current data, but really in the workflow, otherwise, some big průser is to be expected with nearcertainty).

Whole metaproperty statement:
- elvl always "inferential" (i.e. 3)
- mood "indicative"
- mood variant "realis"
- logical operator "and" (this was solved, but now it is again "=" by some mistake!!!)
- certainty "-", not "certain

Metaprop Proptype: 
- elvl "inferential" (i.e. 3)

Metaprop Propvalue:
- elvl "inferential" (i.e. 3)

Otherwise seems OK - i.e. this is not to list all defaults, just diferentially to the current data import (see screenshot below).

This all only concerns metaprops, not in-statement props. If this is a reason to divide IProp into two, i.e. IMetaprop and IProp, let us go ahead with this if @adammertel approves - perhaps it is now the same data type and perhaps it creates some problems, I don't know.

![obrazek](https://user-images.githubusercontent.com/55400794/168426327-9700b8fb-2ca0-4539-9747-3677989536e1.png)

**Comment by davidzbiral** [comment]
@rljshaw : can you please cross-check the defaults on principle, and if not correct, tell me here?

**Comment by adammertel** [comment]
@davidzbiral I understand that these are default values. 
In the case of `epistemic level`, we decided to disallow all the other options than `inferential`. But what about other attributes for metaprop statement (e.g., mood `indicative`) - are those mandatory values that will not be possible to change or those are only default values? 
In case all the values you mentioned are not to be set by the user, I would probably hide them in the UI. I am not sure if a division of the model is a good idea now.

**Comment by tomaham** [comment]
@davidzbiral  This problem probably still persists in the import data.

The present approach is: not make any hardcoded object division between Prop and MetaProp, both still use interface IProp (right @adammertel ?).   So to have the right epistemic level in MetaProps, the context of the import needs to be used (my problem).

@adammertel I am not sure about "certainty" and value="-", the code allows just "0", so "0" is the targeted ="-"?

@davidzbiral The defaults of import for props are okay? (e.g. there is no mood in the default, this is right?)

So this is what we have for **IProp as default**
`    'IProp':{
            'bundleEnd':False,'bundleStart':False, 'certainty':'1', 'children':[], 'elvl':'1',  'id':'', 'logic':'1', 'mood':[], 'moodvariant':'1', 'bundleOperator':'a', 'type': {'id':'','elvl':'1','logic':'1','partitivity':'1','virtuality':'1'},'value':{'id':'','elvl':'1', 'logic':'1', 'partitivity':'1', 'virtuality':'1'}
        },`

And this is what we should have for **IProp used for Metaprops**
`    'IProp':{
            'bundleEnd':False,'bundleStart':False, 'certainty':'0', 'children':[], 'elvl':'3',  'id':'', 'logic':'1', 'mood':['1'], 'moodvariant':'1', 'bundleOperator':'a', 'type': {'id':'','elvl':'3','logic':'1','partitivity':'1','virtuality':'1'},'value':{'id':'','elvl':'3', 'logic':'1', 'partitivity':'1', 'virtuality':'1'}
        },`

Right?

**Comment by adammertel** [comment]
> @adammertel I am not sure about "certainty" and value="-", the code allows just "0", so "0" is the targeted ="-"?

Yes, "-" is a label, the value in the entity is then "0"

> The present approach is: not make any hardcoded object division between Prop and MetaProp, both still use interface IProp

I am not that fixed to this solution. If David confirms, that the number of possible values for meta props is radically different than the classical in-statement prop, I am okey opening the discussion of having two IProp models.

**Comment by rljshaw** [comment]
@davidzbiral can confirm your proposed defaults are correct. 

As for the question of whether things other than epistemic level should be "locked" to the defaults with meta props, my view is probably yes, since I cannot see when a non default value would be used in meta properties, but I may be forgetting something that @davidzbiral will remember!

**Comment by davidzbiral** [comment]
> Are those mandatory values that will not be possible to change or those are only default values that is possible to change by the user?
> In case all the values you mentioned are not to be set by the user, I would probably hide them in the UI.
> 

@tomaham , @adammertel : I confirm Adam's solution.

**Comment by davidzbiral** [comment]
The list of those default values is clear or not?

**Comment by tomaham** [comment]
@davidzbiral It seems clear, but do I interpret it right? :D  That is the question. Check the value below, please.

The defaults of import for props are okay? (e.g. there is no mood in the default, this is right?)

So this is what we have for IProp as **default**
`'IProp':{ 'bundleEnd':False,'bundleStart':False, 'certainty':'1', 'children':[], 'elvl':'1', 'id':'', 'logic':'1', 'mood':[], 'moodvariant':'1', 'bundleOperator':'a', 'type': {'id':'','elvl':'1','logic':'1','partitivity':'1','virtuality':'1'},'value':{'id':'','elvl':'1', 'logic':'1', 'partitivity':'1', 'virtuality':'1'} },`

And this is what we should have for IProp **defaults** used for **Metaprops**
`'IProp':{ 'bundleEnd':False,'bundleStart':False, 'certainty':'0', 'children':[], 'elvl':'3', 'id':'', 'logic':'1', 'mood':['1'], 'moodvariant':'1', 'bundleOperator':'a', 'type': {'id':'','elvl':'3','logic':'1','partitivity':'1','virtuality':'1'},'value':{'id':'','elvl':'3', 'logic':'1', 'partitivity':'1', 'virtuality':'1'} },`

**Comment by davidzbiral** [comment]
@tomaham , @adammertel : where I can find a textual translation of the values, e.g. logic "1", partitivity "1". I cannot read this, I must see the textual values. I suggest even that this is permanently maintained. Perhaps the InkVisitor dictionary/ies are somewhere on GitHub - if so, can we make them more findable by people like me?

Other than that, the defaults in a normal prop should be: 
- Certainty = "-" (0), not 1.
- Mood = "indication", not empty.

**Comment by davidzbiral** [comment]
@adammertel , @tomaham:

Let us leave the IProp model for both normal in-statement props and metaprops for now, and only lock the values in metaprops. There might be projects other than ours, which would like to store some things as metaprops that we wouldn't, e.g. that something does _not_ have some quality (negative logic). There also might be projects which, by legacy necessity, will also parse some data into this structure, and some things that normally should be props will be parsed from entity tables as metaprops, but will be set to elvl1 (even if not correctly referenced to a T and R).
So let us only lock the metaprop values (and set proper defaults in parsed data), not change the models.

**Comment by davidzbiral** [comment]
> But what about other attributes for metaprop statement (e.g., mood indicative) - are those mandatory values that will not be possible to change or those are only default values that is possible to change by the user?
> In case all the values you mentioned are not to be set by the user, I would probably hide them in the UI. I am not sure if a division of the model is a good idea now.

They are mandatory (in _metaprops_) - at least we now think so :-).
Yes, this is what we will do now: hide them in the GUI. And thus, the cogwheel button will disappear from metaprops.

**Comment by adammertel** [comment]
@davidzbiral 
> where I can find a textual translation of the values,

The "translations" for dictionaries are in this [file](https://github.com/DISSINET/InkVisitor/blob/dev/packages/shared/enums/index.ts), the list of all dictionaries can be found in this [folder](https://github.com/DISSINET/InkVisitor/tree/dev/packages/shared/dictionaries)

**Comment by adammertel** [comment]
Thanks @davidzbiral  for clarifications. I created #1067 and #1068 to apply these changes inside the InkVisitor.
All the "default" "mandatory" fields will be applied on the creation of the meta prop and will be hidden in the modal.

**Comment by adammertel** [comment]
@tomaham I removed the application-relevant tasks to new issues, so consider this issue as a data-parsing one (= its yours now :))

**Comment by davidzbiral** [comment]
@tomaham : is this solved?

**Comment by davidzbiral** [comment]
@tomaham We now removed most things in metaprops, so much is solved, but certainty and logic remain. Defaults are: logic = positive (OK in current import batch, but certainty = "-" (which is, I think numerically the value 0). Here, the current import is incorrect, it has certainty = certain.

**Comment by tomaham** [comment]
Should be corrected in the Import batch [development] 2022-10-22 18:54:22.598885

**Comment by davidzbiral** [comment]
Checked as corrected on a couple of examples in the Import batch [development] 2022-10-22 18:54:22.598885. The only remaining issue is the default mood "" (empty) instead of 1, asking Adam about this in the open issue #976. Closing this one.
