### ISSUE TITLE
Still not finding whole word for whole word in Suggester and Search

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1066]
E.g., I should find "social category" by searching "category". Now it does not work - either in Suggester or in Search.  We must misunderstand one another quite a bit re: search. Please request a meeting if you don't understand what I want. 

As I say, whole words must find whole words, wherever in the string they appear. Please implement asap.

Without this, hundreds of spurious duplicate entities will be created by editors.

![obrazek](https://user-images.githubusercontent.com/55400794/169493948-2955231f-a9d5-4346-be29-0469c1185eb0.png)

**Comment by Ptrhnk** [comment]
But the issue is open and is in progress #1009
