### ISSUE TITLE
Revise metaprop attributes

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1086]
Based on perhaps some of my requests, "certainty" was removed as metaprop attribute, and there is only logic now, while some other things are in metaprop proptype and propvalue which should disappear.

In metaprops, lock (hide) everything apart from:
whole metaprop: logic, certainty (plus elvl is there ontologically speaking, but always 3)
proptype: [nothing - hide all]
propvalue: [nothing - hide all]

**Comment by adammertel** [comment]
@davidzbiral so this is what the model should look like at the end?
![image](https://user-images.githubusercontent.com/12932677/173245627-2b592874-f8b5-47be-ba38-49600faaf5dd.png)

**Comment by davidzbiral** [comment]
@adammertel : yes.
