### ISSUE TITLE
New user creation does not work

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1098]
New user can be created, but gets no email on the stated email address and no credentials to access the app.
Tested in https://dissinet.cz/apps/inkvisitor-data-import/, 16 June 2022.

**Comment by jancimertel** [comment]
I believe emails haven't been enabled for test environments. 

However there has been an issue - google changed their policy yet again ...+ it broken existing solutions ie. https://github.com/nodemailer/nodemailer/issues/871

cannot make this work for now, switching back to sendgrid :/

- emails are working again
- added input for testing emails
