### ISSUE TITLE
Too loose search algorithm in Suggester still leads to serious errors

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1100]
Please pefer exact match in the results list. E.g. "sacrament" exists, but is probably too low in the search results, and thus gets outside of the permitted number of matches. This means that editors will create a new "sacrament" concept - which for our approach is a fatal error.

![obrazek](https://user-images.githubusercontent.com/55400794/175078865-eccf6fa8-e6e4-40af-8b8e-7b02e800ef66.png)

**Comment by jancimertel** [comment]
I've added sorting:
- sorting by original label distance ( if input = sacrament, then entity 'sacrament something' has distance = 0, 'new sacrament' has distance 4)
- sorting by label length ('sacrament test' has length 14, 'sacramentum' has length 11)

Greater values will push results to the end of the list, so exact match will be always first.
Deployed on staging/data-import. Test please and let me know :)

**Comment by davidzbiral** [comment]
@jancimertel : Thanks for trying.
I am not sure about whether we want so much the first principle, "sorting by original label distance".
I like the second principle, "sorting by label length". Not sure whether this will solve all the problems - we need to prioritize full-word match. I.e. full word in the input meeting a full word in the label should mean prioritization. 
Is there a reason why full-word match (i.e. between full word chunks in input and full word chunks in result-label) cannot be prioritized even more than the other principles?

**Comment by davidzbiral** [comment]
@jancimertel , @adammertel : are we working on the understanding that Search and Suggester search use the same algorithm? I think they should.

**Comment by jancimertel** [comment]
@davidzbiral 

Point of the first principle is to move labels which start with the matched word/string to the front. It could be removed, but it provides better results if i'm searching for the first word.

Frontend is adding the wildcard to the end of the input by default - at least in the search window. This will conflict with full-word search in the backend.  When the wildcard wasn't there it matched words nicely, but  it didn't match 'sacramentum' if i provided 'sacrament' input. So if i understand correctly, now it should match substrings (not limited to exact matches) but prioritize exact-word matches? Current search algorithm is based on the idea here https://github.com/DISSINET/InkVisitor/issues/1000 with optional wildcards provided manually. If the manual wildcard should be used, then the automatic adding should be removed @Ptrhnk 

And correct - there is currently only one search algorithm on the backend.

**Comment by jancimertel** [comment]
i added additional sorting, which promotes exact word-matches. Works well in combination with length ordering.

'Regis' word found for 2 entities, other entries have the input as a substring.
![image](https://user-images.githubusercontent.com/10438157/175817350-d5e16445-4314-49c9-8230-9f86ea9e8139.png)

Needs to be noted, that sensitive/insensitive match for this ordering can yield different results. I've chosen case insensitive word-matching. In case of need i can change it.

**Comment by davidzbiral** [comment]
Great! I will test it still, but sounds just great and I think we can close - I would reopen if needed.
Case insensitive is the way to go - I fully agree, forgot to mention it.
