### ISSUE TITLE
Display all matching results in suggester search results

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1101]
In relation to #1100 : finding the relevant existing entity through Suggester is really critical to our approach - otherwise the editor will create a new one. Therefore, we need to see _everything_ that matches an agreed-upon search algorithm. 
We must make the suggester search algorithm stricter. But also we will probably need pagination or something in Suggester search results - the stricter algorithm alone will not be enough in the long run. The db will be big, and so some entities will match the whole-word search algorithm while falling outside of the allowed number of suggester query results. Thus, all I can think of is pagination.

**Comment by Ptrhnk** [comment]
Will be implemented by infinite dynamic scroll - React window lib.

**Comment by davidzbiral** [comment]
Great solution! 
What still holds though is that a more precise word-to-word match should have priority in the order of search results.
