### ISSUE TITLE
Users screen: slider needed

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1106]
Impossible to access (delete etc.) users more towards the bottom, even with 100% zoom. Please add side slider or something to allow pagedown, mousewheel, or click-to-pagedown operation.
![obrazek](https://user-images.githubusercontent.com/55400794/175824712-9d820e7d-8316-4b5d-af3b-027a4fe57d3f.png)

**Comment by Ptrhnk** [comment]
Needs complex handling - overflow: visible is needed for suggester but overflow: scroll is needed for longer lists
