### ISSUE TITLE
Better user creation: do not send password by email

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1107]
Could we make a better user creation? Now there are two problems:
1. password is sent as disclosed plain text through email;
2. the email regularly ends in the spam folder.
In the long run, we will want a more advanced user creation: with the user creating the account with their own pwd (with viewer rights and no T assigned), and admins (?) receiving an email prompting them to consider assigning Ts to the new user.
Is this the way to go?

**Comment by jancimertel** [comment]
1. after the rework, the password could be created by the user
2. can you elaborate on which email service is doing this? in gmail i haven't experienced such behavior.
  - gmail support removed, so using sendgrid
  - I've checked reports for deliveries, and for now no spam/bounce report.
  - Additionally, using sendgrid, there are more options to try 
    a) currently we are using gmail address for sender/reply. Since the real sender is not that gmail account, we would probably encounter a DMARC issue - it's always better to use our own verified sender domain (gmail is not ours). **Can we get dissinet based email address?** This will require to ask for some assistance from admins (someone who has access to dissinet dns entries)
    b) the template is plain text - prepared template could be better to avoid spam detectors (this could be done right now) 


The custom password can be created by implementing "magic link". User will see email receive url which will allow him to create the password.

Additional email to administrators is also possible.
