### ISSUE TITLE
InkVisitor app (any deploy) does not load on dissinet.cz today

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1138]
Server problem?
(Posting here because this is a way to reach more of you quickly.)

**Comment by tomaham** [comment]
Try it temporarily over vpn at http://dissinet.priv.phil.muni.cz/apps/inkvisitor-data-import/ .

**Comment by davidzbiral** [comment]
@tomaham : the login page loads here, but unable to log in with correct credentials.

**Comment by tomaham** [comment]
@davidzbiral I see, then sorry, it seems like a bigger problem on the server itself.

**Comment by tomaham** [comment]
I have started the rethinkdb service through systemctl command, it is running, but the admin page is still inaccessible. Weird.

**Comment by jancimertel** [comment]
the machine rebooted.

Ive started the services anew + added services to start at the reboot.
@tomaham jupyter notebook is installed under your user, can you run it now?

**Comment by tomaham** [comment]
@jancimertel  Yes, the jphub is now running .  (And everything is, it seems) 

What services you had started?  What other services were necessary so the rethinkdb admin page is available?

**Comment by jancimertel** [comment]
> @jancimertel Yes, the jphub is now running . (And everything is, it seems)
> 
> What services you had started? What other services were necessary so the rethinkdb admin page would be available?

sorry about the delay.

there is also the firewall/firewall-cmd service which is required even if testing it on the localhost due to proxying (request to port with localhost won't work normally). I will address these issues here https://github.com/DISSINET/InkVisitor/issues/1150
