### ISSUE TITLE
Self-registration of users (own choice of login and password), confirmation by admins

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1148]
- Choosing the email (checking whether it is a valid email address) and password.
- Confirmation link sent to that email to avoid email errors / inactive email addresses (text of the letter - use some good and free existing text as a basis). No access yet (notify).
- Admin confirmation & assignment of rights (e.g. to specific Ts) => email sent.
- Restore forgotten password.

**Comment by adammertel** [comment]
@davidzbiral are we doing this?

**Comment by davidzbiral** [comment]
@adammertel I think we can postpone. It would be individual deploys and we don't count on one large system with many users, rather research teams of 2-15 people working on an individual deploy.

**Comment by davidzbiral** [comment]
@adammertel : Again back to up-to-date issues, because we are granting testing access to users.

**Comment by davidzbiral** [comment]
@adammertel, turns out to be quite important - without a memorable password, I am not very able to show InkVisitor on projectors during conferences.
