### ISSUE TITLE
Deploy: full technical documentation of the process and testing it on real people

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1150]
Write up full tech documentation on how to deploy InkVisitor on a server, including:
- All technical aspects needed to do that successfully.
- Customization of dictionaries (e.g. certainty levels).

Test the quality of the documentation on a real IT specialist doing the deploy.

**Comment by jancimertel** [comment]
closing, readme is now validated and ready to be used.
Next - we should focus on more specific tasks for documentation.
