### ISSUE TITLE
Allow storing structured data protocols for any T

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1152]
Under any T, allow storing both structured and rich free-text data protocolling the data collection.
Somewhat connected to T statistics.

The structured data will include:
- Project's guidelines version.
- CASTEMO variant (SumCASTEMO, NoCASTEMO, SelCASTEMO, FullCASTEMO).
- Start date.
- End date.
- Mode/strategy of data collection: parts vs. whole; single-text vs. topic-driven (combined Ts: e.g. "mentions of lived parish religiosity in inquisition registers"); ...?
- ... a lot of things now in the gdoc protocols - but we must think about what is general and should be there, and what dictionaries to use.
- url - to external, more comprehensive documentation (should we support this and add url field, or rather discourage this?)
- Editors: display only, parse from statements' audits.

**Comment by davidzbiral** [comment]
This can be done through props hanging on the Territory, and thus be more a guidelines thing than a GUI thing , or - esp. if we want comparability between projects - it can be a GUI form (because for comparability and machine operable data, the difference in UUIDs using to describe it would pose a problem).

**Comment by davidzbiral** [comment]
See now [this gdoc for the initial proposal](https://docs.google.com/document/d/1pZUVztrMVQKxJCM61OxZ5B1I1tdGU1ueAVoEFrn7z1M/edit#).

**Comment by davidzbiral** [comment]
Edited now to enable this for any T, working with implicit inheritance down until conflict, not just root Ts.

**Comment by davidzbiral** [comment]
Very relevant in this context: #1924

Proposal: 
1. Let's understand protocol as applying to a given T (which does not need to only be a root T) and all its children unless conflict (no problem for textual notes, solution only needed for the more formal fields, cf. #1924). 
2. Let's implement it as a special important section of the T model (i.e. edited in Detail).

Up-to-date proposal of structure:
### Territory data collection protocol
## Data collection campaign

- Project (text field)
- Guidelines version (text field)
- Data collection guidelines URL (text field)
- CASTEMO variant (select: SumCASTEMO, NoCASTEMO, SelCASTEMO, FullCASTEMO, MGSTEMO)
- Description [multi-line text field]
- Start date: [suggester, accepting V entity]
- End date: [suggester, accepting V entity]

## Statement validation rules
+ add new rule (select/switch: binary/entity; on this, see #1924)

**Comment by davidzbiral** [comment]
Probably implement this issue together with #1932.

**Comment by adammertel** [comment]
Created three more issues following this idea:
[ ] #1960 For extending the BE model
[ ] #1982 For UX design to edit the root T (global campaign)
[ ] #1983 For implementing new section in Detail
