### ISSUE TITLE
Bug: Activate new user / refreshing users page as admin fails with 404

### ISSUE THREAD

**Issue by GideonK** [DISSINET/InkVisitor#1169]
**Description**
1. Attempting to activate a newly created user from the mailbox link leads to 404.
2. Attempting to refresh the users page logged in as admin leads to 404.
3. Possible bug: Previously created user (Gideon) was absent when logging in as admin on 05.08.2022.

**To Reproduce**

***Activating the newly created user***
1. Visit https://dissinet.cz/apps/inkvisitor-data-import/ in browser.
2. Log in as admin.
3. Click on "Manage Users".
4. Add a new user using the text boxes at the bottom of the page.
5. Open up an email client that can access the email sent. Microsoft Outlook was used in the case that led to the bug.
6. In the email, click on "Activate", which attempts to open an activation link. A "Not found" message appears.

***Refreshing the users page***

1. Visit https://dissinet.cz/apps/inkvisitor-data-import/ in browser.
2. Log in as admin.
3. Click on "Manage Users".
4. Refresh the page. A "Not Found" message appears. Refreshing the entry page (https://dissinet.cz/apps/inkvisitor-data-import/) leads to no error.

**Expected behavior**
For both cases, the users page was expected to display, similarly as when visiting the page from the entry page (https://dissinet.cz/apps/inkvisitor-data-import/ => https://dissinet.cz/apps/inkvisitor-data-import/users).

**Software environment**

The browser and OS used that led to the bug was Google Chrome 103.0.5060.134 (now updated to 104.0.5112.81) and Microsoft Windows 10 Home Single Language 10.0.19043.

**Comment by Ptrhnk** [comment]
Fixed by Apache server config.
