### ISSUE TITLE
Change `id` in `IPropSpec` to `entityId`

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1171]
- `id` in `IPropSpec` -> `entityId`
 - `actant` in `IStatementActant` -> `entityId`
 - `action` in `IStatementAction` -> `actionId`
 - `id` in `IStatementData.territory`  -> `territoryId`
 - `id`  in `IParentTerritory` -> `territoryId`

**Comment by adammertel** [comment]
Models in `shared/types` changed

**Comment by adammertel** [comment]
@tomaham could you please reflect this in the data parsing? Also, if you have some ideas to improve the consistency in naming...

**Comment by tomaham** [comment]
Sure.. I suppose it is not change which is alive on the import-data deploy?

**Comment by adammertel** [comment]
No, not yet. For now, it is in the branch `relations`. We can get in touch the next week to decide how to proceed.

**Comment by tomaham** [comment]
@adammertel  I guess, this is solved?
