### ISSUE TITLE
Implement IResponseTagInfo on BE

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1185]
You are free to change the model's structure (let me know, pls) if you find the current suggestion not simple for implementation.

**Comment by jancimertel** [comment]
renamed to IResponseEntityTooltip (TagInfo -> EntityTooltip)

**Comment by jancimertel** [comment]
moved entity tooltip types to EntityTooltip namespace in https://github.com/DISSINET/InkVisitor/blob/dev/packages/shared/types/entity-tooltip.ts

**Comment by jancimertel** [comment]
implementation done, possible corrections later -_-
