### ISSUE TITLE
New "show" parameter of root Ts (TRUE/FALSE) needed; related changes to the T tree

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1189]
A) There are T entities mentioned in our texts, but which do not survive, typically reported fragments of lost texts. We often do not know their parent is (e.g., deposition records mentioned in another document but not extant). 
B) There are also many root T entities which are mentioned in our texts but we don't want to see them in the T tree, since we are not working on them (at least not now), and we simply do not want to see tens or even hundreds of irrelevant root Texts on which we are not working the CASTEMO way in InkVisitor.

Therefore, please: 
1) Introduce the "show in Territory tree" parameter to any T whose parent is root (edited in Detail).
2) Show only those root Ts in the T tree which have this parameter set as TRUE. TRUE is the default value.

Adam's analysis:

> 1. We still do not want to have any Ts (outside of templates) without a parent territory.
> 2. There are some fragmentary Ts that have no T structure and probably no statements - they are mostly mentioned somewhere in the text and we want to link them to the S as actants. A solution is to create new Ts, but assign their  parent territory to root.
> 3. These "fragmentary" Ts will be then automatically displayed within the T tree. While there may be a lot of these fragmentary Ts, we want to let the users to hide them from the tree. And this may be solved by introducing a new "show" parameter.
> 4. Later, one may decide to add more subT or some S to these originally fragmentary T [DZ: and set "show" to TRUE].
 
(For reference, the full discussion is here: https://dissinet.slack.com/archives/CFF247QFK/p1660706479761259.)

I tag also @tomaham: I don't think this affects data parsing (happy to hide irrelevant ones only in InkV rather than in a new column), but just in case.

**Comment by adammertel** [comment]
@davidzbiral we have been discussing this issue with other programmers @Ptrhnk @jancimertel @pondrejk and we think that a more consistent and meaningful solution (from the perspective of data collection and UI design) is to create an entity T:Fragments under the root T and organize all other fragmentary/lost/not-important T there.

**Comment by davidzbiral** [comment]
1. I do not understand what "entity T:Fragments" means - whether it is something special or just any root T containing all fragments and non-target texts (in the given project). I guess a completely normal T without any special attribute or anything?
2. What I don't like so much about the solution is its ontological incorrectness (some are fully-fledged, non-fragmentary Texts but treated as sub-Texts); the implication is also that the sub-Ts of this "folder" have an order, which normally follows the order of appearance in the used R. So it means slightly hacking the ontology.
3. _But_ against myself under No. 2, I have to acknowledge that I foresee also special tematic Ts such as "All mentions of suicide in oldest Chinese literature" for selective _cross-Territory_ data collection. (This is also why I finally ended up accepting the concept of Territory rather than Text as this entity's name.)

Therefore I think I agree, but with one important note. It will be good to have an encompassing Territory for _sets_ of "orphaned" Ts, rather than just this general "trash bin" you propose (sorry about the expression). E.g., I will create the root Territory "Non-extant records of the Guglielmites' trial", and put my fragments under that. Does it work for you? 

And this we can do ourselves, right? So pending answers under No. 1 and approval of the principle of _more_ root Ts to contain those fragments, we can consider the issue closed.

**Comment by adammertel** [comment]
T:Fragments entity is just a territory class entity named Fragments. There is nothing special about it, it is just created to contain all the fragment territories. Also, this is just one way how to deal with the problem.
If a Territory Tree Filter works, we can think about a way how to hide T with 0 (or less than X) statements on click.

**Comment by davidzbiral** [comment]
Following this solution, I created some new root Ts for non-extant texts. They have the metaprop for stating "not extant". Some of them are broad but can be characterized at least by genre (useful for using/not using them in an analysis), e.g. that it is trial records.
E.g.:
T151	Miscellaneous lost records of trial with the Guglielmites
T152	Miscellaneous lost medieval inquisition records
T151 is more specific, T152 is for the rest which can only be identified as (or which is not efficient to identify further than) lost, medieval, and inquisition records.
