### ISSUE TITLE
Core relations: submit a list and devise a notation for gsheet parsing instruction rows

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1193]
@adammertel:
1. Please add to the now newly added col. [our table of relations](https://docs.google.com/document/d/1cqr-kIF_W6voea7RHjf1vFv-BRKRdcFIiqDLLfjK7BE/edit#) their exact names in the JSON code.
2. Consider whether @tomaham needs to understand more about the types (cloud, tree etc.) for parsing or not - probably he does... So explain to him pls.

@tomaham:
3. For parsing instruction rows in gsheet tables, can we adopt the notation `relation` in row 4 (btw, obviously different from the already-implemented `reference`), and specify what relation it is, e.g. `synonym`, from the JSON notation submitted by Adam under No. 1 above?
4. Can you start implementing this in the parsing script? (We will need it shortly - Concepts and Actions are literally full of these relations.)

**Comment by tomaham** [comment]
@davidzbiral  Yes, we can adopt the notation.   As there will be at least testing data for importing, I can start implementing them.

We have already opened conversation with Adam around relations.
