### ISSUE TITLE
Unable to change password for existing user, also not able to log in

### ISSUE THREAD

**Issue by GideonK** [DISSINET/InkVisitor#1204]
**Description**

Attempting to change the password for a newly created user from the mailbox link leads to an error.

**To Reproduce**

_**Requesting to change the password for an existing user**_

1. Visit https://dissinet.cz/apps/inkvisitor-data-import/ in browser.
2. Log in as admin.
3. Click on "Manage Users" (go to https://dissinet.cz/apps/inkvisitor-data-import/users).
4. Next to a user for which access to the associated mailbox is possible, click on "reset password" (yellow icon with key).
5. Open up an email client that can access the email sent. Microsoft Outlook was used in the case that led to the bug.
6. In the email, click on "Reset the password", which should open a page in which a new password can be set (https://dissinet.cz/apps/inkvisitor-data-import/password_reset).
7. Type in the new password in both boxes and click on "Submit".
8. The first time, an error stating "endpoint not allowed" appeared. In two subsequent attempts, the message "missing user / invalid hash" appears. When logged out before clicking the email link, the reset page asks for a user name and new password. The username is apparently not recognized, leading to a "bad credentials" message. I tried the username "Gideon", as well as the associated email address "gideon.kotze@mail.muni.cz".

**Expected behavior**

The password reset page was expected to accept the new password using the credentials passed from the email link.

It was also expected to accept the log-in credentials when not logged in. To verify this, I logged out and tried the regular log-in procedure on the main page, using both the password saved in my browser, as well as the new password, which should have been accepted. In both cases the "bad credentials" error message appeared.

**Software environment**

The browser and OS used that led to the bug was Google Chrome 104.0.5112.102 and Microsoft Windows 10 Home Single Language, OS build 19043.1889.

**Comment by jancimertel** [comment]
The issue has been resolved in [#1204](https://github.com/DISSINET/InkVisitor/pull/1294).
Deployed for staging currently, data-import cannot be redeployed right now as it would possibly corrupt existing data.

Waiting for more info.
