### ISSUE TITLE
Implement ActionEventEquivalent C Tree to EntityTooltip 

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1235]
For Actions:
Implement a new attribute `ActionEventEquivalentTree` that will return the connected Concept and a 3-lvl tree of its `supperClasses`.

**Comment by davidzbiral** [comment]
@adammertel: but this tooltip only belongs under Actions: i.e., under Actions, showing the Superclass tree of the target C, but under C, don't do any inverse action.
