### ISSUE TITLE
New entity type: B - Being

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1261]
We need animals as entity type for cases where they act, i.e. assume actant roles, in ways different than objects. For some projects e.g. literary texts with knights and valiant horses, they will be even more important than for DISSINET (so they are a way to project neutrality). We discussed with Adam that better to implement them right away.

Please implement the B entity type (A for Animal is taken by Action, so we must use B - Being or Beast or Bestia). The B abbreviation already used since today in Action types list, needs to match with this new entity type. (This is why I also tag @tomaham.)

**Comment by adammertel** [comment]
@davidzbiral For B-Being, do we store logical type information (definite, indefinite, hypothetical, and generic options) like for P-Persons?

**Comment by adammertel** [comment]
@jancimertel please check the branch `entity-class-B-#1261` and if everything ok, please merge

**Comment by davidzbiral** [comment]
@adammertel Yes.

**Comment by jancimertel** [comment]
merged https://github.com/DISSINET/InkVisitor/pull/1275
