### ISSUE TITLE
Implement Extended Relation section for Entity Detail

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1263]
TODO:
[x] [#1269  Redefine relationship abbreviations]()
[x] [#1265 Design graphical mockup](https://github.com/DISSINET/InkVisitor/issues/1265)
[x] [#1266 Create response model](https://github.com/DISSINET/InkVisitor/issues/1266)
[x] [#1267 Implement response model on BE](https://github.com/DISSINET/InkVisitor/issues/1267)
[ ] [#1268 Inplement on FE](https://github.com/DISSINET/InkVisitor/issues/1268) 
[x] [#1407 Implement new response model for Tooltip BE](https://github.com/DISSINET/InkVisitor/issues/1407) 
[x] [#1408 Implement new response model for Tooltip FE](https://github.com/DISSINET/InkVisitor/issues/1408) 

also relevant 
[ ] [#1351 Set the maximal number of relations displayed in the tooltip ](https://github.com/DISSINET/InkVisitor/issues/1351)

@davidzbiral tagging you here to check if everything important is included at this point. The actual text takes some information from the "Reserved core semantic and ontological relations" document.
 
Also, @pondrejk, who made the first [graphical mockups in Figma](https://www.figma.com/file/UnnJ8msEBz9hU2oTfc2INh/Relations?node-id=0%3A1).

The idea is to show more information in entity detail (regarding the relations) than just the basic edit (add, remove relations) functionality. For details, see the Google Drive document

**Comment by davidzbiral** [comment]
@adammertel All good!
Just a minor thing on the abbreviations:

> Identification bych dal ID, pro lepší odlišení od IM (implication). Naopak u Related stačí asi R, protože žádná jiná na R nezačíná.
