### ISSUE TITLE
Do not return Relations with templates

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1272]
Linked to #1262 

One exception:
Classification and Related for PLOGESTRB

Other relations with Templates are not valid. If Synonym / cloud-type, remove that template entity from the list.
No entity can have classification to a Template, but a Template can have a classification towards non-Template (= a Template may be on the first position, index 0)

**Comment by davidzbiral** [comment]
I confirm this reasoning :-)
