### ISSUE TITLE
Fix Relations small bugs

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1280]
Good work with Relations (tested in v. 1.2.0 | staging | built: Sun 02.10.2022 23:08), guys! Admirable, most things seem very well done!
I have found only a couple of bugs.

1. I cannot unlink a Holonym (the usual icon for unlinking not there).
![obrazek](https://user-images.githubusercontent.com/55400794/193680085-51377485-fdd1-47ad-ae4e-eda495036fde.png)

2. Classification does not belong under C - remove it from C model.

3. Troponym to be dropped altogether (i.e. from the only model where it is - A model).

**Comment by Ptrhnk** [comment]
@davidzbiral Holonym is asymmetrical so it should be possible to edit only from the side that is created.
E.g. - this was created from [gate of monastery] so only there it should be removed. But if you create the one from current detail, you'll have an unlink button. Is that correct behaviour?

**Comment by Ptrhnk** [comment]
2) Ok

**Comment by davidzbiral** [comment]
@Ptrhnk OK, you're right that it is set from the other side.
But this incident shows that we need a more intuitive display of reciprocations in the other direction, because here the display is almost the same as if it was set here. I.e., somehow differentiating the relations that can be edited from here from those which are only reciprocations. For the latter, something like a subsection of Relations would be due, or something - similarly to Used in metaprops. I think we need a more straightforward display that it is not the holonym but the meronym (i.e. the inverse relation). 

What other Relations this affects, I don't have the time to think over right now, but the principle of showing those not set from here in a significantly different way, more different than just the lack of unlink button, is needed. Because our brain will read this "monastery - has - holonym - gate of monastery", which is false. And we will loose time thinking of how to correct it. So, some special section or something is needed.
