### ISSUE TITLE
Exclude A from allowed entity types in Actant suggester

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1282]
Action cannot be an Actant (I think - @adammertel please cross-check that I am not missing something). Thus, it should be excluded from the actant suggester select where you select entity type.
Statement can, anything else can, but not Action.
![obrazek](https://user-images.githubusercontent.com/55400794/193692083-8e7b3940-2434-426c-8f27-21b85050350d.png)

**Comment by adammertel** [comment]
Crosscheck - it really does not make sense to keep A in actants :) lets remove them
