### ISSUE TITLE
Three new Relations for actant semantics

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1284]
As discussed with Adam, add three new RelationTypes:
1. Subject semantics (Relationtype.SubjectSemantics)
2. Actant1Semantics (Relationtype.Actant1Semantics)
3. Actant2Semantics (Relationtype.Actant2Semantics)

- Only allowed for A
- The only allowed target is C
- Multiple, i.e. one A can have more of these Relations

No special treatment needed in the GUI - nothing needed in the tooltip.
Only in Detail, does not have any in-statement variant.

Placement in Detail:
Between Antonym and SubjectActant1Reciprocal probably.
But be considered: this is very connected to these attributes, so it would also make sense here - it would mean taking this from under the Relations heading, but it makes sense conceptually: when thinking about actant valency, I am thinking also about actant semantics. So from editors' perspective, it makes sense... happy to discuss.
![obrazek](https://user-images.githubusercontent.com/55400794/193826440-4d6b902d-f686-414d-809a-39cce27a96b3.png)

**Comment by adammertel** [comment]
@jancimertel Please check the branch `#1284` and merge it to `dev`

**Comment by davidzbiral** [comment]
@adammertel , @jancimertel : this is urgent for parsing gsheets data, please have a look at this. Tx!
