### ISSUE TITLE
"Related" Relations and Tags

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1291]
This is probably the same thing, only that the tags are in Statements and are an internal attribute of the Entity and Related are Entity Relation edited in detail.

The question: what about:
1. replacing the Tags in Editor with the Related Relations (and removing the tags from entity model)
2. replacing the Related relations in Detail with Tags (and removing Related from the list of relation types)

I am more in favor of (2.) while this information does not have an important analytical value (as is the case of other Relations)

**Comment by davidzbiral** [comment]
Related je hint k vyhledání věcí a úpravu vyhledávacího dotazu - háček k zachycení věcí, které by přes striktnější části ontologie mohly uniknout. Ne k přímému stažení nějakých dat do dataframu. Na druhou stranu se máloco bude stahovat na první dobrou do dataframu bez další iterace, takže jsou to trochu odstíny šedi, co je vlastně analyticky nadějné a co ne. 
Je to složitější otázka.
Kdyby to byly tagy, tak by se to paralelně muselo objevovat, když vložím v okně Statementu, taky v Detailu tohoto S, pokud ho mám otevřený - možná drobný GUI problém.
Dalo by se přemýšlet i šířeji, že není intuitivní otevírat Detail Statementu. Takže si říkám, jestli v případě Statementů nezobrazit celý obsah Detailu paralelně i dole v okně Statementu (úplně dole). To by promptlo editory např. zkontrolovat classification derivátu z S Template (dále S'), ale zas je to neorganické vůči celku...
Víš co, necháme to, jak to je. Tag zní ještě volněji než relace entit, vyzývá i k vložení V "My best statement ever", kdežto Related ne, to je přece jen trochu striktnější, zdá se, že k vložení V a takovýchto tagů to nevyzývá. Takže asi dobře, jak to je. Jen požádám v jiném issue o zařazení Related na konec, jako poslední - protože sémanticky nejvágnější - relace.
