### ISSUE TITLE
Order of Relations list: Related as the last

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1292]
RelationType.Related is the most semantically vague relation, and as such, put it as the last in the list in all entity models.

**Comment by adammertel** [comment]
@Ptrhnk would this be solved by an `orderIndex` attribute in the Relations enum?

**Comment by Ptrhnk** [comment]
@adammertel Possible to reorganize order of objects in shared/types relations.ts but if it helps readability, order can be added.

**Comment by Ptrhnk** [comment]
I did re-ordering on brach #1284
