### ISSUE TITLE
At 100% zoom on 13'' screens, the boxes are too wide to display

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1301]
At 100% zoom on 13'' screens, the boxes are too wide (Territory list does not appear at all, one must use horizontal slider).
![obrazek](https://user-images.githubusercontent.com/55400794/195508910-460ab888-4b22-48f3-839f-6c80cd22f7e9.png)

**Comment by Ptrhnk** [comment]
@davidzbiral There's a breakpoint to keep minimum width on small screens to preserve enough space for layout. Right now it's set to 1400px. So if the screen is less than 1400px, layout stays at 1440px. Nevertheless it's the matter of set up, so let me know what is your screen resolution so I can set it to fit your display.

**Comment by davidzbiral** [comment]
@Ptrhnk It says "1920 × 1080" - but don't know whether my screen should be the basis. No generalistic solution reasonably possible?

**Comment by Ptrhnk** [comment]
@davidzbiral I can set it to always fit the screen on every resolution and we will see if everything is well arranged on smaller displays and then eventually tune it up.

**Comment by davidzbiral** [comment]
@Ptrhnk This could work I think!

**Comment by adammertel** [comment]
@davidzbiral it may be necessary for the future to define the set of screen sizes and devices where the Inkvisitor will be supported and for what purposes (what functionalities will be available on what devices...). 
In case we want to go further with this, we should define a more complex system for the responsive design.
