### ISSUE TITLE
Menu changes

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1302]
- [x] Fix blur click - onHover => Implement from PopUp library?
- [x] Temporary hide Acl => turn on when page working
- [x] Preserve URL for main page #1314 
- [x] Decent animations
- [ ] #1501

**Comment by adammertel** [comment]
[ ] Create a simple page with User settings. For now, only a user name in the heading and maybe a simple setting option (e.g., dark/light theme?). This will be more interesting in 1.4
