### ISSUE TITLE
Refresh storybook

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1310]
For better orientation in components and easier changes, would be nice to rewrite with new props, types, dictionaries etc.

If not, then consider deleting - has too many dependencies and makes it harder to update other libs because of the dependencies, also shows a lot of problems on npm install because of it's amount of deps.

**Comment by adammertel** [comment]
I suggest deleting the whole ecosystem and finding another way to write tests on components.
