### ISSUE TITLE
Reorganize Tag component

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1311]
Needs to wait for #1331 
Motivation:
We need to gain more control about show up of tooltips on tags - don't show two tooltips when the Tag button is hovered.

Ideas:
Tag is used now only by EmptyTag and EntityTag.
Empty tag don't have button, DnD, tooltip..
Maybe move the tooltip call and the button render to EntityTag component. 
Other possibility is to disable main tooltip when button is hovered by adding the state props.

**Comment by davidzbiral** [comment]
@Ptrhnk I am afraid I do not understand the question, if it is for me. "Tag", this is how you call the entity element or entity tag in suggesters etc., right? But still, I don't understand the question.

**Comment by Ptrhnk** [comment]
Implemented
