### ISSUE TITLE
Incorrect GUI handling of inverse relations in asymmetrical Relations

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1313]
@adammertel, @Ptrhnk: There is a misunderstanding re: reciprocation in _assymmetrical_ Relations in GUI detail (this is just GUI and not data model, at least I hope). Change is needed there.
The problematic Relations are those which are marked as Assymmetrical = Y in [our table](https://docs.google.com/document/d/1cqr-kIF_W6voea7RHjf1vFv-BRKRdcFIiqDLLfjK7BE/edit#bookmark=id.lzu4f21zshfb). For those which are assymetrical = Y, the inverse relation should not be displayed in this section and under this Relation name at all. 
One is Holonymy (treated in #1293 - i.e. solving #1313 will solve also #1293), the other is Superclass: the subclasses _must not_ appear under the label Superclass (see image). 
![obrazek](https://user-images.githubusercontent.com/55400794/197336624-7e664698-26b3-47d6-8dde-f748a06394f1.png)
This, incl. the mixing of superclasses and subclasses under the same section, is incorrect.

This concerns all those marked as Assymmetrical = Y, i.e.:
- Superclass
- SuperordinateLocation
- SubjectSemantics
- Actant1Semantics
- Actant2Semantics
- Classification
- Holonym
- Implication

Instead of displaying them under the incorrect (inverse) name in the same section/table, let's create, after Relations section in Detail, a new section "Used in Relations", and in this section, list uneditably the inverse relation (similar logic to Used in Metaprops).
You will find the heading of the inverse relation in the new col. "inverse relation name" in the [table in our gdoc](https://docs.google.com/document/d/1cqr-kIF_W6voea7RHjf1vFv-BRKRdcFIiqDLLfjK7BE/edit#bookmark=id.lzu4f21zshfb).

As I say, this only concerns the assymmetrical relations. For symmetrical or cloud ones, no problem in the current display. That means: in this new section, only display the assymmetrical ones.

Sorry about spotting this later than I should have (but I this "Used in" section was a part of my original idea, as implicitly noted in #1215). No problem, let's swiftly change this - it is a priority now since the current display is ontologically incorrect and editorially confusing.

**Comment by Ptrhnk** [comment]
- [x] Hide relations of inverted direction
- [ ] Utilize filtering functions for relation rules
- [ ] Implement used in section for inverted relations

**Comment by Ptrhnk** [comment]
Filtering of inversed relations is prepared, UX design solution is needed to finish.

**Comment by Ptrhnk** [comment]
@davidzbiral Seems to be more usable to put inverse relations to the relations section, so you can see the connections at one place. Something like this: (not sure about the section naming)
<img width="578" alt="Screenshot 2022-11-09 at 14 58 08" src="https://user-images.githubusercontent.com/29732281/200864185-606061d6-afa4-4595-be4f-2cb22baa90f5.png">
What do you think?

**Comment by davidzbiral** [comment]
@Ptrhnk : we came to an agreement yesterday with Adam and @pondrejk , so the design is ready - talk to them please.. Closing.

**Comment by Ptrhnk** [comment]
Nice! I would close it with implementing the changes to staging then.. It's linked with the implementation branch already.
