### ISSUE TITLE
Reorganize Detail of As to keep valencies (ontological, grammatical and semantic) together

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1315]
Create a new section in Detail of Actions, just before Relations, which will be organized as follows (the fields kept as they are, nothing added, just reorganized):
**Valency**
Subject entity type
Subject semantics
Subject valency

Actant 1 entity type
Actant 1 semantics
Actant 1 valency

Actant 2 entity type
Actant 2 semantics
Actant 2 valency

I.e., take the three relations from Relations and put them in this new section instead, because this is where they are more expected and useful (they remain Relations in data model terms of course, just the order of their visual display changes).

Probably, divide a little bit visually the threesomes (Subject fields, Actant 1 fields, and Actant 2 fields.)

**Comment by davidzbiral** [comment]
@Ptrhnk @pondrejk Moved to 1.3 because now working on Relation display in Detail => doing it all in one blow.

**Comment by davidzbiral** [comment]
@Ptrhnk @pondrejk How's it going? We would like to have 1.3 officially released shortly.

**Comment by Ptrhnk** [comment]
Thanks for reminding! I'll do it after I implement current relations data model on FE which is ongoing now.

**Comment by Ptrhnk** [comment]
Design idea
![telegram-cloud-photo-size-4-5825668382047976222-x](https://user-images.githubusercontent.com/29732281/207900602-dcdfa715-ad33-4ae7-9c92-ddc1fb022179.jpg)

**Comment by davidzbiral** [comment]
@Ptrhnk : Nice, I endorse this! Just perhaps generally, graphically, I would align (na účaří) the suggesters in Detail with the first entity (here C "geographical localization"). No matter that it sacrifices some space - it makes it clearer that the filled-in Cs belong under the heading (here, semantics). I saw this elsewhere in Detail, too, and would make this a general pattern under Relations: align na účaří the suggester element with the top-most entity.
