### ISSUE TITLE
Self-loops break down the RelationType.SubjectActant1Reciprocal in Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1316]
Some RelationType.SubjectActant1Reciprocal are self-loops, i.e. their source and target is the same A. E.g. in cases such as "meet with": if David met with Adam, then Adam met with David - it should reciprocate the same A.
But now, such a self-loop seems to break down the RelationType.SubjectActant1Reciprocal in Detail: there is no input field displayed if such data is imported, and the data is not displayed and cannot be edited under this Relation. (See image - highlighted in yellow.) 
![obrazek](https://user-images.githubusercontent.com/55400794/197343741-f068eb32-cea6-4d69-a47d-2f5b25641917.png)

**Comment by adammertel** [comment]
related to #1263

**Comment by Ptrhnk** [comment]
This can happen when the object looks like this:
```
  {
    "type": "SAR",
    "entityIds": ["a3", ""],
    "order": 1
  },
```
Which can only come from import-data..
Maybe it would be better to automatically clean this, because the only important information (which is the related entity) is missing and so identical object can be created from suggester.
