### ISSUE TITLE
Repositories of MSS: from "class" metaprop to Classification Relation

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1318]
By error, I forgot to correct the [instruction for the generation of repositories of mss - Locations](https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=0&range=J1). Instead of class metaprop, it should be the RelationType.Classification. Instruction corrected, please implement.
![obrazek](https://user-images.githubusercontent.com/55400794/197347695-6578a7b8-f4c7-477a-ad68-76f258aa805e.png)

Input example: https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=0&range=J145
Output example (now incorrect): https://dissinet.cz/apps/inkvisitor-data-import/#selectedDetail=8b1f57de-6149-4e6b-abc1-b922777ae03e

**Comment by tomaham** [comment]
Should be corrected in Import batch [development] 2022-10-22 18:54:22.598885

**Comment by davidzbiral** [comment]
Cross-checked, done perfectly!
