### ISSUE TITLE
Fix the multiplication of manuscript repositories by their machine generation

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1319]
Please implement a new instruction for generating mss repositories (new condition added) in: https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=0&range=J1

Problematic outcome (duplicated L entities):
![obrazek](https://user-images.githubusercontent.com/55400794/197348615-39c4185d-e413-4afb-98b1-b0aa55e716ed.png)

Desired outcome: only create the repository once - if the script has already generated one with the same label, use that one instead of creating a new one.

**Comment by davidzbiral** [comment]
Another change in the same instruction: #1318.

**Comment by tomaham** [comment]
Corrected in Import batch [development] 2022-10-22 18:54:22.598885

**Comment by davidzbiral** [comment]
Cross-checked, done well!
