### ISSUE TITLE
Never import "NA" and "NS" values; treat them as empty cells (seen in generated "NA" R entities)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1321]
Example of input: https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=2056508047&range=CS7
Example of problematic output: T "Sentences of William Arnold and Stephen of Saint-Thibéry":
![obrazek](https://user-images.githubusercontent.com/55400794/197350372-196e4369-f594-40a0-be28-60ea941c959e.png)

Desired output: do nothing, do not generate any R with label "NA" here.

**Comment by tomaham** [comment]
Done.
