### ISSUE TITLE
Multiple Relations of the same kind should have an order

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1322]
RelationTypes allowing multiples should have editable order. For instance, something can have two Classifications, and the editor wants to present them not in alphabetical order but in an editable semantic order (e.g., putting first the prevailing, more important class). I.e., in those cases, use the same drag&drop as in metaprops.

Upon parsing, the order in the cell should be taken as the order for that Relation.

**Comment by tomaham** [comment]
@davidzbiral  The parsing is actually done in the order of the items in the cell.  Reordering is probably part of the GUI operations?

@adammertel Can you comment on that?

**Comment by adammertel** [comment]
I am sorry @davidzbiral but the data model is not ready for this at the moment. 

But it is possible to extend the data model to support this - should we implement this?

**Comment by davidzbiral** [comment]
@adammertel: Yes, please, implement this. As with metaprops, the order of Relations follows some logical order, so it needs to be preserved.

**Comment by adammertel** [comment]
Okey, here we go
 [ ] Integrate order attribute into the relations model #1354 
 [ ] Integrate Relations order attribute on BE #1355 
 [ ] Sort relationships on FE based on the order parameter #1356 
 [ ] Integrate the order parameter into parsing #1357 
 [ ] Design Relations reordering functionality into Detail #1358 
 [ ] Implement Relations reordering functionality into Detail #1359

**Comment by tomaham** [comment]
@davidzbiral 

Should be solved, visible in 
`Import batc`h [development] 2022-11-28

**Comment by davidzbiral** [comment]
@adammertel: if implemented, please close.
