### ISSUE TITLE
Document genre in incrimination datasets: from metaprop to RelationType.Classification

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1329]
We need to replace the "genre" metaprop, with RelationType.Classification. I.e., what was metaprop "T - has - C genre - C sentence" will he "T - RelationType.Classification - C sentence".
Therefore:
1. I updated the "special" instruction in the relevant col. of [Gug Incriminations](https://docs.google.com/spreadsheets/d/1mLevawnoZVLQv6qINaSfiyi1NNlfJzTZevinRSSQVPo/edit#gid=0&range=N1). (This will be the same in the other Incrimination datasets.)
2. I introduced an instruction [hooked-relation](https://docs.google.com/spreadsheets/d/1mLevawnoZVLQv6qINaSfiyi1NNlfJzTZevinRSSQVPo/edit#gid=0&range=Q2:Q4), which is now needed.

@tomaham: Explained clearly or not?

**Comment by tomaham** [comment]
Corrected in Import batch [development] 2022-10-28 18:08:53.290879
