### ISSUE TITLE
Find new library for tooltip handling

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1331]
Create small project for testing necessary functionalities.

**Comment by Ptrhnk** [comment]
https://popper.js.org/react-popper/v2/

**Comment by Ptrhnk** [comment]
Testing at:
https://codesandbox.io/s/reverent-forest-08uf54?file=/src/App.js

**Comment by adammertel** [comment]
How long would you estimate for a complete rewrite of the code to the popper library?

**Comment by Ptrhnk** [comment]
Split into components: https://codesandbox.io/s/ancient-worker-3nx4wg?file=/src/components/Tag.js

**Comment by Ptrhnk** [comment]
> How long would you estimate for a complete rewrite of the code to the popper library?

@adammertel 16 hours with testing?

**Comment by adammertel** [comment]
> > How long would you estimate for a complete rewrite of the code to the popper library?
> 
> @adammertel 16 hours with testing?

Ok, in that case, I would go for it. We are still waiting for the implementation of the DetailResponse model to work on the detail relations :/ So this is maybe a good time for such tasks.

**Comment by Ptrhnk** [comment]
Closing as this issue is for research. Implementing in #1397
