### ISSUE TITLE
Superclass and Superordinate Location in tooltip: only display the relevant superclass/superordinate branch, not the whole tree

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1336]
In Superclass and Superordinate Location display in tooltip, only display the relevant superclass/superordinate branch, not the whole tree. (Same in Detail.)
I.e., in the image example, only L Mediolanum.
![obrazek](https://user-images.githubusercontent.com/55400794/198626598-0797bb47-5e06-43b7-abc4-aa110f775ff1.png)

**Comment by davidzbiral** [comment]
But @Ptrhnk : this will be very useful as one of the views. Issuized in: #1341.

**Comment by adammertel** [comment]
@davidzbiral It's not clear what you mean by "relevant" relation here. 
@tomaham I am not sure, but this looks like a mistake in data parsing, where the position of entities is inversed. The table with the SCL/SOL should go up to the root, not the other way around. This was tested in the first testing data, and it looks reasonable 
![image](https://user-images.githubusercontent.com/12932677/198900749-e0f457bd-7316-441c-96c7-5298b84dc6b6.png)

But I am creating two new issues, one for the maximal number of relations displayed in the tooltip #1351
And one for the not repeating the same entity tree #1353 in the tooltip

**Comment by tomaham** [comment]
The parsing-import part of the problem should be fixed in the Import batch [development] 2022-10-31 23:17:42.155684 and higher.

**Comment by davidzbiral** [comment]
I confirm that when created directly from InkVisitor, the display seems OK. Closing.
![obrazek](https://user-images.githubusercontent.com/55400794/199503736-f2cf2e4b-d941-4585-a487-9e52aaef6117.png)
