### ISSUE TITLE
Two changes of automated generation of modern Locations from Location sheets

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1337]
@tomaham congrats on understanding well my previous - very unclear - [instruction on modern_name in Guglielmites Locations](https://docs.google.com/spreadsheets/d/1jImuYCTu-QrZc7oCT1Vz01SLu5sxYRo4xzJzlF2J8Bs/edit#gid=0&range=modern_name).

I now updated the instruction - two changes needed:

1. The "certainty" of this RelationType.Identification should be 1 - "certain".
[Input example](https://docs.google.com/spreadsheets/d/1jImuYCTu-QrZc7oCT1Vz01SLu5sxYRo4xzJzlF2J8Bs/edit#gid=0&range=M40).
[Output example](https://dissinet.cz/apps/inkvisitor-data-import/#detail=6d1b6531-8dcd-4005-9424-168001448812).
![obrazek](https://user-images.githubusercontent.com/55400794/198635218-9a59fc54-a4bf-4b53-8811-171967090ea1.png)

2. The class of the newly generated entity should be done by RelationType.Classification, not by a metaprop - sorry that I missed it, I have this error at several places of my instructions (I failed to update it to the new system)! Now, the instruction is updated to the new version in [instruction row 1](https://docs.google.com/spreadsheets/d/1jImuYCTu-QrZc7oCT1Vz01SLu5sxYRo4xzJzlF2J8Bs/edit#gid=0&range=M1): "Attach RelationType.Classification to this modern location from col. "modern_name_class_id" (hooked-relation)."

BTW everywhere where there is the deprecated "C0565 class" is used (in either metaprop or [later, when we are parsing coding sheets] in-statement prop), the RelationType.Classification should be used instead (if there is a way to report error in such cases, very good, since checkers might pass it unnoticed).

**Comment by tomaham** [comment]
Corrected in Import batch [development] 2022-10-28 18:08:53.290879

**Comment by davidzbiral** [comment]
Checked.
