### ISSUE TITLE
Represented event: switch it the other way around

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1338]
[Instruction](https://docs.google.com/spreadsheets/d/1mLevawnoZVLQv6qINaSfiyi1NNlfJzTZevinRSSQVPo/edit#gid=0&range=N1): "(3) Relate the lowest-level entity to the Event described by the row by the following Metaproperty: T107-1-01 - [has] - C2286 represented event - E0001".
But the script generated the relation the other way around, which does not fit the metaproptype semantics.
It should be as described, i.e. from T to E, not from E to T.

Example output (incorrect now): [Dictum suprascripti Andree (f5e17ef8-ce42-43b6-99ba-e492a5d171be)](https://dissinet.cz/apps/inkvisitor-data-import/#detail=f5e17ef8-ce42-43b6-99ba-e492a5d171be%2C5c864758-86ed-417d-9770-14bc64628f77&selectedDetail=f5e17ef8-ce42-43b6-99ba-e492a5d171be).

![obrazek](https://user-images.githubusercontent.com/55400794/198674448-67250478-7414-46d6-b806-3a591300786c.png)

**Comment by tomaham** [comment]
Corrected in Import batch [development] 2022-10-28 18:08:53.290879.
