### ISSUE TITLE
Order territories alphabetically by legacy_id

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1339]
Now, upon parsing, the machine generated middle-element territories, e.g. Territory labelled "4" generated from IDs such as "T107-4-09" by [this instruction](https://docs.google.com/spreadsheets/d/1mLevawnoZVLQv6qINaSfiyi1NNlfJzTZevinRSSQVPo/edit#gid=0&range=N1), have a strange order. 
![obrazek](https://user-images.githubusercontent.com/55400794/198676397-295def1c-83eb-4c79-b335-d383318c2745.png)
They should be ordered alphabetically.

But solve this as a part of a broader and major issue: order all territories of the same level alphabetically _by legacy_id_ (not by label). This is crucial, since the legacy_id alphabetical order holds, in gsheets, the information on the order of documents in the source, while now, the order is lost!!! See image - the order is random (or what), definitely not how the documents follow one another.
![obrazek](https://user-images.githubusercontent.com/55400794/198686678-49fe1073-ce72-4ff7-b475-222db8292839.png)

**Comment by tomaham** [comment]
@adammertel I would use your attention to this.  How is the order of the territories implemented?  I looked in the entities.json I push in into db through your import.ts script and the territories with "weird" order I check, actually have proper flow in the file.  (see picture
![image](https://user-images.githubusercontent.com/3739529/198882363-2d96a278-7ab8-4793-936b-4dc64c4cb22a.png) )
  

Also, it is possible to rearrange the order of territories through GUI, but I don't know where is this stored - I suspected an attribute order in the data>parent, but this is still 0 for all the rearranged territories?

I am confused.

**Comment by tomaham** [comment]
@adammertel  More context. 

This query `r.db("inkvisitor").table("entities").filter(r.row('data')('parent').eq(false).not()).filter(r.row('data')('parent')('territoryId').eq('17febfee-a942-45d0-8ac5-9828d956940c'))` returns the elements of T107 (id="17febfee-a942-45d0-8ac5-9828d956940c") in the same order as it is in the GUI.

From where comes this "natural" order which does not respect the sequence from the original entities.json? Could it actually be **order** by the uuid string? 

`- 2, 061f068c-a88c-4f7f-a5b1-048f921821d2  
- 1, 2568f0c3-d0db-4d01-a20d-fc3b45e915c2  
- 4, 5d6f1d27-2dc1-4dee-92a9-6ea7231ed637  
- 3, b4b01758-1351-4f4e-b322-0e6889e8e78a  `

**Comment by tomaham** [comment]
This leads me to report a possible bug, it seems that the manual reordering of the territories is not saved to the DB. It is visually present till you reload the browser.

I.e. this 
![image](https://user-images.githubusercontent.com/3739529/198884407-0a4416e0-d9a8-4af1-b8bb-5b98047bbf88.png)
is gone after reload.

**Comment by tomaham** [comment]
In the 

Import batch [development] 2022-10-30 08:43:10.309179

there should be the right order of the territories (achieved through attribute 'order' on the parent territory object).

**Comment by adammertel** [comment]
@tomaham This is not working in FE because all the child T have order value 0.

**Comment by tomaham** [comment]
Well, it depends on what you mean by "this". If it is "saving the manual rearrangement" if the attribute order is 0, then yes, I understand.  Otherwise, the issue (order of the inner territories) under this issue should actually be already solved.
