### ISSUE TITLE
Allow reordering of Detail tabs by drag & drop

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1340]
Allow reordering of Detail tabs by drag & drop - as e.g. in a browser you can drag & drop a tab and thus change the order of tabs in which they are displayed from left to right. As in browsers. Minor thing, but nice to have.

**Comment by Ptrhnk** [comment]
https://codesandbox.io/p/sandbox/github/react-dnd/react-dnd/tree/gh-pages/examples_ts/02-drag-around/custom-drag-layer?file=%2Fsrc%2FCustomDragLayer.tsx%3A13%2C11

**Comment by Ptrhnk** [comment]
@davidzbiral FYI
https://github.com/DISSINET/InkVisitor/assets/29732281/fe0cc64e-a6a7-4189-841e-a8e8f90e4a58

**Comment by davidzbiral** [comment]
@Ptrhnk Looks very nice!
