### ISSUE TITLE
Avoid the creation of duplicates in the editions columns (R entities)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1343]
By error, I forgot to mention in [this instruction](https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=2056508047&range=CS1)  to avoid creating a new R if it was already created (can be recognized by label, but also URL must be checked, because some have the same label but different URL, and these should be different Rs). Instruction updated now.
Attention - the condition spans throughout the edition cols., i.e. not just the col. edition_1, but also edition_2 etc. If through any of these edition cols the R entity with the same label and URL (if available) was created, don't create a new one but use the existing one.

[Example input](https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=2056508047&range=CS50:CS51) - "Utz Tremp, 2000" should be just one R, not two.
![obrazek](https://user-images.githubusercontent.com/55400794/198832932-91199877-8fbb-4033-a943-58d98f76a008.png)

[Another example input](https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=2056508047&range=CS30:CS31) (btw here, it is the same label but different link => different R).

Sorry about those mistakes.

**Comment by tomaham** [comment]
Should be corrected in Import batch [development] 2022-10-29 19:26:27.397363

**Comment by davidzbiral** [comment]
@tomaham: seems not corrected (same input example as above).
![obrazek](https://user-images.githubusercontent.com/55400794/199887700-5992406c-6504-4611-a357-7e713f4f8d77.png)

There were two comparisons: (1) label and (2) hyperlink. Of course, some are without hyperlink - there, only label should be compared, and if it exists, do not create a new one (example of Utz Tremp, 2000).

**Comment by tomaham** [comment]
Fixed in Import batch [development] 2022-11-07 10:23:01.399303  .

**Comment by davidzbiral** [comment]
Seems ok, thanks!

**Comment by davidzbiral** [comment]
This solved issue observed again in Import batch [development] 2023-01-13 19:35:45.939035 - reopening.
![obrazek](https://user-images.githubusercontent.com/55400794/213869916-999686ae-6d5d-4baa-8cf0-ba62427b2662.png)

**Comment by davidzbiral** [comment]
BTW "Utz-Tremp, 2000" correctly created only once - so perhaps the problem is the non-implementation of this part "Attention - the condition spans throughout the edition cols."?

**Comment by tomaham** [comment]
All edition cols are solved by the same function, it will lie elsewhere, I am investigating.

**Comment by tomaham** [comment]
Found it, it will be fixed in the new reparsed import.
