### ISSUE TITLE
Resources: not Superclass but Classification

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1344]
Again an error of mine. Resources should be classified not by Superclass but by Classification.
[Input example](https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=583750775&range=N10).

**Comment by tomaham** [comment]
Should be corrected in Import batch [development] 2022-10-29 19:26:27.397363

**Comment by davidzbiral** [comment]
Checked as corrected. Closing.
