### ISSUE TITLE
Data validation: find entities using discouraged Concepts in any of its Relations or metaprops

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1346]
A DDB1 query of the working data (before D Day for global entities) can provide a great way to validate them, and possibly discover and correct recurrent errors (e.g. outdated parsing instructions) before approval.
Please write a query which will find any entity using a `discouraged` Concept in (A) metaprop, i.e. as either (A1) proptype or (A2) propvalue, or (B) a Relation as its target.
Print this e.g. in a simple table with 2 columns (first proposal):
Entity label under which the error occurs | Label of the discouraged Concept used there

The historian editors will then check this and decide whether to make changes.

**Comment by tomaham** [comment]
I could do this, but isn't this a little improper use of work time now? The status of concepts is in DDB1, so you can do a DDB1 query to get such information, why to log such information during parsing?

**Comment by davidzbiral** [comment]
OK, changed.

**Comment by tomaham** [comment]
@davidzbiral Do you know at least 1 example of such result?

**Comment by tomaham** [comment]
Probably this. The scope is larger, it tries to find discouraged concepts in all input datasets.

https://docs.google.com/spreadsheets/d/10x8TV2OmkcGt6zHw-3B-I3BhonETa0iQV424vCB9qSQ/edit#gid=1263074641

**Comment by davidzbiral** [comment]
Very useful, I will have a look.
