### ISSUE TITLE
Reorder of the territories through GUI is not saved

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#1349]
A possible bug, it seems that the manual reordering of the territories is not saved to the DB. It is visually present till you reload the browser.

_Originally posted by @tomaham in https://github.com/DISSINET/InkVisitor/issues/1339#issuecomment-1296274764_

**Comment by adammertel** [comment]
@tomaham when I create a set of new territories and try to reorder them manually in GUI, everything works fine. But maybe on a  specific situation, it stops working. 
@jancimertel could you please test a situation when you call a reorder call on a bunch of sub territories with the same order (lets say 0)?

**Comment by adammertel** [comment]
The problem occurs with the newly parsed data 
with this error emitted 

![image](https://user-images.githubusercontent.com/12932677/198891420-6bbc747b-6214-4b2f-971a-0580afb8d736.png)

http://localhost:8000/apps/inkvisitor/#territory=175f0f20-6e81-4378-8a85-51d72ae69bb2

**Comment by adammertel** [comment]
Ok, I see the problem. All the territory children have an "order" value of 0. 
@tomaham, please fill in the order value to make it work.
@jancimertel I created a new issue for creating a BE workaround to work with this kind of data  #1350

**Comment by tomaham** [comment]
I see. I got the wrong impression about the attribute order because I checked whether it is filled by drag-drop rearranging on the parsed data, where it did not work... :) Quite a coincidence.  I will fill the order everywhere.

**Comment by davidzbiral** [comment]
OK, then this seems solved, @adammertel?
