### ISSUE TITLE
Do not duplicate the same C tree in the tooltip 

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1353]
This is probably mainly for A:
If, for example, the same C appears in AEE and SCL relationships, draw only one full tree. In the second example, use symbols such as "-||-" for the repeated levels to signalize the repetition. 

Probably still to be discussed (how much does it make sense visually, and how often this may happen?)
@davidzbiral 
@pondrejk

**Comment by davidzbiral** [comment]
@adammertel: if anything is unclear, I am here to help.

**Comment by adammertel** [comment]
Ok, this problem probably happened because of problems in data parsing and tooltip displaying. 
CLosing this for now
