### ISSUE TITLE
Integrate order attribute into the relations model

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1354]
It does not make sense in some relation types, e.g., SYN

Let's discuss this inside document "Reserved core semantic and ontological relations  - proposal"

**Comment by adammertel** [comment]
@davidzbiral I added the sorting column to the table "Reserved core semantic and ontological relations". Please look at it if you agree.

**Comment by davidzbiral** [comment]
@adammertel: checked and approved, see there. Let us sort identification by certainty, it makes sense. 

Just one question: why Related should not be sorted? Can it be sorted?

**Comment by adammertel** [comment]
@davidzbiral 
Related: it's a symmetrical relation, therefore A-B is stored only once.
Let's say we have these relations with the order in brackets:
A-B (1), A-C(2), A-D(3)
C-B(1), C-D (2)

And now, you want to display entity B. It has two relations, A-B (1) and C-B (1) - which one should be first? And if you create a new relation B-F and want to relocate it between A-B and C-B, you will be changing A-B and C-B order - which may break the consistency of relations under A and C. 
I am not saying it is unsolvable, but it is at least not a straightforward problem. 

So it would be much easier now if you do not need to order "Related" relations :)

**Comment by adammertel** [comment]
A solution would be to maintain two order values for each Related relation.

**Comment by davidzbiral** [comment]
@adammertel: I am happy to drop the order in Related, since it is in itself semantically more loose, and the sequence of related entities is thus not so important. I expect that users will rarely use it to store more than one relation.
