### ISSUE TITLE
Design Relations reordering functionality into Detail 

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1358]
This is only for Detail and for the normal + editable inversed Relations (if there are any)

**Comment by Ptrhnk** [comment]
Can be solved similar as meta props.

<img width="120" alt="Screenshot 2022-11-03 at 10 05 49" src="https://user-images.githubusercontent.com/29732281/199693832-c1f28057-5e04-4c30-a0f0-a20ab3676bcf.png">
