### ISSUE TITLE
EntityTooltip - filter current entity from tooltip data (clouds)?

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1361]

**Comment by Ptrhnk** [comment]
<img width="123" alt="Screenshot 2022-10-31 at 18 06 58" src="https://user-images.githubusercontent.com/29732281/199078576-d6c692f1-30d5-4af2-9e48-5ff3f834d4fb.png">

**Comment by adammertel** [comment]
Yes, this is a good point. Do you want to remove it from the Response model or a GUI solution is enough?
