### ISSUE TITLE
Consider extending of relation props (different then certainty)

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1374]
Not the relations in detail (which are automatically generated on FE by data model) are only prepared for certainty. If another props are needed, FE components needs further development.

**Comment by davidzbiral** [comment]
@Ptrhnk : I don't think that any other Relation needs any attribute apart from the original list, i.e. among the metalevel Relations (those displayed in Detail, attached "directly" to the entity), only Identification needs certainty. And some need order (sequence), as per #1322.
In-statement Classification and in-statement Identification have richer attributes, but you were not perhaps commenting on these, no?

**Comment by Ptrhnk** [comment]
Ok, closing.
