### ISSUE TITLE
Add original gsheet as Reference to entities parsed from it

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1377]
For some operations, e.g. "I am interested only in Persons from the Fournier register", this reference to R will be the only way to filter persons down to only Fournier persons. Now, there is no such identification, and we need it.
(In full CASTEMO approach, it would be stored bottom-up, i.e. the condition would be "if the Person appears in any statement under T Fournier register, it is a Fournier person", but CASTEMO-coding will not be done for all Ts, let alone soon.)

@tomaham, please match the parsed gsheet (Resource) with the [table of Resources](https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=583750775) probably by spredsheet id (e.g. 1UtgKvjr91egdgOQMP8WxsRxgGDT9FC92qBG3sKBiYvk), and under each entity parsed from that Resource (e.g. Guglielmites Persons), store that Resource as Reference (e.g., for Guglielmites Persons, it is legacy_id "R0006"). 
- The reference_part field will remain empty.
- In some entities, e.g. incrimination Events, there is a Reference already - to the OCR that is the original resource. Add this new Reference described in this issue as a new one - References allow multiples.

I hope it makes sense and it is a good move?

**Comment by tomaham** [comment]
I am not sure if I follow, there is legacyId...

All you want is an explicit connection through a reference attribute of entity in addition to legacyId ?  (what do you mean by matching by the spreadsheet id, the resource of the specific dataset is always clear beforehand, or not? I.e. all guglielmites persons come from one clear resource?)

Are you sure legacyId is not enough?  (You are able to make a query addressing all persons which contain "_R007" in their legacyId.    BTW operation like this can be created in the database itself like an update. I.e. you can modify the data with query:  take all entities with legacyId "*_R007" and hook there a new reference object which points to specific Resource entity. The fact you can do such a thing signifies that the information is already in the data.)

**Comment by davidzbiral** [comment]
@tomaham : You are damn right - as long as the R is used as suffix, it is superfluous. Closing.
