### ISSUE TITLE
Add all common languages to the list

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1382]
For project neutrality, we need a more stable approach to languages. Available language lists will not suffice, because InkVisitor users will be dealing with language variants/phases (older phases of a language; dialects), but they are a needed addition. However, it is of course not practical to have a long dropdown of 300+ languages, so the language selector must become actually a suggester, as is usual in selection of languages in some commercial web applications.

Rationale: our users will want this, and it is very unpractical to add each single language by individual request.

**Comment by adammertel** [comment]
Possible solution:

 - add all languages to the dictionary
 - each user can customize the list of the languages
 - add a pre-selected list of languages for the new users

**Comment by davidzbiral** [comment]
Replaced by better specified duplicate, scheduled earlier: #2014. Closing.
