### ISSUE TITLE
In-statement prop elvl: if the involvement of proptype or propvalue is elvl3, the overall is elvl2

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1388]
In our understanding, if an in-statement prop involves any "actant" (i.e. proptype or propvalue) at elvl2, the prop itself cannot be at elvl1. Thus, help data validity by changing the elvl of the whole prop to elvl2 if proptype and/or propvalue is elvl3, and signall the change to the user visibly with the option of reverting it by a single click (as Google does it, e.g.: "File deleted. Undo.")

This does not concern parsed gsheets coding sheets data, because this legacy data does not contain separate actant involvement elvl.

**Comment by davidzbiral** [comment]
Robert's perspective:

> I might offer the following alternative proposal around overall prop elvls, which contains some automatable rules/defaults, since I do absolutely agree that rules/defaults to help coders around complex issues like this would be very helpful, and that we should reduce the headscratching for tired coders!For me, I would say the overall elvl of a property is an editorial decision around the semantic you are trying to model in the text. Thus:overall prop at elvl1: I am trying to model a textual semantic as precisely as possible thru this property, even if using a elvl3 analytical prop type.
> 
>     Associated validation rule: a prop value with elvl1 is thus necessary for an overall prop at elvl1
> 
> overall prop at elvl2: (rarer use) I am trying to model a potential, even probably semantic reading of a bit of text, but one which is less certainly indicated
> 
>     Associated validation rule: a prop value with elvl1 is thus still necessary for an overall prop at elvl2 (since the prop value relates to the text that is being interpreted)
> 
> overall prop at elvl3: I am making a clear inference from the text which I can't directly connect to any textual element
> 
>     Associated validation rule: with elvl3 properties, no element can be elvl1

**Comment by rljshaw** [comment]
Some further thoughts modifying my perspective/alternative proposal (from the same Slack thread):

> I guess there are a few further complexities here beyond what I suggest that go back to our last (now probably outmoded) discussions on elvl.

> E.g. possibility of elvl2 property values, where for instance there is some scribal issue (e.g. badly rendered name), and you have placed the prop value at elvl2 since there is some interpretation required for what the entity is.
> `Here, I might make the overall prop elvl2 as well, given that the interpretation of the prop value which is central to the semantic, and modify the second rule, to cover this case: i.e. a prop value with elvl 1 or 2 is necessary for an elvl2 prop.`

> With my proposal on elvl3 properties there is also the consideration of whether it is more than just prop value and prop type not being elvl1
> `It might even be that both elements have to be elvl3. For if there is some textual or interpretative element within, arguably the overall prop is not totally a "beyond text" inferrence`

**Comment by davidzbiral** [comment]
@adammertel : I asked Katalin to check whether my statement that this is invalid is true at all - so this is pending until she answers, possibly this will not be implemented at all, I'll keep you updated.

**Comment by davidzbiral** [comment]
Explored by Katalin and Robert. There are cases where the combination described above is not invalid, thus do not implement. Closing.
