### ISSUE TITLE
Explore InkVisitor as db manager of a "relational" database (even for people not interested in CASTEMO)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1390]
While they are not the main target audience of InkVisitor, users striving for a nice environment to create relations between entities of different kinds could still benefit from some great features of InkVisitor, especially:
- Quick creation of new entities (selection/creation as part of the same element).
- Explicit guidance, in Detail, to put them in semantic and ontological relations (e.g. synonymy for C and A, classification towards C for PLOGESTRB).
- Openness for the user's specific data model (as long as the basic logic is kept: entities of given kinds, related through Metaprops and Relations).
- Data entry modules, esp. the geocoding module.
- Views.

**Comment by tomaham** [comment]
This vision would need more elaboration, probably a face-to-face.  :) At this moment it is not easy for me to hook into it.   (Without having a clear idea of the full use case with "data out" scenarios, it is hard to imagine this).

**Comment by davidzbiral** [comment]
Sure. Sorry, this is meant somewhere towards version 1.7 to 3.0, long-term development :-) But there is already one real-life example: Lidia's dataset on early heresy, done completely this way, with no statements done or intended, while DISSINET data model compliant.

**Comment by davidzbiral** [comment]
At this stage:
- Multiples - i.e. when in a table you need to fill in two values.
- Our spreadsheets cease to work practically - too long.
- Search.
Not so much, you might say, even if for me it would mean a lot in 2014 when I was exploring relational database managers.

In the future, more:
- Exploratory data analysis with views.
- Smart search with conditions (this can be done in spreadsheets, just not user-friendly for a regular humanist).
- The geocoding module.

**Comment by tomaham** [comment]
I am afraid that you may overlook that inkVisitor is and probably will always be a significant investment on the users' side concerning the installation. 

There are much less costly solutions for governing a small relational database on the market (e.g. "advanced spreadsheets" possible in Notion or Google Tables [still USA only]) with considerably more money and community behind them.  

There are sophisticated cloud analytical and visualisation environments which can hook to various data sources.   

I presume that unless people use CASTEMO, they will most probably have better options.

If we should dream about the inkVisitor future, I would suggest not trying to make it universal (a.k.a. database environment for input, government, output, analysis, and exploration) but tailoring it more to chosen specialisations.

**Comment by davidzbiral** [comment]
The crucial functions which I had _actually_ in mind are now underway as part of the full-text management strand, where it is possible to add tags marking beginning and end of entities - typically Territories and Statements, but also - why not, for people who want to annotate rather than do CASTEMOing - Locations and Persons. So I think we can close this now.
