### ISSUE TITLE
Password reset link does not work when logged in under a different account

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1420]
If I am logged in under one account, the password reset link does not open the password reset page but the application where I am logged in.

**Comment by jancimertel** [comment]
connected issue https://github.com/DISSINET/InkVisitor/issues/1476

**Comment by jancimertel** [comment]
Password reset page merged with activate page.
Logged user is now automatically logouted, email with password should be sent after successful activation.
Waiting for merge with https://github.com/DISSINET/InkVisitor/tree/refactor-password-reset
