### ISSUE TITLE
Design a visual method for entities in Props with inferential elvl 

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1437]
To "dehighlight" them

**Comment by adammertel** [comment]
@davidzbiral could you please approve this issue? And maybe add a short reasoning here?

**Comment by davidzbiral** [comment]
This is part of a broad family of issues introducing validation features to InkV to decrease error rate and make the usage simpler (assistance and validation are two sides of the same coin).

The idea is that actant involvement elvl could be signalled visually. I will write more.

**Comment by davidzbiral** [comment]
Not sure what we ment, probably implemented by actant involvement elvl icons.
