### ISSUE TITLE
A button for clearing all tabs

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1449]
![image](https://user-images.githubusercontent.com/12932677/210178179-93cfc339-6cfd-4138-b627-3879964cbeff.png)

**Comment by Ptrhnk** [comment]
@davidzbiral @adammertel That's what the [x] button do now. Do you want to change icon or maybe add tooltip on the button?

**Comment by adammertel** [comment]
@Ptrhnk good point. I was not aware of this functionality. 
I think changing the icon to "VscCloseAll" will do the job.
