### ISSUE TITLE
Reciprocation in Identification not working

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1478]
I create L Agnanum. I make Identification - certain with L Aglanum. Under Aglanum, no reciprocation back to Agnanum appears. The link should be symmetrical and editable (removable) from both sides, and the certainty is the same both ways (it is actually the same relation).

I think we have seen with Adam that also elsewhere, reciprocations, already checked OK once, ceased to work in the last couple of months also for other relations.

Top priority - this prevents us from checking the correct import of gsheets data for Hackathon 3 (checking due in mid-January).

**Comment by jancimertel** [comment]
can you please confirm if Subject/Actant1 Reciprocal should also be symmetrical?

**Comment by davidzbiral** [comment]
Yes, SubjectActant1Reciprocal is symmetrical. E.g.: if "tell sb st" has the SubjectActant1Reciprocal "hear from sb st", then "hear from sb st" has the reciprocal "tell sb st".

**Comment by jancimertel** [comment]
fixed in c829d714129e9bab2f8053964420a6c734cd81e1
