### ISSUE TITLE
Extend Statement and Statement response model to support order

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1480]
`IStatementAction`, `IStatementActant`, and `IProp` will get a new `statementOrder` attribute

draft of the response model
```
interface StuffAction {
  entityId: string;
}

interface StuffActant {
  entityId: string;
}

interface StuffProp {
  propValueId: string;
  propTypeId: string;
  originId: string;
}

type StuffT = StuffActant | StuffProp | StuffAction;

type Stuff<T extends StuffT> = T & {
  linkId: string;
};

export class ResponseStatement extends Statement implements IResponseStatement {
  entities: { [key: string]: IEntity };
  statementOrders: Stuff<StuffT>[];
  ...
```

**Comment by adammertel** [comment]
@davidzbiral do we also want to sort in-statement **classifications** and **identifications** this way?

**Comment by davidzbiral** [comment]
@adammertel : yes, absolutely. In-statement Relations are indeed another syntactic chunk, order matters.

**Comment by jancimertel** [comment]
in branch https://github.com/DISSINET/InkVisitor/tree/order-in-statement-objects
