### ISSUE TITLE
linked relation hidden if panel width is too small

### ISSUE THREAD

**Issue by jancimertel** [DISSINET/InkVisitor#1482]
Not sure if this should be considered, but if the panel is too narrow, it will cause this:

![image](https://user-images.githubusercontent.com/10438157/211158848-30b6600e-bf5b-458d-883c-8b224d3ab0e9.png)

Feel free to close if not important.

**Comment by Ptrhnk** [comment]
Ok, I'll check that.

**Comment by Ptrhnk** [comment]
- [x] relations in detail
- [ ] actants in editor
