### ISSUE TITLE
Search results hidden because not scrollable

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1511]
Even in the case of 1 result, but even more with more results: I cannot see the results or click on them on smaller 13'' screens - the box is scrollable but without results. Make it scrollable including the results.

![obrazek](https://user-images.githubusercontent.com/55400794/213379244-2cb54989-878a-4b15-8b00-b3dc8f7a1364.png)

**Comment by adammertel** [comment]
This is a special scenario when the X-axis scrollbar hides a few pixels at the bottom of the box.
I hoped it would be saved by #1502, but the problem is slightly different. 
I will add a bottom margin to the box to make sure everything is visible

**Comment by adammertel** [comment]
The proposed solution creates another (mostly visual) problem, but this can be fixed later
![image](https://user-images.githubusercontent.com/12932677/213459540-6be691b4-3409-4e85-aef1-990cbbf70e8e.png)

**Comment by davidzbiral** [comment]
@adammertel : Why not make one single scroll for the whole box? Why create one for the form and one for results?

**Comment by adammertel** [comment]
@davidzbiral, you probably do not want to lose the idea of what you have been searching for while browsing through the results.

**Comment by davidzbiral** [comment]
@adammertel: OK, you are probably right. Already I think what you did (recently) is important - the eye-icon button to hide Templates and Bookmarks makes my life easier. We could further finetune by actually hiding the further filtering (by entity type etc.), because most people will most of the time use just the one input field and that's it - so it could unfold only upon clicking. But Search will be refactored anyway quite a bit in 1.4, so let us left this closed now since these features are sufficient now, and let us give a thorough thought to search for 1.4.
