### ISSUE TITLE
NULL in actant entity type valency has meaning!

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1526]
NULL in entity type valency seems ignored in data parsing, and probably it even does not have any counterpart in the data model. E.g., "P | G | NULL" is parsed as {Person,Group}. However, this NULL is absolutely crucial for future validation, because it says that empty value in that actant slot is allowed. I.e., the entity type valency "P | G" always requires something, and it will be a Person or a Group. While "P | G | NULL" allows empty value in the actant slot, or a Person, or a Group. This is probably not even implemented in the data model, and this is probably why it is being ignored in parsing. 

We must have missed this somehow. We need this - it will be one important validation feature to check whether required actant slots are not empty, and whether slots required empty (i.e. those which have "NULL" only) are not filled in.

When solved, we will need to incorporate it from Action list into DDB1.

**Comment by tomaham** [comment]
Hm. It seems it is not possible to make this "NULL"  value through GUI and even looking the code, it does seem we are note prepared for 'NULL' value there.  Well, this needs some low level work.

I would vote to actually call it "EMPTY" and not NULL.  (no need to change in google sheets, reparsing would change NULL to EMPTY, but the datamodel and inkvisitor need to be prepared for that)

**Comment by davidzbiral** [comment]
Yes, we need Adam. Yes, let us name it "empty" (lowercase), I was thinking the same way. So now, waiting for @adammertel to change the dictionary, then @tomaham will parse the "NULL" in entity type valency as "empty".

**Comment by tomaham** [comment]
I just checked things under the hood and "NULL" value is in the data (you can see it if you look into json), it is just not displayed in GUI. So no crisis, it seems it is only GUI problem.

**Comment by adammertel** [comment]
An `empty` option "listening to" `empty` value was added to the options. Should be working now...  
![image](https://user-images.githubusercontent.com/12932677/213924049-828b876c-93a2-43c1-83d8-e780c8401648.png)
