### ISSUE TITLE
Display In-Statement properties/classifications/identifications in entity Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1528]
In-statement properties under entity Detail only show the uses of that entity as proptype or propvalue. We also need to show those where the entity is the source node. E.g., if we attach somewhere the in-statement prop P Alberic - has - C order - C Dominican order, we need to see this in-statement prop under the entity Alberic. Very important even for our Hackathon 3 coding.

My view is that we should even sort the uses: first list the uses where the entity is the source node, then when it is proptype, and then when it is propvalue. To be considered whether to even create subtitles for those 3 kinds of uses.

**Comment by adammertel** [comment]
If I understand correctly, `P:Alberic` is, in your example, an actant, and therefore, you can find the link under Used In - Statements section
![image](https://user-images.githubusercontent.com/12932677/213920901-f9bebae1-8b01-4a24-bd50-77b86a9a08e1.png)

**Comment by davidzbiral** [comment]
In-statement Classifications and In-statement Properties are more important, they need to be more visible than just giving a link to the statement in which there is a mention of them. I.e., on the basis of your statement screenshot, @adammertel, we need to see more visibly in Detail that Bernard has mother P XYZ and brother G ZYX. 
I think this was decided - that we will create special sections:

Classification
Meta classification
In-statement classification

Properties
Meta properties [editable from Detail]
In-statement properties [non-editable from Detail, click icon available to open the relevant statement]

@rljshaw to cross-check this design proposal.

**Comment by adammertel** [comment]
A hotfix was deployed, which append cases when the entity was an origin into the list of UsedInProps.
