### ISSUE TITLE
Copy Reference and Reference part from previous statement in the order

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1529]
Create a functionality (button) which will copy, in the statement editor, the value of Reference and Reference part from the previous statement in the order of statements.

(If it is the first statement in this Subterritory, then we can either take the last statement in the previous Subterritory, or just drop this functionality. It is not a problem to add this for the first statement in a Subterritory, rather, we are making this functionality for Statement no. 2-200+ in that subterritory, where it will help a lot.)

**Comment by adammertel** [comment]
Sorry, I accidentally duplicated this issue into #1544
