### ISSUE TITLE
In-statement props strangely not indented in Editor window

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1530]
Lowered readability due to the fact that recently, in-statement props and relations stopped to be properly indented. Can you put the indentation back? (Connected to this: too big space between proptype and propvalue.)
![obrazek](https://user-images.githubusercontent.com/55400794/213863916-46c973ee-4aa1-4d31-8d55-c5a1b9aba985.png)

**Comment by Ptrhnk** [comment]
@davidzbiral Ok, identation is fixed now. 
For the big space, I have this screen, let me know if that's better (basically it will not be aligned vertically with other values)
<img width="783" alt="Screenshot 2023-01-21 at 13 24 28" src="https://user-images.githubusercontent.com/29732281/213868834-b061dd72-3f3d-4a26-a28d-3a04e203f177.png">

**Comment by Ptrhnk** [comment]
With buttons aligned it's like this
<img width="679" alt="Screenshot 2023-01-21 at 13 37 16" src="https://user-images.githubusercontent.com/29732281/213869322-12187039-83f6-41a1-8d8f-b31436397942.png">

**Comment by davidzbiral** [comment]
@Ptrhnk Ilike more v. 2 - with buttons aligned.
