### ISSUE TITLE
Date metaprops not attached to machine-generated root Ts' creation events

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1535]
The temporal information of machine-generated root T creation events is not imported.

[Instruction](https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=2056508047&range=V1): "The time relation cols. which follow belong not to the 'id', e.g. T1, but the the creation event, e.g. to E0001_T1." I.e., the metaprops with the time relations (all four) are missing from the Event.

E.g. T22	Bernard Gui’s Book of Sentences.
![obrazek](https://user-images.githubusercontent.com/55400794/213869313-46077f76-48eb-42e0-a1da-71d4f3d85b91.png)

**Comment by tomaham** [comment]
I see, I am looking into it.

**Comment by davidzbiral** [comment]
@tomaham : Same thing observed in machine-generated creation events of O/MSS, i.e. e.g. [these cols](https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=0&range=AG143:AV143) yield no dates - see screenshot.
I guess, no need to write another issue, since it is really the same thing as with Territory dates...?
![obrazek](https://user-images.githubusercontent.com/55400794/213873641-f3ec71a3-5566-4b33-b2ad-b625a68b21e5.png)

**Comment by tomaham** [comment]
Fixed, will be verifiable in the new reparsed import.
