### ISSUE TITLE
Implement self-loop in relations (original: Symmetrical property reciprocals not visible (not parsed?))

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1546]
C1430 "fellow reader" should reciprocate itself, i.e. "C1430", as PRR.
![obrazek](https://user-images.githubusercontent.com/55400794/214082002-1cfd1e73-ca0b-4bf6-8129-3bd36d362a57.png)
Nothing is shown in InkV as PRR, and the field is not editable.
![obrazek](https://user-images.githubusercontent.com/55400794/214082547-b31b27ae-0259-4217-9fcb-f705bcbedda4.png)

There is 41 instances of this - perhaps it is parsed but breaks InkV and we can solve it through GUI?

**Comment by davidzbiral** [comment]
@adammertel: Same thing in self-reciprocationg Actions, relation SAR. Example: "A0097	habuit in societe sua".

**Comment by adammertel** [comment]
working on this...

**Comment by adammertel** [comment]
handing to @Ptrhnk to check the logic and implement the self-loop parameter into the data model
