### ISSUE TITLE
Simplify the entry of epistemic level and logic in Property attributes

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1552]
There is only 3 values in elvl, and only 2 in logic. Simplify their entry - dropdown is click-move-click. Instead, how about we use a button switch similar to the one switching actant roles and status?
I.e., replace the first two dropdowns in:
![obrazek](https://user-images.githubusercontent.com/55400794/214266295-98d8e939-91f9-495f-994b-093b96128f05.png)
With something like:
![obrazek](https://user-images.githubusercontent.com/55400794/214266624-6235bbfa-62c8-4e04-9126-e1e2cf444873.png)

Of course, this can and should impact also the popup on actant involvement.

Rationale: we are selecting esp. elvl a lot => making it more convenient.

**Comment by adammertel** [comment]
Is going to be solved in another issue
