### ISSUE TITLE
Even if Katia has set Writing rights for Niort territory, she cannot delete statements in it

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1557]
![obrazek](https://user-images.githubusercontent.com/55400794/214343108-102795dc-868a-4d28-a8fa-4f095af52e72.png)

This is a bug I think?

I have now set her as admin - this means we will not have any good feedback on the functioning of rights, though.

**Comment by jancimertel** [comment]
delete action haven't been allowed for non-admins till now. added in #1599
