### ISSUE TITLE
Batch copying and moving of statements (bringing Territory tree closer to a folder/file structure)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1566]
We often have: Bernard said the same thing as Alice. Alice's testimony = 4-10 statements. Now we need to duplicate them one by one in Alice's Subterritory, then move them one by one to Bernard's Subterritory, reorder them there. It would be great to to copy& paste them, i.e. select them with Ctrl+mouse, Shift+mouse, and paste them to some territory. With a dialogue might be ok, not necessarily with DnD if difficult. E.g. the possibility of statements multiselect with Shift and Ctrl, and then "copy to" and "move to" function.

I guess some free library must exist for browser-based folder/file structures that we could just adapt? (Territories = folders, Statements = files).

To be explored and discussed.

**Comment by adammertel** [comment]
@Ptrhnk I think this issue involves the implementation of selecting S in the Statement list and then creating a new action menu in the header of the box. Lets probably start with this?

**Comment by davidzbiral** [comment]
A first quick kinda solution of what we need is this also this function: #1588. But we need both. 1588 is just probably quicker to implement - as one of the action buttons of a Territory in the Territory tree.
