### ISSUE TITLE
Make negative logic much more visible

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1570]
Negative logic is really an important feature - e.g. with a prop and relation, it says that the entity is _not_ such, _not_ that, i.e. the complete opposite of the positive logic. I.e., for better readability, we need the GUI to signal this in a much more intrusive way than the small icon following it - e.g. it can be made red, this could do, or something like that.

(I was considering even strikethrough of labels in a prop or relation in negative logic, but this is probably too complex and not so good an idea. A more visible icon could do.)

**Comment by Ptrhnk** [comment]
@davidzbiral With the red color it's already quite visible.
<img width="511" alt="Screenshot 2023-01-26 at 11 16 35" src="https://user-images.githubusercontent.com/29732281/214822808-291ae3e2-35d5-40cb-a46c-637625c132c4.png">

FYI I tried to use the prop for strikethrough, so you can decide if it's better and still readable as well.
<img width="509" alt="Screenshot 2023-01-26 at 11 16 19" src="https://user-images.githubusercontent.com/29732281/214822980-acd3f4d0-648c-417b-b7b2-b546810231e5.png">
