### ISSUE TITLE
Button for copying action properties from previous statement

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1572]
Just like it is possible to copy Reference from previous statement with a new button, we need to copy Action props from previous statement. Rationale: one event is often narrated in 10+ statements, and adding the time to each of the statements again is a real pain. A button to copy this from previous statement would make it easier. Copy all Action props - i.e. if there is more actions in the previous statement and they have different props, copy the props of all actions.

**Comment by davidzbiral** [comment]
@adammertel : It seems I understand you want to solve this with PropTag draggable from Statement list underneath an actant. Is it so? I think this could work, yes. But in such a case, we need a mouseover, over PropTag (and similarly for ClassificationTag and IdentificationTag), showing the proptype, propvalue, and potential child prop - important for us, so that we select the right one.

**Comment by adammertel** [comment]
> mouseover, over PropTag
Yes, this is a good point

So, closing this - it will be solved within other issues.
