### ISSUE TITLE
moving inkvisitor ddb1 backup to "z drive" (instead of DISSINET google drive)

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#1585]
As the DISSINET team google drive storage is limited to 100 Gb, we are trying to put the "cold data" to MUNI internal network drive, which we got from UVT.

It is a service, which is generally described here https://it.muni.cz/sluzby/sitova-uloziste-mu 

We have a group on PERUN, https://perun.aai.muni.cz/organizations/363/groups/10658/ , to which I just added you @adammertel .  By being in it, you should get access to ** \\ha-bay.ics.muni.cz\share **  with UCO and a secondary password.

Inside, you should see you have access to the folder DISSINET
![image](https://user-images.githubusercontent.com/3739529/216059361-d78ae0ea-6b3d-44bb-a1ed-e6318caaaad0.png)

**Comment by jancimertel** [comment]
Currently the backup retains last x days + first day of past months. The same is mirrored on gdrive.
It should be easily changed to store it ONLY on connected network disk. Will that be sufficient? (one backup destination).

**Comment by jancimertel** [comment]
is it possible to create special user for this so we don't have to use @adammertel 's credentials?

**Comment by tomaham** [comment]
Good. Point... well, probably yes, but we would have to ask the IT department.  I'll put this to the package for the Tuesday meeting with them.

**Comment by tomaham** [comment]
> It should be easily changed to store it ONLY on connected network disk. Will that be sufficient? (one backup destination).
Yes, that's the plan.

**Comment by jancimertel** [comment]
i should close this - out server is doing snapshots on OS level, so thi should be outdated.
