### ISSUE TITLE
Button to copy from previous or from selected statement

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1586]
Implement for Actions / Actants / References / Tags

Handle duplicates for tags

**Comment by adammertel** [comment]
@davidzbiral do you need the "copy from ... (+suggester)" + "copy from previous statement" option also for Tags? Or just Actions, Actants, and References?

**Comment by davidzbiral** [comment]
@adammertel : No, we don't want it for Tags. Actions, Actants, and References.
How are you thinking about Properties? In some ways, Props (alongside Refs) are among the most useful to copy from the previous statement. But the solution you seem to propose, i.e. to have a PropTag draggable from the statement list, seems to me a good one!

**Comment by Ptrhnk** [comment]
@davidzbiral So is it better to copy actans / actions from previous statement with or without props? Or would you use both?

**Comment by adammertel** [comment]
@Ptrhnk definitely with properties, in statement relations and in statement identifications :) Or one button for with and one for without (relevant for actants and actions only)
