### ISSUE TITLE
Duplicate Territory including statements

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1588]
We need a functionality of duplicating a Territory including its statements, and adding it to root or another Territory. This is one way to speed up the collection of repetitive texts - witness A deposed X, Y, Z. Witness B deposed the same thing as witness B.

Of course, new IDs to the statements. There will be things that need to be corrected manually - the metaprops of the duplicated statement (e.g. different witness, different creation event).

**Comment by adammertel** [comment]
Duplication should happen without the subT.

**Comment by davidzbiral** [comment]
@adammertel @Ptrhnk This is a great batch operation esp. for coding repetitive subTs - but it can also create a complete mess, e.g. if by error you duplicate a root territory with 10,000 statements! How do you revert? I did not realise when writing this that usually, batch operations are very powerful, and so there should be a way how to revert them in another way than deleting 10,000 statements one by one.

**Comment by Ptrhnk** [comment]
@davidzbiral @adammertel We curently implemented duplicating only T (with or without children) but without statements. So it could be probably better named.
