### ISSUE TITLE
Suggester returns some suggestions based on context

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1595]
When user opens a suggester, suggester may offer some suggestions based on the context without the need to type anything

**Comment by davidzbiral** [comment]
@adammertel Does this mean some form of pre-filling? Is it about pre-filling to confirm, or about sorting of suggester search results?

**Comment by adammertel** [comment]
This was meant to be a surprise :) But we were thinking about suggesting some entities in the statement editor suggesters before typing any character, just purely based on the content of the text of the statement. We are not sure how helpful we can get this function to be but I definitely think that it is worth a try.
