### ISSUE TITLE
Do not invalidate all queries instantly

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1598]
Something like a debounce method for queries would save a lot of FE-BE communication while not every rerender is needed after each edit. 
@Ptrhnk could you see if something viable is not already documented? I believe that this may speed up the application a bit.

**Comment by Ptrhnk** [comment]
Probably the biggest refresh rate right now for the start is in the statement list

**Comment by Ptrhnk** [comment]
Maybe also refresh the topic of optimistic mutations.

**Comment by Ptrhnk** [comment]
Create single place to ask for invalidation with debounce - layer over react-query

**Comment by Ptrhnk** [comment]
We decided for opposite logic - keep object with changes on FE and send update only once in a while. Start with editor - mostly new expanded row
