### ISSUE TITLE
Add actant slot semantic valency to Action tooltip

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1602]

**Comment by adammertel** [comment]
David, what form of information do you prefer?
One suggestion from my side

This is taken from the action in the db1:
```
      "valencies": {"s": "1",  "a1": "4", "a2": "NULL"},
      "entities": {
        "s": ["P", "G"],
        "a1": ["P", "G"],
        "a2": ["NULL"]
      }
```

Which will generate this new row in the tooltip

`Valencies Subject:  P|G (1), Actant1: P|G (4), Actant2: NULL (NULL)`

**Comment by davidzbiral** [comment]
@adammertel : There are three valencies. Entity type valency, grammatical valency, and semantic valency. I only want to display here the semantic valency, i.e. SUS, A1S and A2S. Not the two valencies you mention.

**Comment by adammertel** [comment]
@davidzbiral Thanks for the clarification, I think I understand now. 
I edited the "reserved core..." table
