### ISSUE TITLE
When duplicating an entity in Detail, Relations fail to be copied

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1609]
When duplicating an entity in Detail, Relations fail to be copied. Tested on an Action. The desired behaviour is that the Relations are copied (e.g. A1S etc.) - all of them. The user will then unlink those which should not be there - but many of them will when duplicating. E.g., I was duplicating "found (sb - to be sb/st" into "found (sb - to be which)" (Lat. _invenit_).

**Comment by adammertel** [comment]
Duplication logic needs to be moved from constructors.ts to the backend.
A new route will be added to FE.

@jancimertel notify me after this is ready on BE - I will finish the FE part.

**Comment by jancimertel** [comment]
added new endpoint POST /entities/:id/clone, you can find the implementation in the api clinet in entityClone function.
