### ISSUE TITLE
User choice of default label language

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1614]
Please implement the user's choice of the default label language asap. Tx!

**Comment by adammertel** [comment]
@davidzbiral More specifically - every time a user creates a territory, statement, or any other entity, the value of the `default language` is assigned to this entity language property. 
But just to be sure - this is not applied when the user duplicates an entity, right?

**Comment by davidzbiral** [comment]
@adammertel : Yes, exactly - does not apply to duplication. Duplicating should keep the label language of the original entity.
