### ISSUE TITLE
Identification must be transitive

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1620]
If A is identified with B and B with C, A must be identified with C. We need to introduce propagation, whatever the level of certainty - but of course, marking this level in a visually quite prominent way if other than certain. Now it is not very functiona (tested on certain IDE between Buck (German) = Buck (English) = this dog (English). We need it to work in a very similar way, if not the same way, as Synonym. 

We can consider locking the "dubious" and "false" certainties in meta Identification, if this makes matters easier. I would endorse that if this helps us gain the "cloud" logic (transitivity).

**Comment by davidzbiral** [comment]
@adammertel Solution needed - will we have a look at this when we meet if you see problems?

**Comment by davidzbiral** [comment]
@adammertel We should get back to this soon.

**Comment by adammertel** [comment]
@davidzbiral sorry for waiting too long with this one. 
I am not sure its a good idea to integrate this function like you suggest. The user sees the relation propagated in the graph. But the propagation (inferring the relations) could probably happen on the DDB2(?)!

Inferring the relation between A and C from your example could be complicated in sense of understanding what could happen if the user removes the A-B relation or changes the certainty.
My suggestion is to display those inferred IDE relations like we do in the graph but do not actually add this relation automatically into the DB.

**Comment by davidzbiral** [comment]
This is solved by the graph view - instruct InkV users to use graph view in IDE.
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/26c3900d-79d2-4cc8-a8bc-2bb26c5e30de)
