### ISSUE TITLE
After root T move, focus returns to last opened Territory

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1621]
Small bug: after root T move, the app scrolls down to the last opened root T, and even unfolds it - even if it was not unfolded any more when starting the move. There is no reason for this - after moving a root T, do not scroll anywhere and do not unfold what was not unfolded - only keep unfolded what was unfolded.

Up-to-date FF, v. 1.3.0 | built: Sat 04.02.2023 23:07.

**Comment by Ptrhnk** [comment]
@davidzbiral I don't understand this. Root T shouldn't be possible to move. Do you mean move inside of root T?
