### ISSUE TITLE
Add batch actions for editing References in Statements

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1625]
- Action "handle References" opens a modal window, where the user sees the selected Statements (if it is more than 10, let's see the first 10 + total count) and may add new resource + part pairs as it is done in Editor. Then, (after adding at least one), the user can click either the "append" or "replace" button, clicking which would result in a batch edit of the references.
 - Action "clear References" will remove reference items from all the selected statements. Ideally, a prompt for accepting this action is needed.

**Comment by Ptrhnk** [comment]
Dropdown for batch in statement list - move to T., duplicate to T., append R., replace R.
