### ISSUE TITLE
A question about re/using of Props

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1631]
@davidzbiral, this one is for you, but maybe also you @rljshaw 
One of the main new features for 1.4 is the reusing (let's call it "reusing" for the purpose of this issue) of the props to have better control over the data collection. Last week, you told me that props will always be "reused" with their child.  

_e.g., prop P has three children P1, P2, P3, and P3 has child P31, P32; all of them have some types and values. If you want to re/use P within another actant, we always talk about moving all the children (P + P1 + P2...), not only the original type-value tuple (P)._

Similarly, here is another question that is important before designing the UX. Let's say we have S1 with subject P1 and with a branch of various Props. And a user creates a new S2 with a subject P3. Now, the user wants to reuse the P1 props from S1 (see Picture). Is it more relevant to think that the user wants 
 - (i) reuse all the props from P1 in S1 on P2 in S2,
 - (ii) reuse just some specific props (with their children), one by one (e.g., just C1-va1 pair with children )
 - (iii) both tasks are important

![image](https://user-images.githubusercontent.com/12932677/220171640-0b48f3bc-a5fd-460e-b85c-29cab4adc1fe.png)

**Comment by davidzbiral** [comment]
I think it is fine to copy all, because removing those not applicable is very quick and easy.

**Comment by davidzbiral** [comment]
@adammertel : I think this was answered? What do you remember we opted for?
