### ISSUE TITLE
Replacing attribute modal by "Extended" panel

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1633]
A first step in the process of eliminating that unliked attribute modal window could be its transformation into a toggle panel. A user clicks the cog button as before, but instead of a modal window, he will see a new panel under the prop line. 
What do you think @davidzbiral?

Mockup prepared by @pondrejk . 

![image](https://user-images.githubusercontent.com/12932677/220865750-f9553a38-1d33-46a1-b944-8f608347d157.png)

**Comment by davidzbiral** [comment]
I suggest a compromise: immediately show (1) all elvls, (2) mood, and (3) mood variant. The other attributes only on a further click.

**Comment by adammertel** [comment]
And version 4
![image](https://user-images.githubusercontent.com/12932677/223977965-c0dbc3d5-6e7e-477c-80e0-6eda99d975d7.png)

**Comment by adammertel** [comment]
@davidzbiral could you please look once again at these graphical mockups and explain what solutions look better / are not feasible for you?

Ideally, a decision on this should be made as soon as possible, as this may be a blocker for us.

**Comment by davidzbiral** [comment]
@adammertel : V. 2.

**Comment by davidzbiral** [comment]
... mainly because in v. 3 and 4, proptype and propvalue, which are absolutely crucial, disappear behind those ex-modals.

**Comment by davidzbiral** [comment]
"Disappear" was an exaggeration, but of something real. Proptype and propvalue must be the most prominent element, i.e. most to the top, most to the left. Which v. 3 and 4 don't meet, and v. 2 is the only one which does.

My linking of v. 3 and 4 was not very thought-through. They hide primary information (propvalue and proptype) too much behind secondary information.

**Comment by adammertel** [comment]
@davidzbiral Okey, let me redesign this to address your concerns. I am worried that v2 is taking up too much space. It may worsen the UX with the Editor box (which is planned to be cut to half size in the future after redesigning Search) when a higher number of properties are applied to the statement.

**Comment by adammertel** [comment]
@davidzbiral some redesign of previous mockups

![image](https://user-images.githubusercontent.com/12932677/228686556-6bb2846b-9688-4aeb-b6f3-7c8021d23955.png)
![image](https://user-images.githubusercontent.com/12932677/228686615-de9bd908-cf62-41f6-9c13-830d81ee732f.png)

**Comment by adammertel** [comment]
Final version
![image](https://user-images.githubusercontent.com/12932677/229370832-5a938e40-b79c-444e-a562-90f593d8add0.png)
