### ISSUE TITLE
Default status of A and C upon creation: "pending"

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1634]
Upon creation of Concepts and Actions, given how much info (esp. Relations) they should contain before being approved, and how crucial they are when reused, the default status should be `pending`, not `approved`. Approved is there because we said that as admins, we do not want to, and will not, go through any Person, (Sub)Territory etc. that an editor creates to approve it. But we need a different approach to As and Cs. They are different - they are _types_ (rather than _instances_, i.e. entities such as PLOGESTRB), and thus, they require a different approach. For them, let's make the default status "pending", for the rest, let's leave it as it is.

Already observed that some approved should not have been approved, but are due to this defaulting.

Agreed with @rljshaw.

**Comment by Ptrhnk** [comment]
@davidzbiral so even when C / A created by admins should be pending? Right now all entities created by admins are approved and by non-admins are pending.
So if I understand it right - independently on rights C & A will be pending and others approved, is that right?
