### ISSUE TITLE
Improve the "something bad happened" messages

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1639]
This message usually appears when the server is down. If this is the case, use the text "connection to server lost", or "server is down", with additional information - "please, contact the developers". 
Also, only one message should appear; there is no reason to show 20 of them at the same time.

![image](https://user-images.githubusercontent.com/12932677/222101735-5f748038-9d5e-413c-876d-4c2ab9cf466c.png)

**Comment by adammertel** [comment]
The best solution here is probably to add an initial API request on the health route with a new specific error message.

**Comment by Ptrhnk** [comment]
@adammertel It's only one message now and more specific. Closing.
