### ISSUE TITLE
PRR should show also the other members of the synonym cloud

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1644]
There are relations:
- C fautor - SYN - C supporter
- C object of support - PRR - C supporter

Under "object of support", we would love to see the target of the PRR relation (with the unlink option), but also, uneditably, its synonym cloud, to see the lexico-semantic web more clearly. Simply there, at a side somehow.

**Comment by adammertel** [comment]
You can see the SYN cloud of C supported in the tooltip. Is not that enough?

**Comment by davidzbiral** [comment]
@adammertel You are right! It is enough. Still not used to this feature. Closing.
