### ISSUE TITLE
AEE reciprocation not displayed

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1678]
In A "crucesignatus/a/um", I select "crucesignatio" as its AEE. Under "crucesignatio", I don't see "crucesignatus/a/um" as I should.
[Link to Detail](https://dissinet.cz/apps/inkvisitor/#territory=aec842f6-3880-4570-bd48-e2b89cda36a6&statement=9de8a514-c30b-4f66-a261-663cca336d13&detail=021b0a4a-7ad2-431a-8bcd-ef2cff5e66d7%2Ca603952d-5d9c-4220-9377-6537db5aba46&selectedDetail=021b0a4a-7ad2-431a-8bcd-ef2cff5e66d7).

I don't remember whether there should be uneditable, or editable reciprocation. I think I remember it is a 1:1 relation, so it could be editable both ways.

**Comment by adammertel** [comment]
I see the data are coming into Detail correctly
![image](https://user-images.githubusercontent.com/12932677/229370318-f04164bb-00b1-40b2-a259-b9f338d80d27.png)

**Comment by Ptrhnk** [comment]
Solved by changing attribute to asymmetrical.

**Comment by davidzbiral** [comment]
@Ptrhnk Sorry, was not quick enough to answer. The solution should be the other one - it should be settable and unlinkable from both sides.

**Comment by adammertel** [comment]
From our perspective, in a symmetrical relationship, it matters on the element's position. In the case of AEE, one entity is C, and the second one is E, which means that their position is important and it makes sense to call it AEE only from the side of A.
So the issue now is to make it editable also from the side of C?

**Comment by davidzbiral** [comment]
> it makes sense to call it AEE only from the side of A.
@adammertel : this name makes sense from both sides. If only from A to C, it would be called just "Event equivalent (of Action)". But since we called it AEE, the label works both ways. So yes, please enable editing (adding, unlinking) from both sides.

BTW I am afraid I was using the term symmetrical in completely different ways - for relations which reciprocate the same relation back. E.g. SYN.

**Comment by Ptrhnk** [comment]
@adammertel @davidzbiral I don't really understand from the discussion if it's symmetrical or not

**Comment by adammertel** [comment]
From the perspective of the code, this relation is asymmetric because it make sense to think what element is first and what second.

**Comment by adammertel** [comment]
Every asymmetrical should be now editable from both sides

**Comment by davidzbiral** [comment]
@adammertel @Ptrhnk I think there is some chaos here. No, we do not want to make all editable from both sides. AEE, I wanted to display (it was a bug that it is not displayed), but editing SCL relation from above (from the superclass to its subclasses) will be confusing, and _will not prompt users enough to, after unlinking, add a new one_. This being said, let us not overthink things. Let us make AEE visible, which is the bug I referred to, but not editable from the C -> A side, only as before from the A -> C side. And let us leave all else untouched. I did not request any changes there.

**Comment by Ptrhnk** [comment]
@davidzbiral But AEE is now visible in inverse relations, this was resolved when the issue was closed earlier. For us that means that the atribute is asymmetrical, it would just make sense to document that, because it now doesn't match with the code. (btw you reopened the issue with comment that it should be editable from both sides)

**Comment by davidzbiral** [comment]
OK. The anti-pattern is not worth it. Only the inverse relation. Please read and close - we want only the inverse relation displayed, which disappeared for some reason.
