### ISSUE TITLE
Add websocket connection for realtime online check

### ISSUE THREAD

**Issue by jancimertel** [DISSINET/InkVisitor#1681]
Add websocket support on backend(without handlers).

Add component in the app to show connected/down status of the websocket connection, which will indicate unreachable server.

use socket.io for convenience.

**Comment by adammertel** [comment]
I suggest tracking the ping and displaying a small chart next to the status icon 

![image](https://user-images.githubusercontent.com/12932677/229375434-11cbf70b-2b5c-4b95-bb76-14e788f5b3f2.png)

**Comment by jancimertel** [comment]
added socket.io + some basic pinging
