### ISSUE TITLE
Batch delete for S in statement list

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1692]

**Comment by davidzbiral** [comment]
Is this a question to me? Can you describe more, @Ptrhnk ?

**Comment by Ptrhnk** [comment]
@davidzbiral Would it be helpful to add batch action for deleting statements in statement list? As there are actions for move and duplicate statements..

**Comment by davidzbiral** [comment]
@Ptrhnk Yes, it would be helpful - thanks if you implement. Of course in such a way that it isn't done by mistake, because there is (so far) no undo!!!
