### ISSUE TITLE
fix uncommon cases of "NULL" values from import data

### ISSUE THREAD

**Issue by jancimertel** [DISSINET/InkVisitor#1696]
it happened in ActionEntity implementation - a1 field could have ["L", "NULL"] values

**Comment by adammertel** [comment]
@davidzbiral I believe that "NULL" was supposed to be empty? Or what is the source of this problem?

**Comment by davidzbiral** [comment]
@adammertel, @jancimertel Tell me what entity legacy_id or UUID it is and I can inquire. Other than that, "empty" is a legitimate value (as one among many, or the single one - in the latter case the actant slot triggers invalidity notification [see gdoc InkVisitor warnings] if occupied).

**Comment by jancimertel** [comment]
This issue is connected to import functionality - "null" is probably empty (not string literal) value and to my understanding it can be just filtered out.

**Comment by jancimertel** [comment]
pushed constraints + tests to #260
