### ISSUE TITLE
A series of validation rules for Relations

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1698]
Let's introduce a series of validations for Relations - if something is unclear or seems not right, let's discuss.
These validations should be done the "mild way", as similar to the validation of actant positions in statements as possible; the difference is that there is no statement list to display a warning icon, but such warning icons or markers should be visible in search results and suggester dropdowns somehow - in a visually very mild and unobtrusive way, because there will be a lot of invalid data under normal circumstances.

All of the rules are based on our implicit or explicit guideline-level rules, but thanks to the application, we should now try to check them. Probably, for modular development, there should be the option for users (e.g. from other projects) to switch them off or on one by one, i.e. we should have a list of rules, and the user, in a modal window under customization, would say whether to check for this or not (by default in all DISSINET deploys, switch it on).

This validation is partly related to status, i.e. it is understood that "pending", "unfinished" and "discouraged" can be not completely valid (or not yet), so there is an argument to make the invalidity more prominent for "approved" than for the other statuses - but this is just an idea. Or at least, make it very unobtrusive (while visible), because incomplete formal validity of data is the mark of work in progress, not complete errors - outright data model errors the app does not even allow to save.

This validation will help to data validity, and also other projects than DISSINET to set their rules that the app should check.

Rules:
- Any C must have a SCL value (apart from the root entities which do not have a parent; in DISSINET there is only one root entity, C "entity", but I would probably tolerate that C "entity" will display as invalid rather than introducing some new "root" attribute).
- All SYN must share all (direct) SCL values with one another, or its SCL value must be a SYN. E.g.: if C apple - SYN - C jablko, then, for C apple and C jablko to be valid, there must be either (A) C apple - SCL - C fruit, and C jablko - SCL - C fruit, or (B) C apple - SCL - C fruit, C jablko - SCL - _C ovoce_, _and_ C fruit - SYN - C ovoce. (There is the problem of flow, i.e. when and how to display this to the users and how to allow them to find where the problem is and rectify it - it would warrant some comparative "view" of synonyms, some multi-detail hiding the Editor box perhaps - comparative view is I think requested somewhere already as part of views; but it is good, in v. 1, to start simple, just displaying that it is invalid and leaving the user in the darkness, and develop better editing as part of comparative views). 
- Valency of A - basic check: at least one slot needs to have entity-type valency filled in to be valid.
- Valency of A - checking symmetry between the three valency types: unless the _only_ value in entity-type valency for the given slot is "empty", then (a) grammatical valency must be filled in (at least one character), (b) semantic valency of that slot (SUS, A1S, A2S - depending on the slot) must be set. Also the other way around: if there is non-empty grammatical valency, then the other two types of valency must be filled in for the given slot. I.e., simply put: if any of the valencies is set and the only value is not "empty" (this last condition applies of course to entity type valency only), the other two must be filled in also for that slot. Works also the other way: if the slot has entity-type valency empty only, then the grammatical and semantic valency must be empty.

There are some things that InkV is checking already, such as circularity in SCL. This means it cannot be saved - but it can still be imported. Thus, there is a question whether to incorporate those rules too in the checks, to signal imported invalidity. Probably yes, if it can be done. But, unlike the above, these things which the app does not allow should not be customizable: they are deeply anchored in the data model of all CASTEMO knowledge graphs, not just DISSINET rules.

**Comment by davidzbiral** [comment]
I now agree that probably also the check whether valency is filled in should be done even on statements using that action, as a prompt to correct that action. So the addition to the [gdoc](https://docs.google.com/document/d/1pmsCjNLHAOA58gVrwV64Qfsp-9wO4kZoXbtyjViMuQA/edit#) are valid.

**Comment by adammertel** [comment]
@davidzbiral, it's like 5 issues in one here :)

The warnings in the suggester are not possible in a reasonable timeline. Warnings will be displayed in the Statement list, Statement Editor, and in the Detail.

I moved the rules to the [gdoc](https://docs.google.com/document/d/1pmsCjNLHAOA58gVrwV64Qfsp-9wO4kZoXbtyjViMuQA/edit#)

**Comment by davidzbiral** [comment]
@adammertel : display in Statement list, Statement Editor, and the Detail are fine.
I edited the gdoc and added one further validation concerning AEE there.

**Comment by adammertel** [comment]
@davidzbiral could we also put #1388 into the [gdoc](https://docs.google.com/document/d/1pmsCjNLHAOA58gVrwV64Qfsp-9wO4kZoXbtyjViMuQA/edit#)?

**Comment by jancimertel** [comment]
warnings should be implemented according to table (Entity warnings)

**Comment by jancimertel** [comment]
moved to #260

**Comment by jancimertel** [comment]
closing, AVAL warning remains - moving it to partial issue #1817
