### ISSUE TITLE
Check for non-breaking space character "0xa0" (U+00A0; NO-BREAK SPACE) in text fields

### ISSUE THREAD

**Issue by GideonK** [DISSINET/InkVisitor#1706]
While extracting multi-word labels from Concepts and trying to find them in Latin WordNet, I ran across a message stating a JSON issue (from the Latin WordNet side). On closer inspection, it turned out that the non-breaking space character ["0xa0"](https://utf8-chartable.de/unicode-utf8-table.pl?utf8=0x) may have been the culprit - it seems that some software has issues handling this character, and I suspect that it shouldn't be there in the first place. Just a guess: somebody copied and pasted from the OCR'd PDF into the label field (OCR can produce such characters from my experience). Here is the entry:

`{'class': 'C', 'data': {}, 'detail': 'knowing him/her/them to be a heretic / heretics legal circumstance', 'id': 'e3eccd4e-d27d-4785-9a6b-ac32ca7fab23', 'isTemplate': None, 'label': 'sciens\xa0esse hereticum/am/os/as', 'language': 'lat', 'legacyId': 'C0394', 'notes': ['Import batch [January2023] 2023-01-21 18:58:21.366042'], 'props': [], 'references': [], 'status': '2'}`

Suggestion to check for the existence of this character (and possibly others?) after saving entry.

**Comment by adammertel** [comment]
Thanks for spotting this. I definitely agree; making a check after saving the label value could be implemented quickly.

@GideonK what about other input fields? Should we check and remove ["0xa0"](https://utf8-chartable.de/unicode-utf8-table.pl?utf8=0x) from other places also?

**Comment by GideonK** [comment]
@adammertel I didn't check other input fields, but I would say yes, as the same is bound to happen with automated processing of DDB1 if they exist elsewhere.

**Comment by jancimertel** [comment]
definitely, will look into it

**Comment by davidzbiral** [comment]
@adammertel I confirm that this specific operation should be done also on other fields: detail, note, and text field in Statements.
