### ISSUE TITLE
Label language upon entity creation; customization of default label language

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1707]
I have seen many errors in label language used upon entity creation - esp. English concepts tagged as label language = Latin. We need to implement a check of this. But in this case, the approach would have to be special, since these entities should not be tagged as invalid forever, just in special circumstances (because they probably are valid).

I thus propose the following as an optimal solution: 
- let the user select a default label language - one of them or none;
- in app's default customization settings, no default label language is selected;
- if none is selected, the field is empty upon entity creation;
- if some is selected as default label language, then actually yes, do prefill it.
Makes sense?

**Comment by davidzbiral** [comment]
@adammertel : In relation to #730, I think let us introduce two default languages:
- "Default label language for entities" (by default "-"); used for pre-filling (or not if "-") the language of newly created entities in Detail and the small dialogue of entity creation.
- "Default statement language"; use this for validation requested in #730.

**Comment by adammertel** [comment]
This sounds reasonable, I can look at it this weekend.

**Comment by davidzbiral** [comment]
@adammertel Reima's request, let's talk if unclear. 
1. Tell me, is #730 really covered by solving this issue?
2. Reima has a very sound idea: more default languages of one user possible. Then, the condition applied to proptype and propvalue will only apply if proptype and propvalue in an in-statement prop is not on the list (i.e. it can be e.g. 2, 3 languages, not one only).

**Comment by adammertel** [comment]
@davidzbiral Yes, I believed that the #730 and this was done, but I can recheck.

**Comment by davidzbiral** [comment]
Discussed, implemented, train DISSINET team that it already works.
