### ISSUE TITLE
Non-Concept entities cannot be created by "new entity" in Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1721]
Allow this, no reason to prevent it. It blinks and sets to C.
![obrazek](https://user-images.githubusercontent.com/55400794/236266938-74e513b9-5971-4d43-9d89-914eeacd9d07.png)

**Comment by Ptrhnk** [comment]
Tried on staging and it works. Where are you testing?

**Comment by davidzbiral** [comment]
@Ptrhnk Main deploy, as almost always - this is where I work. If this is not an unstable version currently, perhaps we could update soonish? (But we can live with this for one month if needed.)

**Comment by Ptrhnk** [comment]
@davidzbiral Ok, it's now fixed. Version will be consulted.
