### ISSUE TITLE
Do not scroll to current statement in Statement list after db fetch

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1734]
Do not do this - leave the statement list scrolled where it was. (We usually DnD more entities from one statement to our current statement.)

![spurious-statement-list-scrolling](https://github.com/DISSINET/InkVisitor/assets/55400794/8db359ac-4f40-4d08-9057-4513c3631211)

**Comment by davidzbiral** [comment]
@adammertel Do you understand the issue?

**Comment by davidzbiral** [comment]
@adammertel , @Ptrhnk Another CASTEMO users hates this too just as I do, could you attend to it? Thanks!

**Comment by Ptrhnk** [comment]
@davidzbiral I turned it off also for refresh button in Statement list.
Scroll is now preserved for
- initial load
- all kind of create / duplicate S.
- choose different T
- choose different S
