### ISSUE TITLE
Enable cross-entity-type Identification

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1735]
Cross-entity-type identification should be possible. E.g., on a boat, something can happen (=> L) and it can then be solved (=> O), and thus we need IDE between the L and O.

I thought we already did this, but don't find it implemented, so perhaps I just forgot to tell you.

**Comment by Ptrhnk** [comment]
@davidzbiral In doc it's marked only for the same entities but so far it's implemented for cross entities, can you make a screen where you see it doesn't work?

<img width="415" alt="Screenshot 2023-05-30 at 11 55 45" src="https://github.com/DISSINET/InkVisitor/assets/29732281/01a3a0ab-aee7-47ac-a5e2-8c91d10bd539">

**Comment by davidzbiral** [comment]
@Ptrhnk In the current version, it works, yes. Probably I was either commented on an older one (I am generally using main deploy, not staging) or I was wrong.
