### ISSUE TITLE
When creating entity from Detail / Relations, also open the usual entity creation box

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1737]
When creating entity from Detail / Relations, also open the usual entity creation box rather than creating it directly without doing it.
I.e., even there we want this dialogue:
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/4cf4b362-855c-4d4c-aed8-30c3a35c231e)

**Comment by Ptrhnk** [comment]
So all suggesters in detail will open create entity modal for every entity class
