### ISSUE TITLE
Synonym clouds: why I cannot add more than one SYN?

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1738]
I have Spiritus sanctus and Sanctus Spiritus, which are SYN. Why I cannot also relate Spiritus sanctus to another C, "tertia persona in Trinitate"? There is no possibility of extending the SYN cloud, it is as if SYN closed again only to 1:1 relation.

**Comment by Ptrhnk** [comment]
@davidzbiral now it's implemented in the way that you need to open [tertia persona in Trinitate] and add one of the synonyms which are in the cloud.
If you think it's not enough, we can add the possibility of adding to cloud directly.

**Comment by davidzbiral** [comment]
@Ptrhnk this would be probably fine, but this then leaves no opportunity to interconnect two SYN clouds. If you open "tertia persona in Trinitate", you will find that it already has a SYN, so I cannot add another one.
