### ISSUE TITLE
bug in coordination of  GUI statement -> actants  ->props  interface and JSON data?

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#1739]
In the statement with id "3226c626-bbec-4b61-a108-9d6974921530", the GUI interface for the second actant props looks like this

![image](https://github.com/DISSINET/InkVisitor/assets/3739529/f67cf5ba-a66e-4881-810e-c755ef2e8140)

See the second property "same content", the value slot is empty there.

But in the json data there is uuid of object which otherwise does not exists.  See the image and look for value object of the second prop object, there is object with entityId uuid "d6e9dc12-52fd-4841-a9ff-e94ac0178a26".  This  value object does not exist.
![image](https://github.com/DISSINET/InkVisitor/assets/3739529/ac6b4eb9-6dfe-4cc0-ac5f-081465573c1d)

Some possible bug in deleting the json values with wild GUI operations?

**Comment by adammertel** [comment]
Thanks, @tomaham. This will probably be hard to replicate. 
In the statement with Stephanus Iohaninus, I see the prop values filled in properly.

I am trying to replicate this bug but we probably will need more e2e tests to cover all possible cases that may result in this situation

**Comment by tomaham** [comment]
Sure, feel free to close this.
