### ISSUE TITLE
C and A should not have IDE Relation (Identification)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1749]
For A and C - which, unlike PLOGESTRBV, are classes, not individuals - IDE does not make sense - they have SYN for these cases. I.e. a semantic rather than ontological relation.
Please check whether IDE is in use between some C-C, C-A, and A-A in the main InkV deploy, make a log of IDs and labels if it does, hand over to David to check, and when checked and rectified, and remove this possibility from data model (not just GUI).

In the [gdoc](https://docs.google.com/document/d/1cqr-kIF_W6voea7RHjf1vFv-BRKRdcFIiqDLLfjK7BE/edit#bookmark=id.lzu4f21zshfb), IDE was not marked for As and Cs.

**Comment by Ptrhnk** [comment]
@davidzbiral Also it's marked that you can link only the same entities in doc if it's correct which was until now for all combinations (and the V is missing in doc as well, but I'm adding it)
