### ISSUE TITLE
Attribute choices (ex-modals): enhance contrast

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1750]
Thanks for the really nice new features in InkV, such as getting rid of attribute modals for mood etc.
Please make higher contrast of the selected option (icon), both in the actant position and in the other options.

**Comment by Ptrhnk** [comment]
<img width="627" alt="Screenshot 2023-05-29 at 17 38 38" src="https://github.com/DISSINET/InkVisitor/assets/29732281/9a8c219c-fc1f-489f-97af-7f8698494859">
Is it better like this?

**Comment by davidzbiral** [comment]
@Ptrhnk Yes, great  think!
