### ISSUE TITLE
When copying entity, do not copy its inverse relations

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1753]
This "visit" entity 66087e5e-5c97-4dfe-9d32-b811503d4b37 was created by mistake. It copied its inverse relations, which is bad. **Only the relations _from_ the entity which is being duplicated** should be copied. The inverse relations no, because this means: 
1. changing other entities at the background, without the knowledge of the user;
2. and - it seems - also disabling this entity's removal.

Try to remove this entity 66087e5e-5c97-4dfe-9d32-b811503d4b37 - it cannot be removed, while it has no relations of its own (only inverse relations copied from its model) and it is not used anywhere.

**Comment by jancimertel** [comment]
@adammertel 
packages/server/src/modules/entities/index.ts - await Relation.findForEntity(request.db.connection, originalId) should be filtered
