### ISSUE TITLE
The JSON actant composition

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#1757]
@adammertel 

Can you clarify the logic behind the actant JSON attributes concerning the _entityId_ vs _identifications_ vs _classifications_?  

See this
![image](https://github.com/DISSINET/InkVisitor/assets/3739529/a2003739-c532-4440-8a36-15d5fbb91b35)

There is entityId filled, but identifications and classifications are empty.  But the entityId points to the Person "Raimundus...". This conceptually identifies the actant object with the Person entity.  So this is identification.  (Or not?)

But what should be then in the "identifications" array? :)

**Comment by adammertel** [comment]
@tomaham i would say that the identifications and classifications are the in-statement identifications and classifications defined on that actant while entityId is the link to the particular entity. 
I can check it tomorrow to make sure I did not forgot anything here.

**Comment by adammertel** [comment]
@tomaham I am sorry, but it looks like entity `9447a241-cfb2-4f09-ace2-70b5c101f994`, P:Raimundus de Chaliavo does not have any (meta) identification or in-statement identification.

**Comment by tomaham** [comment]
@adammertel why are you sorry? :)

You have forgotten what this is issue is about, haven't you? :D

It is old stuff now, it was triggered by communication / conceptual fog around the difference (see original question). This  was not bug report, but request for data model explanation. 

I am closing, I got it from certain slack conversation.
