### ISSUE TITLE
add password management for users

### ISSUE THREAD

**Issue by jancimertel** [DISSINET/InkVisitor#1789]
Add endpoint for editing user's data, accessible by respective users.
This endpoint should accept user's data - currently only password.

On frontend, prepare required components for manipulating with user's password.

**Comment by jancimertel** [comment]
@Ptrhnk endpoint updated

**Comment by Ptrhnk** [comment]
@adammertel What about some minimal length and some symbol (safety) requirements. Is it necessary? Maybe the length at least?
