### ISSUE TITLE
Value class unavailable for creation

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1795]
The V entity class not available in dropdown in the Sandbox deploy.
v. 1.3.2 | sandbox | built: Tue 04.07.2023 09:38
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/64ed2846-5f0a-49b0-bfa2-50e541ca17c3)

**Comment by davidzbiral** [comment]
@Ptrhnk This must be a misunderstanding. We need to create Vs all the time. What request do you refer to? In any case, we need Value entity type creation in any suggester. Just we do not want to _search_ through Vs, because Vs are always new, and 41 bottles should not connect to 41 years of age.

**Comment by Ptrhnk** [comment]
@davidzbiral That makes sense. Probably a misunderstanding. I allowed that and closing.
