### ISSUE TITLE
handle audits for deleted users

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1797]
User makes changes and then is removed. Missing user is not loaded to audits which is followed by error and the audits are incomplete.

**Comment by Ptrhnk** [comment]
@jancimertel @adammertel Some ideas how to handle this?

**Comment by jancimertel** [comment]
I would like to respect rest convention to return erroneous response in any case.
So instead i created two options to ignore error toaster in calls:
- by cloning the api instance without response interceptors ( `api.withoutToaster().usersGet(user as string);`)
- by providing optional configuration to each request (`await api.usersGet(user as string, { ignoreErrorToast: true});`)

https://github.com/DISSINET/InkVisitor/blob/40c0b6507e51f7a8fc09fd654fc91880e6b97087/packages/client/src/components/advanced/AuditTable/AuditTable.tsx#L58

**Comment by Ptrhnk** [comment]
@jancimertel Okay, this option will be definitely useful, but how we gonna display audits for things changed by missing user?
