### ISSUE TITLE
AVAL entity warning 

### ISSUE THREAD

**Issue by jancimertel** [DISSINET/InkVisitor#1817]
https://docs.google.com/document/d/1pmsCjNLHAOA58gVrwV64Qfsp-9wO4kZoXbtyjViMuQA/edit#heading=h.qf272wpfiqhh

**Comment by adammertel** [comment]
@davidzbiral when you have some time, could you please add more description to this rule? Ideally with some real-world examples. Ideally in a format which can be used for testing - cases when this warning should appear and when is should not appear.

**Comment by davidzbiral** [comment]
@adammertel I don't understand the problem, probably, at least if it is not clear after I corrected the old name (grammatical valency) to the new one (morphosyntactic valency).
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/baede0c5-4273-4934-9110-33781af97ec0)
If subject's entity type valency is Person or Group, then SUS must be filled in. If it is not filled in, AVAL error.
If subject's semantic valency is filled in, and entity type valency is "empty" or is left empty, AVAL error.
Clearer now?

**Comment by adammertel** [comment]
![20231102_182103.jpg](https://github.com/DISSINET/InkVisitor/assets/12932677/3dd7826d-08e0-45c2-9669-25b35a1916ce)

Not sure this has any value, but trying to reconstruct the AVAL presence with this table.
