### ISSUE TITLE
New modality: Expectation

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1830]
Please introduce a new modality value in the dictionary and the GUI - "expectation".
Rationale:
It is meant for things such as: 
quedam femina que vocatur Taria deberet fieri cardinalis
et quod ipsa Guillelma debebat resurgere et ascendere in celum videntibus devotis illius sancte Guillelme
quod {sicut Christus passus fuit in forma hominis} ita illa Guillelma debebat pati in forma mulieris
(audivit ab eis) quod ipsi debebant mutare leges et facere Evangelia nova
quod quidam ex discipulis debet tradere eos in manus fratrum,
This is neither wish, nor possibility (could), but some “expectative” – it is futural rather than wishful; it feels strange to code this simply as “wish”, and I felt even before that we are overstretching the breadth of “wish” too much. Here are some a very clear example. 
It is not possibility either, i.e. something “can happen”, but about expectation (something “will happen”).

Detailed rationale in [team drive](https://docs.google.com/document/d/1Mj7autiuXhLNB9CQvaQYQ9Cq6nN0BXoIpkjiT12jovc/edit#bookmark=id.zbd7f0b4u2yc).

**Comment by davidzbiral** [comment]
@adammertel This is sorely missed. The low frequency of updates on our main deploy will already start to influence the data in a negative way.

**Comment by adammertel** [comment]
David, this is already integrated. I am closing this.
