### ISSUE TITLE
New funding body

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1844]
Please add the credentials of a new funding body into the application.
https://drive.google.com/drive/u/0/folders/1e-KE0VG-GRu4FxqDfp1QFH-jIx8AWZWC

**Comment by Ptrhnk** [comment]
@davidzbiral Can you please provide the description for funding section?

![Screenshot 2023-10-06 at 12 51 40](https://github.com/DISSINET/InkVisitor/assets/29732281/9414d245-2c21-488f-b81c-b933aeb24b6c)

**Comment by davidzbiral** [comment]
@Ptrhnk Czech Ministry of Education, Youth and Sports & European Union (project “Beyond Security: Role of Conflict in Resilience-Building”, 9/2023–6/2028

Dále prosím uvést měsíce i u ostatních již uvedených:
ERC: 9/2021–8/2026
EXPRO: 1/2019–8/2021
MU, FA: 6/2022–8/2023
