### ISSUE TITLE
Error message upon load

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1849]
1. Please remove unknown errors generally - improve error messages.
2. Remove this one which appears a couple of days.
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/04ef03f8-6530-41fe-aecc-c15f5f6f4fec)
Tx!

**Comment by jancimertel** [comment]
Error should not appear again. 
Unknown errors removal - pending.
