### ISSUE TITLE
Reimplement Subterritories divided by another Subterritory (of lower or same level)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1850]
Split Subterritories are not solved in InkV - in gsheets we had this feature of returning back to the original Sub-T level, but in InkV we don'. There, we have to artificially create 2 Subterritories and add metadata to both of them, which is wrong; it is more work, and it is spurious work; e.g., they will then be counted as 2 documents rather than 1 (and IDE relationship is also not a solution, it is semantically a completely different relation). Thus, we'll have to reimplement the split Subterritories.

Should be done before import of Statement data (Kent, Seila).

**Comment by davidzbiral** [comment]
Current opinion: solved by adding anchors, we will not try to solve the order of "folders" (Ts) mixed with "files" (Ss) it in the territory tree.

**Comment by adammertel** [comment]
I would probably need more context here, ideally an example?

**Comment by davidzbiral** [comment]
@adammertel : 
<T1>T1 starts.
<T1.1>Now a nice T1.1 is interposed, such as a letter included in a broader chronicle.</T1.1>
Now T1 happily continues
</T1>

Is this structure possible in anchor adding? I think it maybe is. If it is, let's close the issue, it is solved.
If it isn't and we need to artificially divide T1 into T1 and T2 just because of the technical limitations, it is bad and we must solve.
