### ISSUE TITLE
Bugs in data validation

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1854]
Great design of data validation, but let's get some things right - there are many warnings which are not correct.
Can you fix, and also do some better testing of the validation features?
1) As seen in screenshot, subject is right for this Action - why error?
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/5878660f-3757-448c-8a75-19d6ee524a4f)
2) Same here, for a2:
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/1cf1b588-3367-4ca4-abaf-18716502732f)
And many more. Probably all of this is the same error.

**Comment by adammertel** [comment]
@jancimertel 
could you please take a look on how `empty` is processed. I can reproduce this error only when several (1+) options in valency are selected including the `empty` value.
