### ISSUE TITLE
Upon unfold of Statement validity warning, open Action type in Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1857]
If sb wants opens validity warning, it means that they want to inspect and fix it, and this means they need to see the current Statement's Action Type in the Detail, because it is there that the valency frame with which the Statement clashes is stored. Usually, user has opened a different Action, which confuses.
Therefore, when unfold is clicked upon and there is an error concerning the valency frame (actant slots):
- open that Action in Detail, if not opened;
- activate its tab, if opened but tab not active.
(I have observed myself to do an error or at least losing time all the time without this.)

**Comment by adammertel** [comment]
@davidzbiral the problem here is that the warning is an outcome of the effect of ALL the actions used in this statement. I can see how this may work when we have only one A, but ehat should be opened in detail in case we have 3 As in the statement?
