### ISSUE TITLE
Allow drag&drop of entities from the Detail tab heading into Detail and Statement editor

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1873]
Oftentimes, when I am editing some entity in Detail, I want to drag and drop in some field an entity opened in another tab of Detail. Thus, taking the "tag" from the tab heading, i.e. allowing to, as if, drag and drop the tab into a suggester field would help. 
Potential partial design conflict (solvable) with #1340.

**Comment by Ptrhnk** [comment]
@davidzbiral What do you think about this solution for dragging to suggesters?
https://github.com/DISSINET/InkVisitor/assets/29732281/b862b98a-230e-4040-9f99-9538deb701de

For changing the tab order, I'd suggest dragging just the panels similarly to internet browsers (separate it from this functionality)

**Comment by davidzbiral** [comment]
@Ptrhnk I like this, go ahead! I only don't understand how tab move will work, because it seems to me it is in something of a design conflict with this functionality...? But I am sure you will find a good way.
