### ISSUE TITLE
Does "any" include "empty"?

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1876]
@davidzbiral 
I think we have been talking about this earlier. Just to make sure, once again :)
Does `<any>` includes `<empty>`?
This is mostly relevant to the valency select, see the video:

![any-option](https://github.com/DISSINET/InkVisitor/assets/12932677/7bfd0056-6eab-4757-83ce-01bb8d17c824)

**Comment by davidzbiral** [comment]
@adammertel : No, Any and Empty are mutually exclusive. Let us even check whether the data model is set in a right way, because Any is actually not meant as any positive value, but only as a GUI shortcut, for convenience, to quickly and simply add all entity types (not empty, though).
