### ISSUE TITLE
Search interface quick change: advanced options only upon unfold

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1891]
The options are "advanced" and rarely used, and make that we need to scroll to see search results. Show these advanced options only upon unfold (clicking on a pseudo-link "Show advanced options" or something similar).

**Comment by Ptrhnk** [comment]
@davidzbiral So everything excluding label should be hidden?

**Comment by davidzbiral** [comment]
@Ptrhnk Yes.
