### ISSUE TITLE
Data validation: condition by CASTEMO subtype

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1900]
When we develop semi-structured data collection protocols for any T, we will want to switch off some validations in Ts which are tagged as a SumCASTEMO data collection campaign rather than SelCASTEMO or FullCASTEMO. E.g. checking valency frames if more verbs are used (which is an important principle of SumCASTEMO).
Connected to: #1152

**Comment by adammertel** [comment]
Is this possible to satisfy by adding options in the new development menu, allowing the owner to choose which validations are going to be applied to all users in the development?

**Comment by davidzbiral** [comment]
@adammertel : No, because in the same project (deploy), the same owner will have Ts based on different types data collection campaigns. So it is really not a thing of global customization but more local, T-based validation. But definitely good to think about it in this two-level hierarchy: global and T-based.

**Comment by adammertel** [comment]
Closing in favor of #1989?

**Comment by davidzbiral** [comment]
Yes.
