### ISSUE TITLE
When clicking on a folded statement list, unfold statement list

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1901]
... in the same way as if the user clicked on the button:
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/561901f6-3cf9-4b24-8df7-aac7e2afd587)

**Comment by Ptrhnk** [comment]
@davidzbiral Do you mean to make the header of the statement list clickable?

**Comment by davidzbiral** [comment]
@Ptrhnk Yes, to make the header clickable, and upon click, the statement list will unfold. I followed a user when working and he was visibly expecting this functionality :-)
