### ISSUE TITLE
Enable SOE for Groups (G-G) and Statement-Statement (S-S), and Statement-Event (S-E)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1903]
[EDITED:] Enable SOE for G-G, S-S, and S-E. (GDoc updated.).

**Comment by davidzbiral** [comment]
@Ptrhnk Also tooltip should be revised, i.e. for what entity to show SOE relations.

**Comment by Ptrhnk** [comment]
I added #1906 for tooltip separately
