### ISSUE TITLE
Value entity type should allow Classification Relation (CLA)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1904]
Value entity type should have CLA. Please guys point me again to the document where we did this, because it clearly needs revision - two errors (this one and #1903) discovered recently, so we need to get this right.

**Comment by Ptrhnk** [comment]
@davidzbiral https://docs.google.com/document/d/1cqr-kIF_W6voea7RHjf1vFv-BRKRdcFIiqDLLfjK7BE/edit
Links related to relations are in github wiki -> relations

**Comment by davidzbiral** [comment]
@Ptrhnk It was missing, I added it to the gdoc, please implement - V can have CLA.
Mostly for historian users, this is linked to a [debate on single-use Concepts](https://docs.google.com/document/d/1Mj7autiuXhLNB9CQvaQYQ9Cq6nN0BXoIpkjiT12jovc/edit#bookmark=id.cznseq7hiuum), something we generally discourage. Concepts are Types, and thus some text snippets will be Vs, and thus they need to allow CLA (e.g. in "it happened one day", the "one day" Value of a temporal property should allow to be classify through CLA as "day").
