### ISSUE TITLE
Add SOE to tooltip

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#1906]
@Ptrhnk Also tooltip should be revised, i.e. for what entity types we should show SOE relations. Can you add some explanatory remarks to
E classes tooltip
E classes detail
E classes Detail inversed

in the gdoc, so that I re-understand what they mean and can suggest? Basically I think it is such an important relation that it should be visible in tooltip, if non-empty, for all entity types allowing SOE.

**Comment by davidzbiral** [comment]
@Ptrhnk Yes, add SOE in the tooltip for all entity types which can have SOE. SOE is a fundamental relation.

**Comment by Ptrhnk** [comment]
@davidzbiral 
I tested behavior of tooltip on staging and SOE is visible for all required classes, so can you please reflect this behavior in the gdoc. (check all columns of SOE)
<img width="401" alt="Screenshot 2023-12-13 at 13 49 41" src="https://github.com/DISSINET/InkVisitor/assets/29732281/568e8658-ac08-4cb4-a3e3-579aebe3bbf3">
