### ISSUE TITLE
Add "Used in References"

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1934]
In Detail of R entities (R entities only, not others), together with Used in Metaproperties etc., add also "References", and output uses of that R as the reference in References.
Add it at the end of the list of Used in (...).
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/927cc0b9-1ae3-467d-8ea7-7b1bc1d771a3)

**Comment by adammertel** [comment]
@jancimertel could you append this information to the response from BE and let us know that its ready for the implementation on FE?

**Comment by jancimertel** [comment]
added on backend

**Comment by Ptrhnk** [comment]
@davidzbiral As "output uses of that R as the reference in References" you mean to show to whole relationship between 
[used in entity / statement | resource | part] as a table, similar to the others used in?

**Comment by davidzbiral** [comment]
@Ptrhnk In the end I think it would be too many, one R can be used in tens, hundreds, and it is not so important to see it. It is more a fuctionality for advanced search. Thus, closing this issue, let us not implement. I am closing, and replacing this with #1958.
