### ISSUE TITLE
Change display of Part Label of Resources in Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1935]
Solve how not to make the line uneven. Probably: if that R entity has "Part Label" filled in, then display it in an uneditable column, rather than breaking the height of the line as it is done now.
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/f13a81eb-13dd-41ea-98f6-bbad1b5a38a3)

**Comment by adammertel** [comment]
@davidzbiral do you think that showing the "Part label" in the value tooltip + showing it as a placeholder of suggested (when no entity is assigned) would be enough here?

**Comment by davidzbiral** [comment]
@adammertel Yes, good solution. By placeholder, you mean that in the empty suggester, there would be this as gray text? Yes, that's fine, good solution.
