### ISSUE TITLE
References: Build links to external resources and display them in Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1936]
Priority because we are having a hackathon on this and this would help.
If a Resource has Base URL, and an entity has a Reference to that Resource with a Part filled in with a Value, then build the link as "Base URL + this Value", and show it in a clickable way in the Detail, at the side of that reference. The link will be labeled "external link", and will appear between Part and the action buttons.
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/67578a52-b757-4692-b857-8f6c8d9f9df9)

**Comment by davidzbiral** [comment]
@Ptrhnk thanks for implementing, seems done in the main deploy even?

**Comment by Ptrhnk** [comment]
@davidzbiral it was there but not working properly so I resolved the bug - when missing "/" at the end of link, it didn't build the link correctly
