### ISSUE TITLE
References: add "copy value" button

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1937]
In Detail under References, add a 3rd action button next to Delete: icon = copy, mouseover = "copy value". This will copy the `label` of the V part of the tuple in the system's clipboard.
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/359fcb08-542c-4a66-8935-d20f82221968)

Perhaps do together with #1936.

**Comment by Ptrhnk** [comment]
@davidzbiral We decided to make every tag label copyable by clicking if not double clicked
