### ISSUE TITLE
Validation: label language missing, PoS missing

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1952]
Add new validations of entities:
- "label language missing"; and
- "part of speech missing".

**Comment by jancimertel** [comment]
added validations

**Comment by Ptrhnk** [comment]
@davidzbiral 
So it shouldn't be possible to choose empty (-) language in dropdown or is it when the empty (or any language) is missing?
Is this for import data or should it be shown as warning somewhere?

**Comment by davidzbiral** [comment]
@Ptrhnk I don't quite understand the question " Is this for import data or should it be shown as warning somewhere?" It is for InkVisitor behaviour, not for data import. The warning should be shown in the same way as other validation warnings in Detail, e.g. of Actions: such as "Superclass missing". 
Language "-" should be removed from the select. (It makes sense only in some V entities, such as numerical values "3" which has no language, but V entities you don't normally open in Detail, and rather than introducing special behaviour for V entities, we can easily live with the language warning displayed in the Detail of V entitites).
Of course, part of speech only As and Cs have, and in As, "verb" is fixed and nothing else can be chosen (i.e. in Actions, part of speech [PoS] is display only).

**Comment by adammertel** [comment]
I understand that the "-" in the select should be replaced by "empty" (we count these two options same :) ).

**Comment by davidzbiral** [comment]
Yes, "empty", and it should be invalid, i.e. trigger a validation msg.

**Comment by adammertel** [comment]
Just to clarify, invalid in sense of warning - not impossible.

**Comment by davidzbiral** [comment]
Yes, invalid in the sense of triggering validation warning.

**Comment by jancimertel** [comment]
added warnings on backend
