### ISSUE TITLE
T-based validation - new warnings

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1976]
Add warnings defined in the warnings document regarding the Territory protocols

![image](https://github.com/DISSINET/InkVisitor/assets/12932677/fe016379-2e05-4461-ab6a-c833a50ee0a4)

main issue #1924

**Comment by adammertel** [comment]
Postponed, waiting for clarification in https://github.com/DISSINET/InkVisitor/issues/1924

**Comment by davidzbiral** [comment]
@adammertel I commented in the gdoc. There is at least one misunderstanding.

**Comment by davidzbiral** [comment]
@adammertel , I think the notifications you proposed are too specific and do not catch all situations. I think my table captures all the situations, but shows that we need to capture three situations:
1. required tie missing
2. required tie present but with invalid value
3. unrequired property is present, but once present, it needs to meet a list of values.
I am afraid that I was not yet able to express enough that we also need No. 3.

**Comment by adammertel** [comment]
@davidzbiral I have put some comments in the document and on your Slack. I do not agree with all your suggestions.

**Comment by davidzbiral** [comment]
Discussed on Slack.
