### ISSUE TITLE
Add new attributes to the document model 

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1981]
A new attributes will be associated in the document model, all of them will be text fields and presented as a text input under the linked R detail.

Non-main text removal
Editorial brackets removal
Dehyphenation
Text cleaning note
Character Error Rate estimate
Character Error Rate measurment
Character Error Rate note

**Comment by davidzbiral** [comment]
The corresponding issue was closed today - we will not implement. See #1932 for reasons.
