### ISSUE TITLE
T-based validation rules - extend T model

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#1985]

**Comment by davidzbiral** [comment]
As seen in #1924, some concern also root, i.e. global settings for the whole deploy (ACL: only owner can do this global settings).

**Comment by adammertel** [comment]
My idea is that the global settings would be stored in the root T as its not changing and the same interface could be used within all T models consistently.

**Comment by adammertel** [comment]
@jancimertel could you please integrate the T extension (see [packages/shared/types/territory.ts](https://github.com/DISSINET/InkVisitor/commit/e3b4789bba5472c89172e612093acb7190c5c280#diff-049855f08f298bd1db75b6af0e64e8f9bcbbef582e9c954bd2d39feef869f05d))on the Backend? No special logic is needed here.

**Comment by davidzbiral** [comment]
@adammertel : I agree, storing the global settings in the root T is an ideal solution. The only difference would be access rights, i.e. that for root T, only owner can edit the Validation rules.
