### ISSUE TITLE
Remove "no document assigned" notification

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#1986]
Remove "no document assigned" button and notification, it is not useful, and in many ways misleading (because not every R should have a full text).
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/bb1c68db-ce3d-4435-95a0-5f5deaf8b958)

**Comment by adammertel** [comment]
We will be rewriting this UI most probably as the referencing in document fulltext will work a different way (no reference link needed for having an anchor in document). So yes, this will be removed.
