### ISSUE TITLE
Add part of speech to entity tooltip

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2011]
Add part of speech (if filled in) in the entity tooltip - in the parentheses after language, e.g.:
"evil (English, noun)".
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/b942ec6a-dec7-4fb0-8526-d8e88ffa4550)

(Terminology: is this mouseover called tooltip?)

**Comment by Ptrhnk** [comment]
@davidzbiral yes, we call it tooltip, entity tooltip is precise name for the ones from entity tags

**Comment by davidzbiral** [comment]
@Ptrhnk Thanks for implementing, how do you show missing part of speech (PoS) in the tooltip? Simply without, i.e. for instance "heresy (English)", is probably the best? (There is a different place to signal missing PoS.)

**Comment by Ptrhnk** [comment]
@davidzbiral Yes, exactly. Also when concept PoS is "empty", there's just language right now - it's the same as you quoted. Is that OK?

**Comment by davidzbiral** [comment]
@Ptrhnk Yes, that's ok!
