### ISSUE TITLE
Bug fixes before 1.4.0 2nd part

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#2020]
Read mode
- [x] disable editing of relation identification prop
- [x] read mode - Disable unlink button for synonym
- [x] read references loosing consistency for long labels

Fixes
- [x] min length of username in manage users, validate existing

**Comment by davidzbiral** [comment]
@Ptrhnk, @adammertel  We are now really rushing towards having the core functionalities of 1.4.0, so consider whether all of this is needed now, or can be moved to 1.4.1.
