### ISSUE TITLE
Notification when app changes elvl of proptype at the background

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2024]
In relation to #1707: Because 1707 is changing data at the bacground, on principle the user should be notified about this change.
=> add notification "Epistemic level of property type [entity tag of proptype] changed to 'inferential' based on user's default language ([paste user's deflt language here])."

**Comment by adammertel** [comment]
Already implemented (?)

**Comment by davidzbiral** [comment]
@adammertel Is it? The change of elvl is implemented, but the notification we haven't seen yesterday when working.

**Comment by adammertel** [comment]
We saw it yesterday. I will recheck it, but I recall doing it somewhen in the past.
