### ISSUE TITLE
Can't save user customization

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#2037]
@jancimertel check this please - it's about resaving the same user
PUT users/{id}
<img width="432" alt="Screenshot 2024-04-19 at 11 42 45" src="https://github.com/DISSINET/InkVisitor/assets/29732281/887b9d0e-e408-4a35-b521-25b8e158ec2e">

{"result":false,"error":"UserNotUnique","message":"email is in use"}

**Comment by jancimertel** [comment]
done in 5b76e369e1be4dd87e97a45bb7d1c2d9faff6c70
