### ISSUE TITLE
Not possible to delete T with editor write rights

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#2039]
403 forbidden

DELETE
entities/{ID}

**Comment by davidzbiral** [comment]
@Ptrhnk What do you mean? Unclear. It should be possible and isn't, shouldn't be possible and is possible?

**Comment by Ptrhnk** [comment]
@davidzbiral That was server communication problem, not design. That's why the description talks about api.

**Comment by adammertel** [comment]
There is a condition that T cannot be deleted while having some subT or S entities. Is this relevant to the original issue/question?

**Comment by jancimertel** [comment]
T removal has been restricted to admins only.
Currently prepared version which allows removal with Edit (write) rights also.
