### ISSUE TITLE
Make Territory tree box resizable

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2050]
Territory tree box stopped to be resizable. Not high priority, i.e. does not prevent us from working, but quite inconvenient on smaller screens.

**Comment by Ptrhnk** [comment]
@davidzbiral  it never was

**Comment by adammertel** [comment]
I have edited the name of the issue - should not be a problem to implement this even this was never part of the application.

**Comment by davidzbiral** [comment]
@adammertel OK, it somehow feels smaller. I thus change it into a feature request: make it resizable. Thanks!

**Comment by Ptrhnk** [comment]
@davidzbiral It could feel smaller because of adding the root T so everything has one lvl more indentation.
Ok I'm gonna implement that.

**Comment by davidzbiral** [comment]
@Ptrhnk I think that's it, you found the reason for the feeling of the panel being smaller!

**Comment by adammertel** [comment]
Moving to 1.4.1 as this might take more time to implement.

**Comment by davidzbiral** [comment]
@Ptrhnk This is implemented somehow? I know you moved it as far as 1.5 in #2560, but by closing #2050 you imply that some partial solution was found...? It is a little uncomfortable that the resize is not available, we don't see, on 13'' laptops, more than the first, and even incomplete, word, which will not feel to users as a working solution without the resize. It just feels unfinished and quite inconvenient.

![Image](https://github.com/user-attachments/assets/a4a3ff3c-b0a5-4534-b63e-1282a525d99d)

**Comment by Ptrhnk** [comment]
@davidzbiral It was implemented and planned to release in version 1.5 but I can move that to the current release.

**Comment by davidzbiral** [comment]
@Ptrhnk If you can, please move it, because we will have external users and they will be:
1. less patient with GUI inconveniences;
2. using 13'' screens more.
Of course let's do all resizes at a time, not just T tree, but all panels.
