### ISSUE TITLE
Add "main" to menu

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2052]
Alongside the other options, the first could be "main", if it makes sense from the design point of view. While one can click on the InkVisitor graphical header to return to the main screen, not everybody knows this, and some people are used to see also home page link in the menu still, and some go to the same spot where they got to a special screen to search for ways to return to the main window.
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/6e2e0a43-d948-4f97-9dfd-75352d255077)

**Comment by adammertel** [comment]
@davidzbiral maybe "Data collection" instead of "main"?

**Comment by davidzbiral** [comment]
@adammertel I think "main" works better. There are viewers only, who will collect no data, etc. It is much clearer what I can expect if I see "main". Or you can use "home", if you prefer.

**Comment by adammertel** [comment]
... because we are planning to add more pages for 1.5.x, mainly the data visualization and advanced search page, so "main" could be a bit unspecific then.

**Comment by davidzbiral** [comment]
@adammertel I see. With this explanation, "Data collection" makes sense.
BTW no reason I think to have Manage Users with capital U - regularize. Data collection, Manage users.

**Comment by adammertel** [comment]
For the consistency, maybe we should show all pages, even the active page, just highlight the item in the menu so it is visible where the user currently is located.
