### ISSUE TITLE
"Show/hide ordering table" customization: remove this choice

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2053]
If by ordering is meant the order of elements in a statement, e.g. what comes first, what then, then remove this from the menu. Because the order feature is deprecated - superseded by adding entity anchors in the full text and parsing the order from that.
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/8e628713-7e71-44d9-b74e-b587c972a19f)

**Comment by adammertel** [comment]
@davidzbiral what about those users not using text annotation who, for some reason, care about the order of elements in the statement? Are there no such people at all?

**Comment by davidzbiral** [comment]
@davidzbiral When somebody requests it, we can implement, for now the function is really deprecated and I do not recommend this solution. I will be pushing users to have full-texts and annotate them, they will get more valuable data.

**Comment by Ptrhnk** [comment]
@jancimertel also needs to be removed on BE - elementsOrders in statement object
