### ISSUE TITLE
When selecting a Territory in the Tree and Annotator is opened or I open it, scroll to the anchor in the full-text

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2055]
When the users selectts a Territory in the Territory tree (e.g. a subT) and the Annotator is already opened or the user opens it, scroll to the anchor of that territory.

**Comment by rljshaw** [comment]
A priority from my perspective too

**Comment by davidzbiral** [comment]
This will also solve reload of window (often needed), because already now after reload, the correct subT is unfolded where I was working.

**Comment by adammertel** [comment]
Created issue #2100 which is a precondition to this.
