### ISSUE TITLE
After full-text save, don't scroll to start but remain where I was

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2056]
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/05f1a742-e023-4312-a8a9-63682be360a0)
I suggest this is solved by solving this: #2055. If #2055 is solved, this one is not needed (at least at this point).

**Comment by adammertel** [comment]
Yes, this should be related to #2025. #2100 is a precondition here.

**Comment by adammertel** [comment]
Duplicated to #2195
