### ISSUE TITLE
Unexpected disappearance of anchors

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2069]
We were working on anchoring ca. 5 statements, and found the statement anchors disappeared in the raw version. I doubt that we removed them by any delete operation in the full-text, they are too many, so it must be an error of the annotator.
Unless (talk to Robert) they are there but fail to be displayed: clarify with Robert his comment in #2062.

**Comment by rljshaw** [comment]
I have found my anchors in edit mode now, so my issue mentioned above was not a problem and not part of this still active issue

**Comment by davidzbiral** [comment]
Adam reports reimport of Bologna that afternoon ==> it might be the explanation of the issue. If no other issue with disappearance of anchors is found, close the issue.

**Comment by davidzbiral** [comment]
@adammertel I have proof from my Guglielmites work this morning that this really happens with statement anchors, so it was not due to the exchange of Bologna full-text.

**Comment by davidzbiral** [comment]
Also, I know that I added 5+ statement anchors in Guglielmites, and 3+ in Bologna, but there are none.
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/487a161c-79c9-4933-9c31-4b224b00837a)
