### ISSUE TITLE
When creating SubTs via annotator, no anchor is created

### ISSUE THREAD

**Issue by rljshaw** [DISSINET/InkVisitor#2072]
When I am trying to make new SubTs via the button in annotator, the new subT is created but not actually anchored to the text I selected. Currently I have to go back and do this manually. Not sure if it is the same for Statement creation (I have not been experimenting with statement anchoring), but certainly for SubT creation functionality in annotator it is a key bug it seems (unless I am somehow doing it wrong!)

**Comment by adammertel** [comment]
@rljshaw Did you save the document after the changes? It may not be the best user experience to save it after each change so we might integrate some automatic saving?
![subt-creation-save](https://github.com/DISSINET/InkVisitor/assets/12932677/013bd8f7-e9d3-4302-af6a-fda4dde71a78)

**Comment by davidzbiral** [comment]
@adammertel this seems fixed, but first @rljshaw to check. Now there is a prompt to save after anchor creation.

**Comment by rljshaw** [comment]
Seems working, thanks for the guidance!
