### ISSUE TITLE
Territory-based validation: specify warning more

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2077]
I have this rule defined in root:
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/a4b8f18c-d549-49a1-a56d-36f0b7faccc5)
This is the warning I get:
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/304d65bb-541e-40e6-9b6e-5acec89fc715)
Make the warning more specific, as for metaprops - i.e. mention to what R the reference must lead. I.e. it should read: "[A receptatus/a] is not referenced to [R Lila Lemma Collection]", wich the R represented as clickable entity tag.

EDIT: I see, this is an artifact of the design of this as a multiple-value. But if I formulate such a rule for REF, it means the R is required, not an OR logic. So for this situation, I want to impose that a metaprop (of any propvalue) or a ref to a R (of any "refvalue") exists. We could introduce AND/OR logic in the validation rule settings, but for now I suggest that only one Resource, not a multiple. I.e. I want to impose that "metaprop sex exists" or "every L is referenced to GeoNames" - in these things, a field accepting multiples is undesirable.

**Comment by adammertel** [comment]
@davidzbiral I suggest creating a new issue for introducing the AND/OR logic - lets keep this one inside the scope of the specifics for the Reference rules warning text.

**Comment by davidzbiral** [comment]
@adammertel At this stage, I don't want to introduce the AND/OR logic, but only drop the field accepting multiples. See the original issue on the explanation what the problem is. If this is implemented, you can close without creating a new issue.
