### ISSUE TITLE
Unfilled actant 2 valency should trigger warning

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2085]
This situation should trigger the warning "Entity type not filled in for all valencies" - it seems the warning works for actant 1, but not for actant 2. It should also check actant 2. (Tested today - actant1 entity type valency does not pass without explicit "Empty" value, but actant2 entity type valency does.)
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/86d224fa-acf6-4131-af69-cc7019c2f0e5)

**Comment by adammertel** [comment]
@davidzbiral 
Could you please recheck if this is really still valid?
![image](https://github.com/DISSINET/InkVisitor/assets/12932677/eed2d994-4710-43d4-b31f-8f9d0f9100de)

**Comment by davidzbiral** [comment]
@adammertel Checked and seems fixed, you can close.
