### ISSUE TITLE
Better solution of action buttons in statements list

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2090]
The icons are kinda clumsy and often lose focus, i.e. disappear before users succeed in clicking on them. Needs to be tested under different window zoom sizes etc. and make it as convenient as possible.
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/a2df70af-7e34-441b-b48c-39ca1b7a40c5)

This might be a good task for @Ptrhnk if nothing specific on Annotator etc. is at hand - up to @adammertel of course.

**Comment by Ptrhnk** [comment]
Dev note for me: implement with floating UI, the same also could be for context menu in tree
