### ISSUE TITLE
Move delete button to the right

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2095]
In Editor, the delete button, often used, is on the left. Put it to the right, even after the cogwheel. If you dislike "breaking off" - by the delete button - the cogwheel from the attributes it unfolds, then at least make delete the second from the right, and separated by space, to highlight it more and make it more accessible.
But I actually think it should be on the right, the cogwheel separated from what it unfolds is not a problem, and used less than delete I think.

[Approved by all H4](https://dissinet.slack.com/archives/C01CWE6JKUJ/p1714138994076759).
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/871eae06-b4c3-4fa2-8eac-9306edd0bb90)

**Comment by adammertel** [comment]
@Ptrhnk probably, move it to the most-right position and color it red to create a contrast. Also maybe all the icons might be the same size (the cog can be with a dark blue background).

**Comment by davidzbiral** [comment]
@Ptrhnk Red is too intrusive.
