### ISSUE TITLE
Show new empty reference and prop in detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2096]
If this does not imply creating empty props and refs - which should not be in the database, i.e. if it can be handled only at the FE without affecting the db, please make adding meta refs and meta props easier by displaying a first empty set of suggester fields, so that the user spares the clicking on "+ new metaproperty" and "+ new reference", and can rather start filling in directly. In such a case, deriving from other places in the db, probably a new double field should appear if one is filled in.
If it is a bad idea, I can easily live with current solution. Just trying to use all opportunities of saving time to coders.

![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/688423b8-8847-43a6-a557-6770f49ec541)

**Comment by adammertel** [comment]
@Ptrhnk could you investigate if this is realistic? So when no reference / metaprop is stored, we would mimic an interface for a completely empty item which is directly saved after any edit... But as David said, not a priority.

**Comment by davidzbiral** [comment]
It is done this way in some places of the app - but probably not in refs an metaprops, it is true. 
If implemented, should also be implementet in Editor for Refs:
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/40f4e655-f4c3-4e05-9644-da4b308327fd)

**Comment by Ptrhnk** [comment]
@davidzbiral @adammertel 
I can imagine always having one spare row.. something like the suggester in Tags here on the image, once confirmed, there's always a new one

**Comment by davidzbiral** [comment]
Yes, that's it - design-wise, probably quite simple, only we want to avoid storing this empty thing on the database.
