### ISSUE TITLE
New batch operations on the statement list: "relate to SOE", "classify"

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2097]
Rationale:
Statements can be composed into Events. In fact, any statement which denotes action is a micro-Event on its own. For example WW2 or a dinner can be described in 1-N statements, and all of them can belong to the broader Event of WW2 or "this dinner". 

Feature request:
To the batch operations on statement list, add the following two:
1) "relate to superordinate event". This will be similar to "replace R", i.e. a suggester accepting only Events and suggesting only Events will appear, and user will be able to relate all selected statements to this event. 
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/81334250-6360-4637-a7b0-2f4b3910e3e2) This will create, between each of the statements and the target Event, the SOE relation. I.e. each of these statements - SOE - E the selected event.
2) "classify as". This will make a Concept-only suggester appear, where I can put a C and thus add a meta CLA relation to them towards this Concept (of course, only to those which don't yet have it - but I guess one cannot add one twice anyway, so this is already taken care for). Typical use: batch classification into trial/non-trial statements.

Notes:
@katalinsuba in the Consolamentum project will know what I am talking about.

**Comment by davidzbiral** [comment]
While implementing, probably do also this minor label change: #2098.

**Comment by adammertel** [comment]
@Ptrhnk this would involve a modal window, the header would be the same as the option label and the footer would involve "confirm" and "cancel" buttons. Let us know if you need a new API call for this.

**Comment by davidzbiral** [comment]
@adammertel Seems you want to look at it more quickly than for 1.5 - ok, then please put in a correct milestone where you want it.

**Comment by davidzbiral** [comment]
@adammertel I actually need this quite early on, moving.

**Comment by davidzbiral** [comment]
Chane label: not superordinate event, but superordinate entity!
