### ISSUE TITLE
Annotator `scrollToAnchor` api method 

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#2100]
The annotator API would need `scrollToAnchor` method which takes `entityId` and scrolls to the canvas to the position. If there is no anchor with the given `entityId`, the method does not do anything.
Additionally to the `entityId`, this method would accept a second parameter `occurrence` (default 0), which defines what occurrence it needs scrolling to - this will be important to searching through multiple anchors with the same entityId.

**Comment by davidzbiral** [comment]
Does not yet seem to work on the FE.

**Comment by adammertel** [comment]
Not yet, needs to be integrated on the frontend
