### ISSUE TITLE
Add batch remove action for selected statements in T

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#2135]
A new option in the batch actions menu in S list. This action should be confirmed by a modal prompt.

This is motivated by #1588

**Comment by jancimertel** [comment]
implemented as multiple calls to _delete one_

**Comment by davidzbiral** [comment]
@adammertel So this is done, and could be closed?
(Motivated not only by #1588, but also other things.)

**Comment by Ptrhnk** [comment]
@davidzbiral No I'm still working on the client side, but it's gonna be finished in upcoming days
