### ISSUE TITLE
Anchors can be even on parts of words

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2141]
I wrote somewhere that anchors cannot break words and you should control against it. I cannot find it now, so at least create this issue to say that this is _not_ true. **Adding anchors within words should be possible.**
Because when dealing with digital editions and e.g. adding a markup for subRs (sic), in the sense of subordinate entities of an R, then we need this because some page or folio breaks are within words. E.g. the markup in an edition visible in the screenshot should result in actually putting an anchor inside a word. 
Related to:
#2140 
#2129 
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/7fbe7bf1-44ec-465d-a861-bf79a3bccc36)

**Comment by davidzbiral** [comment]
Linked to #2116.

**Comment by adammertel** [comment]
This is already the part of the implementation / nothing limits you from anchoring parts of the words
