### ISSUE TITLE
Fix DnD of entity tag from Detail tab header in Firefox

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2145]
If I drag and drop in the area of tabs, keep current behaviour - i.e. use for changing tab order in Detail. But when DnD to a suggester, use as norman DnD of the entity tag. I see no conflict there, i.e. the DnD goal can be evaluated based on whether the user remains in the tabs area, or goes somewhere else.

Why: because we often need to DnD one opened tab's entity into a different tab's metaprops or other fields.

![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/9ac19008-cdfe-44f7-806e-a7a8cf850b44)

**Comment by Ptrhnk** [comment]
@davidzbiral 
It works right now with this magic icon.)
https://github.com/DISSINET/InkVisitor/assets/29732281/91bc34c8-d553-429c-be93-0360d7cbd9da

**Comment by Ptrhnk** [comment]
@davidzbiral 
It works right now with this magic icon.)


https://github.com/DISSINET/InkVisitor/assets/29732281/471c93c5-f2c1-4632-b165-4f43c3df9c80

**Comment by davidzbiral** [comment]
@Ptrhnk In what version? Does not work for DnD into Detail metaprops in mine (v. 1.4.0b | built: Wed 01.05.2024 17:36).

**Comment by Ptrhnk** [comment]
@davidzbiral do you click on the move icon in the tab?

**Comment by davidzbiral** [comment]
Yes, sure. Single click, then DnD.

**Comment by Ptrhnk** [comment]
@davidzbiral yes please

**Comment by Ptrhnk** [comment]
https://github.com/DISSINET/InkVisitor/assets/29732281/26238f7b-1c10-4049-9ee6-e2a952c0a7dc

**Comment by davidzbiral** [comment]
I saw this video, no worries. 
Here's mine. Simply does not work.
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/600d216a-b025-4cc6-b70f-27cda07ac4f1)

**Comment by davidzbiral** [comment]
![dnd-from-detail-header-does-not-work](https://github.com/DISSINET/InkVisitor/assets/55400794/7bd44929-6d6a-45bb-a0dc-4fcf3390b119)

**Comment by Ptrhnk** [comment]
@davidzbiral Ok I see it now, it doesn't work in firefox. Thanks, I'm gonna look into that.

**Comment by davidzbiral** [comment]
@Ptrhnk Yes, Firefox, always.

**Comment by adammertel** [comment]
@davidzbiral 
I discussed this with @Ptrhnk and we came to the conclusion that this is quite a specific and edge-case relevant for FF that could take a lot of time to dig into. 
I am closing this, as the functionality is easy to mimic by clicking the resize icon, which shows the entity tag that is then draggable.
![dragging-ff](https://github.com/DISSINET/InkVisitor/assets/12932677/7ba06515-f833-4faf-9667-e70f3537ab6e)

**Comment by davidzbiral** [comment]
@adammertel I will probably remember, but it is quite unintuitive to DnD after click (i.e. click and release), so I doubt a normal user will find this functionality.
