### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#2181]
Inspect the situation when the inactivated user cannot pass the login page even though the toast says they are signed in. 

![image](https://github.com/DISSINET/InkVisitor/assets/12932677/03a7e53b-4d5a-428e-b584-fc2f1cdaab03)

**Comment by adammertel** [comment]
Might have been fixed by changes in #2133, where we disabled the password re-creation when the user is not verified yet

**Comment by davidzbiral** [comment]
@adammertel Sounds like a solution - so how about you test this and then close?

**Comment by adammertel** [comment]
@Ptrhnk when you have time, could you please recheck the user story for registration, activation, and log in to check if you can reproduce this behavior after the last changes we made, and close this issue?

**Comment by Ptrhnk** [comment]
The question was "inactivated user cannot pass the login page even though the toast says they are signed in"
Now it says user is not active and log in is not allowed which seem correct to me.
I've also tested the verification and activation / deactivation.

**Comment by davidzbiral** [comment]
@Ptrhnk I think the issue was about a user "not yet activated" rather than set inactive, but we can put the matter to rest because it is not described enough.

**Comment by Ptrhnk** [comment]
@davidzbiral Inactivated doesn't even have password so it shouldn't be possible to even click on the log in. When I write some random password it says that user is not activated so I think it's solved if this is the exact case.
