### ISSUE TITLE
Until anchor removal and move is possible otherwise, re-allow it in XML

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2198]
Yes, I did say that I don't want textual anchor removal and adding in the xml mode or anywhere else, but there is a misunderstanding - we need to have at least some access to anchor removal until #2071 is implemented. So unless #2071 happens very quickly (which is what I suggest), you need to asap reenable anchor removal and move through the XML mode through deleting and copy-pasting the anchor.
Currently there seems to be no way of removing or moving an incorrect / incorrectly placed anchor.

**Comment by adammertel** [comment]
You should be able to remove the anchors in the XML mode. 
Also, we make sure #2071 is shipped as fast as possible.

**Comment by davidzbiral** [comment]
OK, closing.
