### ISSUE TITLE
Include annotator/statement list mode choice in the URL, so that URL opens a similar view

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2199]
Include annotator/statement list mode choice in the URL, so that URL can serve to share a similar view between users (unless it is a bad idea, e.g. because making URL too long or because it is not such a stable option as the entity UUIDs to open in Detail etc).

**Comment by adammertel** [comment]
No, this is realistic and not that complicated to implement

**Comment by Ptrhnk** [comment]
That's a good idea
