### ISSUE TITLE
Avoid adding extra whitespace characters around anchors

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2204]
It seems that adding statement anchors sometimes adds an extra whitespace which should not be there (screenshot, before Interrogatus; I am almost sure I did not add it manually). Can you please check whether this is not happening, and if it is, avoid that behaviour?

![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/0edcfe94-9b04-42b5-b3d4-4baa839dd14a)

**Comment by jancimertel** [comment]
few whitespace chars on the left side (before the anchor tag) - is this part of the issue?

**Comment by davidzbiral** [comment]
@jancimertel The chars before the anchor tag are _not_ part of the issue, because they are in the original. Adding anchors should leave the full text as it is now.
But perhaps this issue might be due to the uncertainty of text selection in current annotator, described elsewhere. Needs your testing.

**Comment by jancimertel** [comment]
Tested it in various scenarios, there should not be any functionality that adds new whitespace character anywhere during the anchor-adding operation.

However i noticed situation which causes the selected area to select also the newline character (\n) which could push one blank space to the anchored area. Fixed & closing this issue for now.
