### ISSUE TITLE
Annotator text is recreated into a different form after a selection is made

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#2207]
![text-moving-with-selection](https://github.com/DISSINET/InkVisitor/assets/12932677/a25b581b-dda5-47ee-b6b7-762edefe1c60)

Text position is sometimes moved after a specific selection is made.

**Comment by jancimertel** [comment]
it is caused by resizing the container. cursor stays the same but text is recomputed to fit the new size.
