### ISSUE TITLE
Copy (append/replace) validation rules to another T

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2217]
Validation rules are inherited from parents, so no point copying them from parent to child, but often, you have a set of rules that you have on one sub-root T and want to also use them for another T also. Thus, conveniently copying them is the way to go.

Allow copying them through a suggester which will accept T entities only. This will copy the rules from the T that you drag&drop in the suggester or find through the suggester. Allow, as usual in these suggester-based operations, two modes: append / replace, using the same switch and icons as elsewhere in these cases.

**Comment by adammertel** [comment]
![image](https://github.com/DISSINET/InkVisitor/assets/12932677/f0e7f4df-7afd-4084-bdb9-3129a16cb8bb)
The same UX would be applied to the Territory validation rules, just instead of S -> T in suggester and no "previous S" button
