### ISSUE TITLE
Missing entity type valency does not trigger warning

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2220]
This situation should trigger missing valency warning for actant1 and actant2, but does not (see screenshot - no warning displayed). All entity type valency slots must be filled in, at least with "Empty".

![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/33fc353f-7dd5-4e59-a9cc-b928bd0259f8)

**Comment by adammertel** [comment]
Seems to be perfectly working for me, here is a printscreen from the production instance. 
The warning is displayed whenever I remove the "empty" Entity type for any Actant position.
![image](https://github.com/user-attachments/assets/a868c447-621c-4a9d-8440-5aa4ee7d3f01)

**Comment by adammertel** [comment]
Closing now, feel free to open again if the situation occurs again
