### ISSUE TITLE
Important bug in superclasses

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2228]
Important bug found in superclasses, I never encountered it before. Remains even after page reload.
I am editing these two entities: [1](https://dissinet.cz/apps/inkvisitor#selectedDetail=138dc5a9-72fe-4e7e-a43a-4421f00512f3&detail=138dc5a9-72fe-4e7e-a43a-4421f00512f3), [2](https://dissinet.cz/apps/inkvisitor#selectedDetail=c8ac5c8d-c872-4867-b1a0-d057875ab779&detail=c8ac5c8d-c872-4867-b1a0-d057875ab779), which have SYN relation between them. But for some reason their superclasses seem to be edited by the app, or displayed badly, in such a way that some or all appear twice based on having added them in the other one (the synonym) - as if the app was taking them from the synonym and thus duplicating them. So far, I think, we requested no symmetrization of the SCL of synonyms, only warning that SCL of synonyms is inconsistent. So I do not know what to think about this behaviour, and whether the data structure is not in danger.

Interestingly, over these incorrect duplicates, mouseover shows nothing, while for one set which correctly belongs there, the mouseover works just as always.

![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/a9a6d6ed-91bf-4213-ab30-3da413050219)

**Comment by adammertel** [comment]
Seems that identical relations are returned in this case. Just to make sure - when one of them is removed, are the duplicate removed as well? If yes, there should be no danger and the fix should be quite simple.

**Comment by davidzbiral** [comment]
@adammertel This morning it was fine, i.e. only 2 SCL were under both particeps and member, and I also tried removing and adding under one, and no misbehaviour was observed. Can it thus be that it was a bug in some slow or misguided communication between app and server?

**Comment by jancimertel** [comment]
no duplicates coming from backend/not rendered in ui now.
