### ISSUE TITLE
Statement list width & vertical bar problem

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2229]
On some settings now the vertical bar does not show:
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/15acae25-9f6f-4382-828d-23da8ef47ee4)

On other settings, it shows, but the function buttons of the statement list are partly hidden:
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/c99f3018-f5d5-423a-8901-2765f5e487a8)

**Comment by adammertel** [comment]
This is more a problem of the list not getting the full with of the box @Ptrhnk
