### ISSUE TITLE
import script: importing full database ends with error "Nesting depth limit exceeded."

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#2262]
When I try to use import.ts script to import full db (e.g. dataset folder contains dumped db from production), I get an error 

![image](https://github.com/user-attachments/assets/dba25adf-35bb-4124-9ed9-4ca7eea620de)
(It happens around 70% of entities import)

Does this mean that production db contains an error ("You probably have a circular reference somewhere.") or could it be that there is some bug in the import script or a quirk which appears if the dataset is really big?

**Broader Context**: I tried to use import.ts to import the result of the "transplanted dataset", and I got the error. So I tried to import unmodified dump to ensure problem is in my modified data.

**Comment by adammertel** [comment]
I think this might be an error in the imported data. One quick option to debug and find the problematic place is to try importing the `entities` list by small batches. If needed, I can take a look and assist here.

**Comment by tomaham** [comment]
So, in your opinion, does this mean that the production DB contains such 
an error?
(This could be a problem with the first import batch - it went through 
an old version of import.ts.)

Cool, take look,  I would be slow in altering the typescript import.ts.

------ Original Message ------
From "Adam Mertel" ***@***.***>
To "DISSINET/InkVisitor" ***@***.***>
Cc "tomas.hampejs" ***@***.***>; "Assign" 
***@***.***>
Date 8/11/2024 8:57:39 PM
Subject Re: [DISSINET/InkVisitor] import script: importing full database 
ends with error "Nesting depth limit exceeded." (Issue #2262)

**Comment by adammertel** [comment]
The problem is that some entities got stored on DB with the `entities` attribute. If possible, please remove the attribute from the entities objects in your dump. We will remove them directly from DB and make sure that are not stored again.

![image](https://github.com/user-attachments/assets/2560c0e1-c153-4b38-9dfc-86b690db158a)

I have created #2267 to adress this issue.

**Comment by tomaham** [comment]
Super cool. I acknowledge the situation, and I close.
