### ISSUE TITLE
After a new deploy, all users need to logout and login

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#2305]

**Comment by adammertel** [comment]
Maybe not an issue anymore - need to be checked

**Comment by jancimertel** [comment]
using build date as suffix to auth secret - maybe another frontend action will be needed

**Comment by jancimertel** [comment]
need to check all api calls - if unauthorized -> needs to be redirected to login

**Comment by jancimertel** [comment]
fixed redirect in d4b133bb17ee3a8e5a89b57edb2bfe4361024d42
