### ISSUE TITLE
Close anchor creation modal upon Esc or click outside of Annotator

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2319]
Now there is no smooth, natural way to abort the operation of creating an anchor. Upon Esc and click outside of the area of annotator, close the anchor creation modal.

![obrazek](https://github.com/user-attachments/assets/54e3dae3-b776-4d90-89cd-1c536cef608f)

**Comment by adammertel** [comment]
I have added the "Escape" key functionality but catching the mouseclick outside of the annotator is a bit tricky while it would disable any interaction while the menu is opened - e.g, dragging any entity tag to the suggested in annotator.

**Comment by davidzbiral** [comment]
@adammertel you are right, only Esc can work. I am fine with this solution, thanks.
