### ISSUE TITLE
Text edit does not work

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2320]
If at the beginning of a line, Enter leads to moving rather than adding a paragraph break. Add paragraph breaks instead.

![annotator-not-editing](https://github.com/user-attachments/assets/5bcc1afa-bb5f-4db1-8ff3-bbd43ec4e40e)

**Comment by jancimertel** [comment]
added in 3df21454166905aa9c91f7ca9d179dfb81e3a55f
