### ISSUE TITLE
Cursor keys still add text instead of moving

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2321]
If I press End, instead of going to end of the line, it edits text, adding the string "End". This is really not what we want.

Observed in Text edit mode.

![obrazek](https://github.com/user-attachments/assets/c2e1b3b8-b51e-4a6c-9f48-fc7a6545c7a0)

**Comment by jancimertel** [comment]
added in 6d92b058a878932d88367bebd1f742af2bb599d3
