### ISSUE TITLE
UUID pasted into the main text while only working in the Highlight mode

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2324]
While only working in the Highlight mode and only dragging existing Statement tags into the create anchor modal, the full text gets distorted by putting anchors into the main text.
Happened to me already 3 times, so it is hardly just my error - seems to be a bug of the app.

![obrazek](https://github.com/user-attachments/assets/3b2dd5a8-f8a9-450b-ae77-0846ff2d0540)

**Comment by adammertel** [comment]
Cannot replicate now, probably fixed by another commit
