### ISSUE TITLE
Prepare InkVisitor for upcoming data publication in a login-free instance

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2336]
We will shortly be publishing Niort data (also) in the form of a read-only InkVisitor & DDB1 instance, without forcing registration and login. Please prepare InkVisitor ACL philosophy and implementation for this use.

**Comment by adammertel** [comment]
Not sure it would be that simple to completely remove the access-control system.
Would it be possible to create an instance with one user with the global reading rights and show the credentials (username + password) in the login modal?

**Comment by davidzbiral** [comment]
@adammertel Not completely seamless, will feel odd to visitors, but it can work at least as a quick solution for sure. So the only change would be that you pre-fill the credentials somehow in that instance (?), and otherwise no change to the app?

**Comment by adammertel** [comment]
We can also change the login modal to a "welcome" modal and hide the input fields. And replace the login button text to something like "enter".

**Comment by davidzbiral** [comment]
@adammertel This could work I think. So can you prepare it, so that we are prepared when we say "let's cut the data out from DDB1 that we want to share here", and we can create the instance swiftly? Let's prepare everything for this.

**Comment by davidzbiral** [comment]
@adammertel We decided that we want to do it with Niort data, could you prepare the app for this use?

**Comment by davidzbiral** [comment]
@adammertel I confirm we want to use it, and we need it by 15 October 2024 for submission.

**Comment by adammertel** [comment]
@davidzbiral may I close this?

**Comment by davidzbiral** [comment]
I think this is done, yes - mostly Robert was controlling this. If he finds something, he will talk back to you. Closing.
