### ISSUE TITLE
Introduce new field 'alternative labels' under all entity types, and include it in searches just as 'label'

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2367]
Introduce a new field under models for all entity types, entitled 'alternative labels', a multiple field which will accept individual strings (one or more words). E.g., we want to create C "democratisation", and put "democratization" in 'alternative labels', and then find C democratisation also when searching for democratization.
In all searches, treat any of the alternative labels as the 'label' (I think you call label 'name' internally in the DB). 
If the user confirms as alternative label the same string as the 'label' or as any already existing alternative label it should _not_ be added (this would create an unnecesary duplicate; message: 'alternative label already exists'). 
The user needs to be able to remove any alternative label later, design-wise probably the same way as you remove an entity class from lists of entity classes.

EDIT: in Detail, they will be just under Label.

More detailed rationale (written esp. for historians):

> C and A Entities are lemma-meaning units. Orthographic variation is not a difference of meaning, and should not matter and should not lead in creating them as new entities (linked as SYN), but is needed for querying. (Such over-burgeoning of entities makes the data quite messy to query and do research on, and in this case, quite unnecessarily.) Thus, I propose to add a new field to all entity types – a multifield, where individual items will be individual orthographic variants.
> (In Persons, editors can, by perfectionism or doubt, decide that P. Fornerii and Petrus Fornerii will be created separately and linked with IDE – this is not necessarily discouraged and is not related to this proposal. This proposal argues that we need to have a way not to create A vocatus and A vochatus as two verbs, and double the work on the action description, but we still want to find find vocatus trough vochatus.
> I don’t care whether some borderline cases will lead to more entities even in C and A, esp. if the variation is so massive as to constitute uncertainty of the same lemma and/or meaning. This will still be possible. My concern is to solve the normal case, where we have becharius, beccarius, becarius… and want to find trough InkVisitor Suggester field the basic variant when searching for any of them.

**Comment by davidzbiral** [comment]
@adammertel Endorsed by H4 and related to upcoming work. I prioritize - but still the working Annotator (user-friendly basic functionalities) is top priority.

**Comment by davidzbiral** [comment]
I guess that this is understood, but by including it in searches, I mean both the Search and, just as importantly, the search through the Suggester field.

**Comment by davidzbiral** [comment]
I edited the name - changing it from "spelling variants" to "alternative labels".

**Comment by jancimertel** [comment]
add labels for entities instead of original label on backend, 
@Ptrhnk check please
