### ISSUE TITLE
Empty entity type valency on actant2 does not trigger warning

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2380]
This situation does not trigger warning of undefined entity type valency for actant2 (only observed in actant2). After I add one and remove, the warning is already triggered, but it should be triggered even when I open an entity which lacks actant2 entity type valency definition. At least 'empty' must be selected. Same rule applies to subject, actant1, and actant2.

Observed cca 20 times these days - it is a systematic bug.

And it is a real issue - I have seen many that other editors than me confirmed, while they had this flaw, i.e. priority to fix.

![obrazek](https://github.com/user-attachments/assets/73487df7-4e24-4273-b011-596b5c0f6b18)

**Comment by adammertel** [comment]
@davidzbiral could you point me to some examples? Because I cannot replicate / cant find any Entity where the warning is incorrectly handled.
![image](https://github.com/user-attachments/assets/4dc6e99b-d7d0-4b31-98da-059866851a48)

**Comment by davidzbiral** [comment]
For example [here](https://dissinet.cz/apps/inkvisitor#selectedDetail=ca82fe85-c408-4d92-8f27-6fd400bf635b&detail=ca82fe85-c408-4d92-8f27-6fd400bf635b). The Actant2 must be filled in, at least with explicit declaration of Empty.
