### ISSUE TITLE
Undo statement and other entity deletion

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#239]
Add the undo function (in the form of "hyperlink") to the notification "Statement removed", which is displayed after removal. 
(The point is not to have a full undo history, but undoing this one removal.)
Related to metaprop and prop removal undo (#649).

**Comment by adammertel** [comment]
@jancimertel  is this possible with the current code structure?

**Comment by davidzbiral** [comment]
@jancimertel : see question above.

**Comment by jancimertel** [comment]
@davidzbiral its possible to add one field / flag, which will indicate removal. Find/search queries will ignore entries with this flag set to true. This is probably the easiest approach currently.

It can be further enhanced by some admin call - purge deleted entries to remove the completely.

**Comment by davidzbiral** [comment]
@jancimertel : I don't like this much because what you describe is a case for status = discouraged. Here we are speaking about real deletion, but having the undo option for e.g. 15 seconds.

**Comment by jancimertel** [comment]
@davidzbiral then there is a possibility to defer the delete action - call it asynchronously after timeout. Such timeout could be cleared before its execution.

**Comment by davidzbiral** [comment]
@jancimertel : this is a good solution I think, let us go forward with this.
