### ISSUE TITLE
Alternative label: save also upon Enter

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#2400]
Thanks for implementing alternative label. Now the user must click on the + button to store it, however. We have been developping the app to also accept keyboard signals, though - this is thus inconsistent.

Please:
1. Also add the alternative label upon simple Enter key when in the input field.
2. Enable jumping to the + button also with Tab, just like it is possible to jump with Tab between control fields in and around Suggesters.
3. There is some slow response of the environment, when the control field of the Suggeter changes appearance to a more basic and non-InkVisitor-like - remove this change.

**Comment by adammertel** [comment]
@davidzbiral we werent able to replicate the 3. point, we are closing this. Feel free to reopen with more information.
