### ISSUE TITLE
Validation of statements upon data entry by actant slot entity type

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#260]
Check whether the actant slot occupied by an allowed entity type (as per definition of the given A type entity in the allowed entity types for that A type.) Includes: is not a required actant slot, i.e. one which does _not allow NULL_, empty? Is not an actant slot requiring only NULL occupied? On this, cf. #684.

The only problem is when to trigger the check.

**Comment by adammertel** [comment]
Here is the documentation 
https://docs.google.com/document/d/1pmsCjNLHAOA58gVrwV64Qfsp-9wO4kZoXbtyjViMuQA/edit

**Comment by jancimertel** [comment]
> 

implementation + tests done according to the docs
