### ISSUE TITLE
Bookmarks - further places to drop entities

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#262]
In bookmarks, entities can currently only be dropped in the Suggester element. But many a folder in Bookmarks is likely to be quite long => a lot of scrolling all the way down to the Suggester element to be able to add any entity. Therefore:
- consider to use the heading with folder name as a further place to drop entities (the entity would then be added as the last in the order, i.e. at the end);
- and consider, besides this improvement, even the possibility to dropping it anywhere, i.e. directly dragging it to the place where one wants to have it among the other entities, not just at the end (in a manner similar to dragging app icons on a mobile phone to the home screen).
I think that in Bookmarks, unlike e.g. actant slots, the logic of dropping should be different and we should not be attached to dropping it in the Suggester element only.

**Comment by Ptrhnk** [comment]
Also handle long labels!
