### ISSUE TITLE
Allow multiple entities at a time in Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#271]
[EDITED 17 Apr 2022]

The Detail box typically shows just one entity. We need to display more entities.

Why:
- Automatic display of a newly created entity in the Detail subwindow clears the Detail box from what the user had there before (and probably wants to have there still).
- Sometimes you need to compare very similar entities (e.g. with the same label) to be able to choose the correct one. Seeing them together in the subwindow would help a lot.

If we decide to implement this feature, then:
- a Clear / close all button will be necessary;
- clearing upon app close is OK, I think;
- if necessary, setting an upper limit of the number of entities in Detail due to slowing down the app (no idea whether this is an issue);
- the new entities will be added on top in the subwindow, pushing the tabs for the previous ones down.

**Comment by davidzbiral** [comment]
I think we decided to implement a tab solution. We must decide how the URL would look like.

**Comment by Ptrhnk** [comment]
@adammertel I think it's good to start with BE => we need to be able to fetch / track more entities at once. Right?

**Comment by Ptrhnk** [comment]
Checklist for me: 

- [ ] rewrite EntityDetailBox to separate EntityDetail component
- [ ] put selected detailId to redux
- [ ] decide if keep state of detailIds in redux or useParamsContext

**Comment by Ptrhnk** [comment]
- [ ] Tabs concept
- [ ] refetching selected detail / fetching all details
