### ISSUE TITLE
Write readme

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#290]
Write readme on GitHub as a preparation for making the dev public by 31 Aug 2021:

1. data model (@davidzbiral)
2. application & its use (@adammertel with contribution from @davidzbiral )
3. deploy (@jancimertel)

Needed by **20 August** (leaving time for proofreading - neat version by 31 Aug 2021).

By that time, try to update the Data collection guidelines into a publishable version.

**Comment by jancimertel** [comment]
Some peaces has been done previously, but i need to check it after latest 1.3.0 changes. I will use Wednesday 27th as a deadline. Sorry about such delay.

**Comment by jancimertel** [comment]
ive updated what i deemed important. i moved parts to package dirs (database/server). @adammertel do you think we can do the same for client package?

**Comment by adammertel** [comment]
Yes, I do not see a reason why not...

**Comment by davidzbiral** [comment]
@jancimertel : Please tell me when you finish, I will have the text proof-read by a native speaker.

**Comment by jancimertel** [comment]
> @jancimertel : Please tell me when you finish, I will have the text proof-read by a native speaker.

its in the #994 and assigned branch

**Comment by adammertel** [comment]
I added a few lines to the client package. But I think, a more serious text needs to be created, so let's discuss this within the next week.

**Comment by davidzbiral** [comment]
@adammertel, @jancimertel: Hum, still pending.

**Comment by jancimertel** [comment]
closing & we should make more specific additions to readme
