### ISSUE TITLE
Model for Territory and Resource

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#321]
What attributes are we collecting about the Territories and Resources? Do they have some specific attributes?

**Comment by davidzbiral** [comment]
What _data_ we attach to highest-level T (whole registers) is best visible in the Sources table (https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=2056508047; card Texts and Resources). But what should be an internal _attribute_ and what should be a _property_ is partly blurry and needs to be decided. I will give it a thought when designing the import.

**Comment by davidzbiral** [comment]
Territory: will have all entity attributes + parent T + order.
Resource: will have all entity attributes + URL.
Other data will be handled as props.

**Comment by adammertel** [comment]
Lets close it for now :)
