### ISSUE TITLE
API - swagger

### ISSUE THREAD

**Issue by jancimertel** [DISSINET/InkVisitor#330]
lets generate online api docs (swagger) so requests are testable by outsiders

**Comment by davidzbiral** [comment]
Please describe this more here (who should have access, and under what ACL conditions?).

**Comment by jancimertel** [comment]
@davidzbiral there was an idea to provide api documentatiion in [swagger tool](https://editor.swagger.io/). Its not required but it could be used to test api calls.

Similarly to postman, you can set access token for tested calls, which will identify the caller. If the calller has permissions to use such endpoints, it will go through. Caller without permissions will receive error. Just like if you attempted to access detail for entity for which you dont have access through inkvisitor app.

**Comment by davidzbiral** [comment]
@jancimertel @adammertel : I do not understand it much even with this explanation :-) In any case, what I need is a better documentation of the app now that we are starting sharing and promoting it. If this is a good step towards my goal, let us do it :-)
