### ISSUE TITLE
Suggester - Working with status = 'discouraged'

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#340]
- tag visualization (diagonal pattern, dashed border, ...)
 - suggested (not including in suggesters)

**Comment by davidzbiral** [comment]
Consider even the visually prominent "wasp" dashed pattern (i.e. yellow & black dash) to signal something is really wrong here...

**Comment by davidzbiral** [comment]
Not including "discouraged" in suggester results is an absolutely crucial feature for the gui.
