### ISSUE TITLE
Add "global replace" function

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#341]
[Added by David:]
To replace one entity, e.g. a discouraged one, by a correct one.
Besides global replace, allow one-by-one replace, with displaying the given statement in the Editor window.

**Comment by davidzbiral** [comment]
- Probably, the way to go is to connect this to `search` function - which will allow the user to see the instances before they perform the replace.
- Probably only admins should have the right to use this function - it is a somewhat risky one if not properly understood.

**Comment by adammertel** [comment]
The new search functionality should cover this functionality
