### ISSUE TITLE
New design for Statements subwindow

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#349]
@davidzbiral would it be possible to have a short call on this week?

**Comment by Ptrhnk** [comment]
- handler na posúvanie statementov v tabulke hore dole (done)
 - Tagy k akciam (v tej skrátenej podobe) aj s tooltipmi
 - Tagy k aktantom (v tej skrátenej podobe) aj s tooltipmi (to je asi done, akurát to spojiť do jedného)
 - text Statementu, zmestí sa pravdepodobne iba nejakých 20-30 slov
 - tlačítko na kontextové menu, podobne ako u T Tree. V ňom by bol insert, duplicate a delete.
 - select S (to už tiež máme :) ) 
 - expand akcia by bola ideálne naviazaná na celý riadok, ale aby sa ten klik nepropagoval keď klikneš niekam inam. Už sme to raz skúšali a moc nám to nešlo - tak by som tomu dal ešte šancu a ak nie, tak vedľa selectu by mohlo byť malé "info" tlačítko

**Comment by davidzbiral** [comment]
In any case, the Edit action should be done by a more intuitive icon, and in the same way as in the Detail subwindow (pencil icon).

**Comment by davidzbiral** [comment]
Further improvements suggested in https://github.com/DISSINET/InkVisitor/issues/360.
