### ISSUE TITLE
Improve Statements subwindow

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#360]
- Replace the label col. "Actants" with label "Objects" (because also the subject is an actant).
- Replace the label col. "Type" with label "Actions", and list the actions of the statement there as one or more red A entity icons.
- Use the “+” icon to add a statement _after_ this one, not _before_ (and update the tooltip text accordingly).
- Unify the jump to editing between Detail and Statements subwindows - use the more intuitive pencil icon for jumping to the editing window.
- List all actants in subject and actant1 and actant2 positions and all actions (as small icons, full label on hover). I.e. stop using "..." for dropping some of them.
- After moving the action icons on hover only, will we have space for displaying part of "text", similarly as in the Detail subwindow? Would be great.

**Comment by Ptrhnk** [comment]
> * Replace the label col. "Actants" with label "Objects" (because also the subject is an actant).
Do you want to merge cols subjects and actants? Because now there is separate col for each of them.
> * Unify the jump to editing between Detail and Statements subwindows - use the more intuitive pencil icon for jumping to the editing window.
Not sure what that means. Detail is opened by double click on tag. Do you want to open detail by pencil instead of double click on actant tag?
> * List all actants in subject and actant1 and actant2 positions and all actions (as small icons, full label on hover). I.e. stop using "..." for dropping some of them.
It depends on number of actants in statement. How to behave when its not possible to fit all of them with other props in the row? Is there some possible highest number of actants in statement?

**Comment by davidzbiral** [comment]
>> Unify the jump to editing between Detail and Statements subwindows - use the more intuitive pencil icon for jumping to the editing window.
> Not sure what that means. Do you want to open detail by pencil instead of double click on actant tag? Or is it anything else?
No. I want that in Statements subwindow, the same Pencil icon is used as in the Detail subwindow (while now, the Edit action in Statements clicking on the circle) because: 1) the same action should be triggered by the same icon (and not by two different icons, one in Detail and another in Statements), and 2) pencil is visually more intuitive to signal editing.
But maybe you will solve the whole-row click, and this would make the icon unnecessary (in both Statements and Detail) - in such a case, consider this suggestion deprecated. (When designing this, mind that I need to implement this as well: https://github.com/DISSINET/InkVisitor/issues/376.)

>>List all actants in subject and actant1 and actant2 positions and all actions (as small icons, full label on hover). I.e. stop using "..." for dropping some of them.
>It depends on number of actants in statement. How to behave when it's not possible to fit all of them with other props in the row? Wrap tags to more rows or dont show all of them? Is there some possible highest number of actants in statement?
You are right that it cannot grow infinitely, so there will have to be some "...", but these "..." should be clickable and click should somehow display the hidden ones. 
But still I want to see more of them in the basic view. There is no limit on number of actants, but what I suggest to display is up to 2 subject icons, up to 2 action icons, and up to 4 object (actant1 + actant2) icons. BTW I do _not_ want to display entities in the role of pseudoactants here in any way.

**Comment by davidzbiral** [comment]
I would prefer row click (or double click) to open editing. But this might depend how much info you suggest to be under Info. A priori, to open editing.
