### ISSUE TITLE
Stop allowing deletion of a used entity (Detail subwindow)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#364]
Now, the button "remove actant" in the Detail subwindow allows to remove even an entity which is used in some statement (meta or otherwise). However, what should become of statements using that actant?
The correct course of action is rather as follows:
1. an admin _discourages_ (rather than removes) such entity,
2. the editors replace it with a correct one,
3. and only then the entity - used nowhere now - can be removed if need be.

Therefore, **only allow the removal (and only display the button) if the entity is not used anywhere**.

Terminology: **relabel the button** to "remove entity" (because an "entity" becomes an "actant" only once it is used in some statement, i.e. "actant" describes it in its role in a statement rather than in its independent aspect).

**Comment by adammertel** [comment]
There is an inconsistency in the solution - how do you click on an actant that is not used anywhere? Only either through the search of discouraged actants, maybe directly through pasting the id to the URL, or through selecting an entity and manually removing all the uses - all these options are either ineffective or inprobable. 

What we do now - by removing the entity, every use of this entity is replaced by an empty value. This results in e.g., replacement of the tag in the editor by a suggester component. All the other values connected to the use of that particular entity remain (e.g, the position of actant in a statement, certainty value...). I think this is a good long term solution as I can easily imagine these two features of the remove modal:
 - list of all uses of this entity (this is basically in the detail box right now),
 - function to replace this entity with another entity by the user's choice.

Naturally, only admins will be able to remove entities. And also maybe editors may remove entity that is used only within their own Territories.

What do you think?

**Comment by davidzbiral** [comment]
I agree with the part on "how do you click on an actant that is not used anywhere?".

But still, there will be several admins who will have different levels of understanding of data management, and such removal is a very dangerous and questionable operation, because in the current implementation, authors of the affected statements are not informed in any way about the removal, i.e. they think their statements are correct, and they aren't and were truncated, and there is no way of finding such statements and correct them. I am ready to accept this solution, but on the following conditions:

1. The remove button will not be as prominent as it is now, i.e. a) inviting to do the operation often, and b) risking misclick too much.
2. There will be a dialog box to verify the editor's will to really remove the entity _and explaining what it does in the affected statements_. I.e., making the remover aware that it affects something.
3. Only (a) admins, and (b) editors who are the exclusive users of an entity can use this function (this is needed already in the finetuned 1.2.0 version because much damage could result from interaction of inexperienced editors with this button).
4. The statements with the entity removed will be somehow visible / searchable. E.g., one low-cost option would be to create a system C, something like "C entity removed, enter a correct one" (at elvl3), and make any "remove" action put this C in all the slots which contained the removed entity. Thus, any editor will be, through Search, able to search up the affected Statements and correct them.

How does it sound?
