### ISSUE TITLE
Tooltip empty in InkV-created S entities

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#369]
If Statement is imported from gsheets, its tooltip is the "id". If added in InkV (= prevailing case in the future), its tooltip is empty:
![obrazek](https://user-images.githubusercontent.com/55400794/133894387-0c294671-f585-4af0-a4ef-67cbc39a446e.png)
In other entities, the tooltip is the "label". What should it be in the case of Statements?
(A) Do we remove the tooltip for S? Cons: inconsistent with other entity icons and (!) unhelpful in Editor when handling substatements (i.e. S used as actants).
(B) Do we use "text"? Pros: useful, consistent with other entities. Cons: in Detail, the text has also a dedicated col. => here the tooltip kinda duplicates it.
(C) Do we use the URI in tooltip? Pros: follows the current practice for S imported from gsheets. Cons: Not very useful.

I tend towards B, but perhaps somebody will have an even better idea.

**Comment by adammertel** [comment]
After the discussion with @Ptrhnk, we think that Statement should have its own "label" and "detail" attribute, even the editors will be not using it most of the time. The tooltips for Statement Actants will then work the same way as the tooltips for other Actant types, but the text value should be appended to the third line, therefore we would go with solution B).
In case of parsing, we are now importing the id value from the spreadsheet table to both id and label, this may be changed (e.g., label should stay empty)

**Comment by davidzbiral** [comment]
OK, let's add "label" and "detail" to Statements!
My only concern is that these new textboxes kinda prompt editors to fill them in, which in this case is mostly loss of time, and on 15,000 statements this makes a real difference. It makes little sense to fill in a label for a normal statement. However, it _will_ make a lot of sense to fill in "label" and "detail" for Statement templates (fragments) destined e.g. for Bookmarks. I.e., I very much support this.
Will this Statement label and detail be edited through the Editor panel, or just the Detail panel? 
If in Editor, can they be somehow made different there, so that it is visible that they are very optional and they do not prompt editors too much to fill them in?

Parsing: yes, if the above solution is adopted, "label" of statements parsed from gsheets should remain empty for consistency.

**Comment by adammertel** [comment]
Good question. While Statement has the "open detail box" option, you can edit these values through here. But adding label and detail inputs to the editor box is also possible. What do you think?

**Comment by davidzbiral** [comment]
I think, let us leave them only in Detail, so that they the editors do not feel too compelled to fill them in.
