### ISSUE TITLE
Colour the entity type dropdown in Suggester?

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#372]
The dropdown in Suggester does not use colour - all is black. Since elsewhere the entity type is signalled through colour, the speed and precision of the selection of the entity type by editors would be enhanced by the use of colours in the dropdown. The dropdown would become a little colourful perhaps, but useful feature. Even more importantly, it would actively prevent the creation of an incorrect entity, e.g. "autumn" under Persons.
![obrazek](https://user-images.githubusercontent.com/55400794/133895262-479cac32-d750-4443-b38a-310c5e144bd8.png)

**Comment by adammertel** [comment]
@pondrejk @Ptrhnk is this a good idea? I am a little bit afraid of Disneyland. What about icons for each entity type? Or a more subtle solution with the colors?

**Comment by davidzbiral** [comment]
This is I think already implemented, isn't it? By left border.

**Comment by adammertel** [comment]
The left border style of the actant tag depicts the `logical type` attribute. This issue is about using entity colo(u)r codes within the suggested select.

**Comment by Ptrhnk** [comment]
No David meant left border of actant suggester (dropdown) as mentioned in the name of this issue. Which is already implemented.

**Comment by Ptrhnk** [comment]
Can I close the issue @davidzbiral ?

**Comment by davidzbiral** [comment]
Works as it is - thanks, I am closing the issue.
![obrazek](https://user-images.githubusercontent.com/55400794/143903971-5c61356d-8fe4-4c33-b5fc-878f76a3e168.png)

**Comment by davidzbiral** [comment]
I reopen. When tried in real world, I conclude I was right and would like to have the colours in the dropdown - not just when selected but also when the dropdown unfolds, in order to make the selection of the right entity type quicker. Human mind is much quicker in processing colours than abbreviation of entity type (V, C...).
![obrazek](https://user-images.githubusercontent.com/55400794/144706062-44bb525d-0514-448d-b79d-37c57343ede2.png)
