### ISSUE TITLE
Search panel: in Label, search for words from label

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#380]
If I search T for "Barca" or "Barc" in Search panel, I do not find T "La Barca". Change the algorithm in such a way that it searches for individual words (defined by white spaces) from the input in individual words from the entity labels. Case insensitive.
I.e., upon searching "Barc" and "Barca", it must find "La Barca".
Compare the beginnings, i.e. do _not_ (at least at this stage) implement any more complex comparison algorithm.

**Comment by jancimertel** [comment]
done: infix search
