### ISSUE TITLE
Territory Tree: filtering needed to avoid visual mess

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#389]
With so many root-level Territories, it is a mess. Therefore:
- Allow hiding empty (i.e. with no statement underneath).
- Consider allowing hiding those to which the user does not have editor or admin rights.
Starring favourite Ts will further contribute to keeping order.

**Comment by adammertel** [comment]
Create menu for filtering "empty", "starred", "editor rights", and by name

--------------------------
Display only
[  ] Non-empty
[  ] Starred
[x] Editor rights 
[  ] Filter __________

**Comment by Ptrhnk** [comment]
I have to postpone this to next version, we need to test and fix bugs before release.

**Comment by davidzbiral** [comment]
Agreed - not a high priority for 1.3.

**Comment by davidzbiral** [comment]
@Ptrhnk Let us now stop works on this - it turns out there are higher priority things. Non-empty Ts are already displayed first, right? This is I think sufficient for now.

**Comment by Ptrhnk** [comment]
@davidzbiral Maybe is good to remove it from tasks in project table as it's postponed and I'm not implementing it now, right? Or what do you mean by stop works?

**Comment by davidzbiral** [comment]
Yes, remove it from tasks please - we have loads of priority things. Tell me: is it the case that non-empty Ts are displayed before empty ones? I think so - which already solves a lot.

**Comment by davidzbiral** [comment]
On Slack, we are discussing to add the display parameter TRUE/FALSE to any root T. This would solve the problem.

**Comment by adammertel** [comment]
> @Ptrhnk: Yes, remove it from tasks please - we have loads of priority things. Tell me: is it the case that non-empty Ts are displayed before empty ones? I think so - which already solves a lot.

No, Ts have their order, and they are displayed within that order.

**Comment by Ptrhnk** [comment]
@adammertel when searching by label, should it starts with or contain searched text?
