### ISSUE TITLE
Show also "detail" (not just "label") in Suggester

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#391]
To allow the correct choice of an entity (or creation of a new one), it is necessary that the Suggester displays not only the "label" but also the "detail" field (if not empty).
This is an absolutely crucial feature to start real work.
(BTW it is probably not relevant to _search_ the text of "detail", but it is very important to _display_ it in Suggester.)

**Comment by Ptrhnk** [comment]
Also #273

**Comment by Ptrhnk** [comment]
What about showing detail on tooltips like this?
<img width="282" alt="Screenshot 2021-09-30 at 19 11 48" src="https://user-images.githubusercontent.com/29732281/135500656-e1fc936b-5e72-4367-ac04-4df8517d6a97.png">
Just wanted to ask, otherwise I will redesign the list to show every detail.

**Comment by davidzbiral** [comment]
I think these tooltips work very well, also because they allow longer "detail" if needed. So yes, tooltips. Just one thing to add: put only "detail" in the tooltip. Putting also the "label" there again means duplicating this info.
