### ISSUE TITLE
Editor box: if logical or comparison operator is set, make it more visible?

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#394]
It is somewhat troubling that logical operators are not more visible in the Editor box. E.g., if a Value is "more than 6", the user sees "6" on the screen, and "more than" becomes only apparent on mouseover in the info box. There is an argument to make, in the Editor box, the bundling (parentheses) and logical and comparison operators more visible (for correct reading and quicker checking).

I know that also logic and modality is crucial for the understanding of the Statement, so I concede it is incoherent to solve this for bundling and logical/comparison operators, and not solve it for mood and logic. So this is more of a design question for further consideration of a broader change, e.g. colour-coded display of the values which are now kind of "hidden".

**Comment by adammertel** [comment]
I agree. Now we have only a minimalistic solution and there is a potential to make something more visually informative. I will move it to @pondrejk now - we will talk about it.
