### ISSUE TITLE
Comparison operators: needed under actants for Values such as "more than 6"?

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#397]
In the original table for modality and logic (https://docs.google.com/spreadsheets/d/1a6Wli7bLQ-UkGzhiNWM4Lo_6gC6CWDdMVldhCZfh2rk/edit#gid=0), we had comparison operators under logical operators, and thought that they are not needed for actants. 
However, they might be something else than logical operators, and be needed under actants. E.g., it seems that to code "more than 6", we need V ">6", i.e. V "6" with comparison operator ">" (now, in gsheets, we save it as V ">6").

**Or else, should in this case the operator be part of the value itself, i.e. ">6" as in GSheets? TBD before implementation!**
After discussion, revise this thread: https://dissinet.slack.com/archives/C01K0EA45GC/p1632485654000100?thread_ts=1632208832.002300&cid=C01K0EA45GC.

EDIT: I now tend to think that if "more than six" is the value itself, it should remain in the value and the V should be literally ">6", same as in the data model, i.e. no change to the data model needed. But I need you @adammertel to think about this.

If we decided to implement the change, we would add a new column "comparison operators" in the table (link above) and do the following:
- separate comparison operators in the data model from logical operators per se (and, or, xor);
- separate them also in the modal windows into a separate select box;
- implement them where they belong according to the table;
- remove them where they do not belong according to the table.
![obrazek](https://user-images.githubusercontent.com/55400794/134685748-4dae2a77-88ad-42a1-b210-4069d7903727.png)

**Comment by adammertel** [comment]
I understand the problem. I think it should be decided as soon as possible as this involves the data model.
If you think that this will be needed in the future, lets do it now.

**Comment by davidzbiral** [comment]
I now think it should be part of the value, i.e. ">6" is actually the value, the ">" is part of the V, not the relation of the V to something else. I.e., introducing a convention of having operators within values where they are part of the value itself. It is arguably something different than a comparison operator. We will confirm when we meet.

**Comment by davidzbiral** [comment]
Closing this - confirmed in a call with Adam that we will store "more than six" in the value itself, ">6", because there is no point of comparison, the "more" is rather part of the value itself. We will then need to think about it for numerical values, and work with this type of free-text ">6" in data projections and probably also in the more semanticized DDB2 version, i.e. decompose (semanticize) this convention.
