### ISSUE TITLE
Bookmarks: saving also whole S structures (templates), not just individual entities

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#398]
In some sources, there are whole repetitive syntactic structures which can be copied over and over again. E.g. "[Person] saw the heretics, but did not adore [the heretics], neither saw them adored [by anybody]". This highlights the need to have "fragmentary" metalevel S structures, which users will be able to save in Bookmarks and then use over and over again, just dragging the correct actant (e.g. Person) in the empty slots. (The example is even more Statements perhaps, but since we re-adopted "multiples" in the action field, this could perhaps now be handled within 1 statement...)
 
Such metalevel S structures will exist anyway, e.g. to decompose composite Concepts which have Statement structure (he believed - C1; C1: "God did not create this world", which can and should be decomposed into the full S syntax underneath through metalevel props). So probably no problem here (the principle of decomposition of some things into metalevel/T0 Statements through metalevel props already discussed and approved by Adam in I think July 2020).

But this involves a change in the GUI: if an S structure is dragged from anywhere (typically from Bookmarks) into the Action field (not Actant field), the A Type entity of this structure should go into Action, and the other dependent actants should go in the appropriate actant slots in the Editor, alongside any Action or Actant props (if any) - thus serving as a template.

**Comment by adammertel** [comment]
This is not relevant anymore

**Comment by davidzbiral** [comment]
I confirm, not relevant any more - we have found a new solution with S Templates (S').
