### ISSUE TITLE
Suggester / entity type select: by default, free search in all entity types

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#401]
The choice of the entity type from the select is an annoying action repeated all the time. Please **remake the select and the search function** (in line also with the Detail select where adding "\*" is requested in ) in the following way:
1. The **default option** in this suggester select will be **"\*" (or "Any" or however we call it)**, and the whole DDB1 will be searched **without filtering by entity type** (i.e., the Suggester will display results from different entity types).
2. If the user wants, s/he can then filter the search results by choosing the entity type in the select after the initial first search.
3. The choice of entity type from the select is only enforced upon **creation of new entity** (where, of course, the user must declare the entity type). I.e.: if the value in the select is "*", creating a new entity will trigger opening the select, and the user will choose the entity type.

This only applies to suggester selects where we do not enforce a specific entity type. I.e., no change in the suggester select under Resources (where only R remains), under Actions (where only A remains) etc.

![obrazek](https://user-images.githubusercontent.com/55400794/134806405-fc02c23c-dcd9-49ef-b035-c5476f68a9c2.png)

Extended rationale: Most of the time, users will find what they are searching for without the necessity of limiting the search to an entity type. They can if they want, but they should not be forced to. E.g., if I search for "time relation", I will hardly find a Person, and so choosing "C" all the time from the select is annoying.

**Comment by adammertel** [comment]
@Ptrhnk Do not forget about implementing a modal for selecting the entity on "Create" action. (this is maybe a useless message :D)
