### ISSUE TITLE
Suggester component graphical | UX redesign

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#408]
While users spend most of the time in the suggested component, it may need some new fresh ideas to make it look fresh and user-friendly. 
@pondrejk maybe you can start with some analysis of existing libraries, implementations...?

**Comment by davidzbiral** [comment]
Easier selecting of suggestion - now only the small "play" icon on the left. Allow cursor keys (PgDn/Up, arrow up/down) to select, and perhaps larger select area.

**Comment by davidzbiral** [comment]
I agree with selection by keyboard, good thing.

> display "home" entities (already used elsewhere in T) on text field focus (without the need to type)
I.e. on focus of suggester's text field? Problem: there will be hundreds, rather thousands of entities used in each T.
