### ISSUE TITLE
Statements List: Layout for extrude in statements table

### ISSUE THREAD

**Issue by pondrejk** [DISSINET/InkVisitor#427]
should contain the same info as the editor in condensed form

**Comment by adammertel** [comment]
This is the "expand" function in the List of Statements that we have been postponing for a longer time.

**Comment by davidzbiral** [comment]
I like the proposal, let's go forward with this!
But two points deserve attention:
- I have some small doubts about the viability of this tabular design vs. comparatively long labels that we'd like to have.
- Also actions have props (in a high percentage of cases: it can easily be 80%) and they should be displayed here.

**Comment by pondrejk** [comment]
![take2](https://user-images.githubusercontent.com/8287578/153047632-cbde69cc-779c-4f15-bb4a-4aa49120ac5b.png)

Updated proposal, should leave more space for nesting, metadata, etc. 
@adammertel

**Comment by davidzbiral** [comment]
This works!
Only a minor comment really: perhaps we have space for not abbreviated role labels, such as "subject" instead of "subj", "reference" instead of "ref", "actant 1" instead of "act1".

**Comment by adammertel** [comment]
I like this. Lets try to implement it now :)
