### ISSUE TITLE
logo font

### ISSUE THREAD

**Issue by pondrejk** [DISSINET/InkVisitor#430]
more historical version?

**Comment by davidzbiral** [comment]
The opinion of Tomáš Staudek was exactly to refresh, and avoid the historicizing font, so there is a difference of opinion on this. In any case, it is true that our target audience is also social scientists, not just historians.

**Comment by pondrejk** [comment]
I wouldn't go too far with the historical look, just slightly more evocative font, suggestion before/after:

![screen](https://user-images.githubusercontent.com/8287578/136469481-685a9d50-3150-4c81-8506-2272883070ef.png)

**Comment by adammertel** [comment]
@pondrejk do you also want to change the fill color of the horse? I am probably more in the favor of the historic font, but definitely just my subjective opinion.

**Comment by pondrejk** [comment]
Colored horse feels better visually separated from the title. Though we can get back to white or chose a different hue if consensus is against it

**Comment by adammertel** [comment]
@pondrejk Ok, let's start with your suggestion and we will see whether it fits or not. My idea was to use this logo without the application interface also.

**Comment by adammertel** [comment]
Lets probably close it for now
