### ISSUE TITLE
Devise a way to edit statement templates

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#439]
For Bookmarks (and also other, even more important reasons such as decomposition of composite Concepts and Action types), we will need metalevel Statements (incl. Statement fragments, serving as templates, with some parts filled in and some to add manually when the template is used).
- How to edit them? The logical place to edit them is the Editor panel, but how to get to the editation, given that metalevel statements are not under any T? There is probably one way already: suggester > Detail > EDIT icon. Test whether this way works, and think whether this is a simple-enough way or too tortuous to find (and too many clicks).
- Devise a way to use those statement templates (from bookmarks or the full database). I.e. apply a template (S entity) to an empty (or even non-empty?) editor window.
BTW those statements should have labels, and thus they will be searchable.

**Comment by adammertel** [comment]
This is probably (hopefully) not relevant anymore
