### ISSUE TITLE
Minimalistic adjustments of the Search panel

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#497]
We decided on a more thorough design of the Search, but for now, minimalistic adjustments are enough:
- "Label" goes first, as the place to write the search string.
- "Class": change text to "Limit by class"
- "Actant": change text to "Limit by co-occurrence" (if the algorithm to do this already exists; if not, hide this filter and move this part to the next milestone).

**Comment by Ptrhnk** [comment]
Also add loader when searching adding tag and tooltip to left side on found tag.
