### ISSUE TITLE
Handling backup DB data

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#503]
Besides the backup file being stored once a day, these files should be regularly sent somewhere outside of the MUNI server. I am not sure now about our possibilities. Google Drive? FTP server? mail? @jancimertel do you have some suggestions?

**Comment by jancimertel** [comment]
there is a mounted high-capacity medium on the server, which should be used exactly for this.
I've moved backup script to the repository.

Closing this issue for now.
