### ISSUE TITLE
User information should be saved somewhere else than into localstorage

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#509]

**Comment by adammertel** [comment]
@jancimertel @Ptrhnk Do you know about a more suitable solution for this?

**Comment by Ptrhnk** [comment]
There is also session storage which is not pernament and clears when the tab is closed? Is it better? Do you expect pernament log in of users?

**Comment by davidzbiral** [comment]
The current trend in similar services is I think remaining logged in (apart from bank accounts of course :-) ), but we are fine with both. It is good not to have to log in any time, but not a big inconvenience to log in again.
