### ISSUE TITLE
Create Actant modal styling and onKey Enter confirm

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#516]
![image](https://user-images.githubusercontent.com/12932677/139706533-b2befbbd-07d1-462d-b364-b0a628afa364.png)

**Comment by Ptrhnk** [comment]
Yes. I knew about it. I just merged half done suggester changes, because of possible conflicts. (I had inovations on my branch - more than 2 weeks of work and other changes were going on on the same place.)

**Comment by Ptrhnk** [comment]
Also #515
