### ISSUE TITLE
category in GET /actants/detail/${actantId} don't match with same actant in other requests

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#549]
Example in #547

**Comment by Ptrhnk** [comment]
<img width="275" alt="Screenshot 2021-11-06 at 22 34 20" src="https://user-images.githubusercontent.com/29732281/140624507-a5538a87-0565-4ba4-ab68-586ea23c4101.png">
We use same request in actant detail box - same issue.

**Comment by adammertel** [comment]
This solved the problem, but it is probably not the optimal solution 
![image](https://user-images.githubusercontent.com/12932677/140625598-32d93e29-5ffc-47a6-bed3-1e98bc9d4e50.png)

**Comment by jancimertel** [comment]
this is a good solution - just the type of class should be explicitly EntityActantType as it could implement more than just one class type.
Class is essential, constructor in entity requires an assignment - one value needs to be used as default - Person in this case
