### ISSUE TITLE
Statements List: Move statement to different territory

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#553]
Probably a suggester at the beginning of the editor box

**Comment by Ptrhnk** [comment]
@jancimertel is it possible on BE?

**Comment by jancimertel** [comment]
/territories/moveStatement should work

**Comment by jancimertel** [comment]
territories/moveStatement - territoryId needs to be added to request

**Comment by Ptrhnk** [comment]
@jancimertel needs FE afterwards

**Comment by adammertel** [comment]
@Ptrhnk @jancimertel What about just updating the `data.territory.id` inside the statement while the `order` value will be changed to `-1`? Is BE able to take care of that index?

**Comment by jancimertel** [comment]
actants/update can be used too with order value `-1`. Just keep in mind that if the `-1` value is already used by another statement, then the used value will be changed accordingly:
1. if already used indexes are [-1, 0, 1], then the order for updated statement will be changed to `-0.5`
2. if already used indexes are [-1, 1], then the new order value will be `0`

**Comment by Ptrhnk** [comment]
Ok, I Implemented this solution.

> actants/update can be used too with order value `-1`. Just keep in mind that if the `-1` value is already used by another statement, then the used value will be changed accordingly:
> 
> 1. if already used indexes are [-1, 0, 1], then the order for updated statement will be changed to `-0.5`
> 2. if already used indexes are [-1, 1], then the new order value will be `0`

**Comment by Ptrhnk** [comment]
@jancimertel please check ordering.

**Comment by jancimertel** [comment]
```
export enum TerritoryOrder {
  First = -9999,
  Last = 9999,
}
```

order enum added, for first position use TerritoryOrder.First, TerritoryOrder.Last for last position

**Comment by jancimertel** [comment]
#681

**Comment by davidzbiral** [comment]
@Ptrhnk : is this not done already? If so, close.

**Comment by Ptrhnk** [comment]
We didn't close it, because of #681. Which was probably implemented by @adammertel and needs to be checked ideally by him for time efficiency. If he don't have time, I'll check this later. Or we can close this one and just now about the possible bug of not putting new territory at the end of the statement list - #681 (which needs check).

**Comment by Ptrhnk** [comment]
I implemented it.

**Comment by Ptrhnk** [comment]
@ It's added on first place in statement list when moved to new territory, is it OK?

**Comment by davidzbiral** [comment]
@Ptrhnk Yes, it's fine. If needed, it can be moved in a second step to a different position by a new DnD.
