### ISSUE TITLE
Statements List: Move Selected T to different parent T

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#554]
Suggester?

**Comment by Ptrhnk** [comment]
Needs BE handling

https://user-images.githubusercontent.com/29732281/149965494-47b3a714-9ef8-49b3-99be-93dd9f6fc743.mov

**Comment by Ptrhnk** [comment]
@jancimertel @adammertel
Also possibility tu recursively search for lowest child on FE and use path to filter them from suggester.
