### ISSUE TITLE
Editing `logicalType` in `actant.data` does not work

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#556]
logicalType should be editable by everybody no matter what UserRole they have (for now) 

![image](https://user-images.githubusercontent.com/12932677/140656982-94c08795-8854-4951-a617-db13d99233ba.png)

**Comment by jancimertel** [comment]
fixed: repetitive calls with the same payload result in unchanged flag -> internal server error
now the unchanged flag wont trigger an error
