### ISSUE TITLE
Identify imported entities as being from a specific batch

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#577]
In the import gsheets, there might be individual features or errors (parsing errors, input data errors or legacy features) that we will need to correct later. Therefore, we need to be able to identify the entities originally imported in each individual batch:
- some automatically attached tag or other feature identifying a specific import batch and allowing to find them through Search box;
- for each S from a gsheet coding sheet, R entity of the parsed table (following the [Resources table](https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=583750775)) stored as R reference "secondary";
- day of import of an entity (probably "creation" timestamp in the edit log - created earlier in GSheets, but from InkVisitor's perspective this is the moment).

Questions:
- Do entities other than S have any edit log? Does it make sense? Because of metastatement props and other features edited through Detail, it probably does?
- Do S allow multiple R "secondary" references and multiple "primary" references? They should - if not, please allow.

**Comment by davidzbiral** [comment]
@tomaham : Any opinion on how to do this? Audits can be (part of the) solution perhaps?

**Comment by tomaham** [comment]
We plan some chat with Adam around 1.3 release and this will be part of the talk.

At the moment, I plan to create a note (with the "original author" info) with import information and possibly an audit record.
It should be possible to simulate audit event, so the original author is part of the audits. 

Because there is not a plan for how exactly to use such audits information, it is not clear how to store this information (we do not know how it should be retrievable, for what exact purpose it will be used).  Anything can be put to "notes" and it can be even parsed for complex things.  But if  notes are fragile, possible easily deleted - they should not server as any more permanent log. Audits as data, which are immutable for user change are definitely the place to store the information.

**Comment by davidzbiral** [comment]
Yes, audits are the place. In Search function, there is a possibility of retrieving things by editor and by date range, which presumably must work with audits, so audits are the way.

**Comment by tomaham** [comment]
If I am not mistaken, at the moment, the user can not search entities by editor and date range - but this is probably planned? (In 1.3. ?)

Absolutely describe this -or rather specify it **in the context of the app**, that is, describe use cases when and how should the application give you a way to operate with such information. (Maybe this is described somewhere? I am just stating "I" am not aware of the specification or these use cases and the present interface does give hints about these use cases.)

**Comment by davidzbiral** [comment]
You're right that for time and priority reasons, we put most of the advanced search functionalities into 1.4. More to follow.

**Comment by adammertel** [comment]
@tomaham @davidzbiral 
Would it be possible to use Audit model for 1) and notes in Entity model for 2)?

**Comment by tomaham** [comment]
@adammertel 

Ad "After a discussion with @tomaham, a new non-editab le system attribute _systemNotes: string[] wil be introduced to the Entity model."  

Actually, let's leave it in the normal notes now and think this through in some future release, where we have more visible the use cases context and the nature of the operations in the inkVisitor, i.e. which will be possible, rare and normal in the system. From the system engineer's point of view, even the import should actually use the API - the direct work within the DB is not exactly kosher. :)

**Comment by tomaham** [comment]
@adammertel  Hm, when there are two audit records, which have the same "object" inside, only one record seems to be displayed, so the solution offered in the message above does not work without further edits in the system.

So this is not a good solution.

**Comment by davidzbiral** [comment]
@tomaham and @adammertel , try find a solution for this - I need to (1) give full credit to the editors of the data incl. old gsheets data (soon even calculating their "share" in statements based on the audit entries) and (2) identify the batch.

**Comment by tomaham** [comment]
@davidzbiral The present solution is not sufficient for you?

**Comment by davidzbiral** [comment]
Notes are somewhat sensitive, and perhaps not the best place structurally to store what essentially is audit information, but I think I am fine with this.
