### ISSUE TITLE
Exclude V entities from suggestions in the Suggester

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#578]
V entities are free text and should not form nodes which connect things. E.g., if I have 41 years and somebody else has 41 years, the two V entities have the same label "41" (has - C age - V 41), but the two V entities "41" should be distinct nodes. Now, Suggester suggests the previous value "41", which incites editors to erroneously click on it instead of creating a new V "41".

Solution: stop Suggester from searching V entities. V entities are by their very nature always one-use, always distinct.

**Comment by davidzbiral** [comment]
@Ptrhnk: Is this really closed? Not implemented in current deploy (the one from last weekend or Monday).

**Comment by Ptrhnk** [comment]
I was implementing it on Nov 29 (same day as deploy), so It probably did't went to this version.

**Comment by davidzbiral** [comment]
Value entities are searched through again in Suggester, at least in Detail, which should not happen. Reopening, please solve, @Ptrhnk , tx!
![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/a634e52d-eaac-4e55-967d-7c0976a72f7c)
