### ISSUE TITLE
Add "About" popup with info on app version, lead creators, recommended citation

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#581]
- app name and version;
- copyright notice: (c) Masaryk University, 2021;
- licence;
- lead creators: see README and if needed discuss that text. The two texts should be in harmony;
- recommended citation of the software (in different formats?).
- clickable logos: ERC, GAČR, MUNI Arts
Have a look what most apps do in such About and consider doing it too.

**Comment by davidzbiral** [comment]
Moving this to a more visible milestone :-)

**Comment by adammertel** [comment]
@davidzbiral 
This is the first draft 
![image](https://user-images.githubusercontent.com/12932677/167585020-58135927-0227-4414-9496-7e561d5bbe65.png)

**Comment by davidzbiral** [comment]
@adammertel : 
- Logos are fine (if their resolution is suitable). 
- It is a long-term project, so we must count on people leaving, i.e. we will not give credit to all developers who were there for some time: for now, it works, but think about it.
- I need to change the text and have it proofread. Please share it with me as gdoc in some textual version (no problem with some MarkUp or other coding as needed). E.g., I need to credit specific projects, and I will probably change the About part in line with the README.TXT.

**Comment by davidzbiral** [comment]
@adammertel : drafted [here](https://docs.google.com/document/d/1FpiJe809vKNKnnctbN_1O7cHckTrLR2sW_v9jp0-zFs/edit#), please have a look!

**Comment by adammertel** [comment]
@davidzbiral 
The second draft
![image](https://user-images.githubusercontent.com/12932677/205457168-7994352b-0f96-41ab-a3ec-c5ce42262ce2.png)

**Comment by davidzbiral** [comment]
@adammertel : Approved on content. Just please for MUNI Arts logo, use the positive variant (in MUNI blue) rather than the negative/inverse variant (in white on MUNI Arts light blue background). It will go better with the other logos. Tx.

**Comment by adammertel** [comment]
Done, 
The about page is now accessible through the Menu button.

**Comment by adammertel** [comment]
Done, 
The about page is now accessible through the Menu button.
![image](https://user-images.githubusercontent.com/12932677/207783789-fa9e41e8-6276-4203-b4e2-5e201036640a.png)
