### ISSUE TITLE
Update Database diagram

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#583]
Update https://app.diagrams.net/#G1j2Vpq-zY63TT6Da3mUZLmzRTN_1TD3P5 with all recent changes.

**Comment by adammertel** [comment]
I agree. Lets do it after #612 is solved

**Comment by adammertel** [comment]
The old diagram is deprecated, long live the new diagram https://drive.google.com/file/d/1bKvqEKr6JzPWryVg-vYudQy_4KvuzHS9/view?usp=sharing
@davidzbiral probably take it and back up it on the DISSINET drive somewhere.
