### ISSUE TITLE
Visibly mark Sandbox deploy to avoid confusion

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#584]
Make Sandbox deploy easy to identify so that editors do not put real data there by mistake. E.g:
1. different (and very prominent) colour of the header background (under the word "InkVisitor");
2. "InkVisitor" in the header -> "InkVisitor SANDBOX".

**Comment by adammertel** [comment]
@jancimertel @pondrejk how it is possible to implement this? A special CSS file for each deploy strategy?

**Comment by davidzbiral** [comment]
Would be enough to change the header background... do not need to change the "app name" to "InkVisitor Sandbox". Colour is enough. Unless we do this, very probably some editors will enter some real data in the Sandbox deploy => big problem.

**Comment by pondrejk** [comment]
visible in /inkvisitor-staging env, sandbox needs to be redeployed for changes to take effect

**Comment by adammertel** [comment]
@davidzbiral you can find "inkvisitor-staging" deploy here https://dissinet.cz/apps/inkvisitor-staging/
