### ISSUE TITLE
Statements box: Reorganize detailed info

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#585]
Reorganizate the detailed info displayed when clicking on the unfold button in Statements box:
- Divide subjects, actions, and objects, and put them in the same order as in the less detailed info (i.e., as in the condensed view).
- In this detailed view, consider even dividing Actant 1 from Actant 2 (i.e., instead of "Objects", in this detailed view, having "Actant 1" and "Actant 2" separately).
- Consider an icon accompanying each actant and action if 1 or more properties are appended to it in this Statement (the same icon could also serve as a general property icon).

![obrazek](https://user-images.githubusercontent.com/55400794/142147242-446bb31d-6c7f-42d7-a140-d7d7259a9691.png)

**Comment by adammertel** [comment]
The Statement list detail will be implemented in a different way

**Comment by davidzbiral** [comment]
How?

**Comment by adammertel** [comment]
It's just in a form of a graphical mockup on paper. But I hope you will like it :)
