### ISSUE TITLE
Display Statement log and Entity log

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#590]
Users should be able to view the basic log, i.e. when an entity was **created** and when it was **last modified** and by **whom**.
I don't know what log is stored in DDB1, but this basic log is probably all we neeed to display.
For any Statement, it should be probably:
- in Editor, at the very end (after Notes).
- in Detail, at the very end )after Notes).
For any Entity (you call them Actants), it should be:
- in Detail, at the very end (after Notes).
(I do not know how to deal with the changes, though, i.e. that this log changes the very second we are editing in Detail or Editor. Perhaps display log only upon click would solve this?)

**Comment by adammertel** [comment]
#618 #619 are the preconditions here

**Comment by adammertel** [comment]
Also, add "last edited" column to the statements list

**Comment by adammertel** [comment]
Closed, #658 created
