### ISSUE TITLE
User login not working: ""shaw"  

### ISSUE THREAD

**Issue by rljshaw** [DISSINET/InkVisitor#596]
Received two emails with different passwords for username "shaw"; neither work. Please send new login.

**Comment by adammertel** [comment]
I changed the email of this user to mine and let the password send to me. Now It is "bh32j1kz9o", and it is working fine for me. Maybe try to log in, rechange the mail again, and click on the yellow key button at the end of the row to get a new one.
![image](https://user-images.githubusercontent.com/12932677/142766723-6206b809-83e8-424a-9f9d-87d8e86f348e.png)

**Comment by rljshaw** [comment]
Thanks, working now
