### ISSUE TITLE
Border signalling the entity logical type does not update

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#602]
When I updated the entity logical type to "definite", the border did not update. Even upon renewal of window.
Neither in the full-label entity nor in the icon in Statements.
![obrazek](https://user-images.githubusercontent.com/55400794/142383538-68ece727-8137-4358-aa6f-8c696eced883.png)

**Comment by Ptrhnk** [comment]
Definite should be full border which I can see on the picture (Raimundus Arnaldi). Is it really wrong? Or did I understand it in different way?

**Comment by Ptrhnk** [comment]
I'm also trying to replicate in on dissinet.cz, but it seems to be working right. Can you record it?
https://user-images.githubusercontent.com/29732281/143040980-f75d9ca0-a287-45bf-a682-3d2a84b7474c.mov

**Comment by adammertel** [comment]
@davidzbiral ? closed?

**Comment by davidzbiral** [comment]
You checked that this works now - I haven't but the video shows it works now. Closing.
