### ISSUE TITLE
Border signalling entity logical type does not display well in Search results

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#603]
This G is indefinite and shows thus in Editor but in Search results, it shows mistakenly with full black border.
![obrazek](https://user-images.githubusercontent.com/55400794/142385609-cf59c5a8-3c8e-4c4e-879a-322ff5e635aa.png)

**Comment by Ptrhnk** [comment]
Needs to be added to data model first.

**Comment by Ptrhnk** [comment]
@jancimertel can you pls add logicalType to search results? I will then implement it on FE.

**Comment by jancimertel** [comment]
@Ptrhnk please use branch [603-logical-type-in-search](https://github.com/DISSINET/InkVisitor/tree/603-logical-type-in-search)
