### ISSUE TITLE
Meta statements: preserve order and allow changing order by drag & drop

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#607]
As with other statements and props, the order (1., 2., 3...) matters in meta statements in Detail (and data model). Therefore:
- Do not order alphabetically but add new ones at the end.
- Add drag&drop button ![obrazek](https://user-images.githubusercontent.com/55400794/142648635-9defd4a7-a13c-4f8c-b0e8-78b081804f58.png) and allow moving meta props to a different place in the order.

**Comment by adammertel** [comment]
Linked to #612

**Comment by davidzbiral** [comment]
@adammertel : how this is progressing? This one is really important.

**Comment by adammertel** [comment]
This should be implemented, the new changes to the data model allowed this
. But It's not drag and drop so far (move up and down buttons).

**Comment by davidzbiral** [comment]
@adammertel : we need drag & drop, definitely. Move up/down is not practical at all.
