### ISSUE TITLE
"Moving meta props into the actant model" discussion

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#612]

**Comment by davidzbiral** [comment]
We will need 2nd order properties in meta props.

**Comment by adammertel** [comment]
Decided to implement new model IProp

**Comment by davidzbiral** [comment]
@adammertel : how will it look like? Does it allow future extension with 3rd order props?
Some structures need five slots or 2nd/3rd order props, e.g. "Prague is 206 km from Brno and 90 km from Pilsen".

**Comment by adammertel** [comment]
@davidzbiral this does not limit DDB2, but if you will like to have 3rd level properties (please don't  :) ), do not hesitate to reopen this issue.
