### ISSUE TITLE
Develop a general procedure for Parsing meta headers (instruction rows) in Gsheet data

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#617]

**Comment by davidzbiral** [comment]
There are 3 instruction rows in the header of datasets prepared for parsing which define what to do with the given col - this is what "meta header" in the issue name means.

**Comment by tomaham** [comment]
I guess this task is mine now. 

 @davidzbiral  
Sometimes there are four header rows ? (e.g. "texts" ?) Could we have one place, which aggregate all instructions and resources around the the topic of this issues? (Maybe here, maybe godc, but one place with everything. I recall you talk about 5 header row in slack, but that is the thing - let's have one place.)

**To to "import-operation" keywords:**

I love the operation keywords "inside" and "discard" (that is my favourite, actually B-) ). 

I have a slight headache with the keyword "prop".  In gs of text/resources/manuscript there is "prop", in gs Kent coding the keywords change to "proptype", "propvalue" and "2nd-order...".   I understand the general principle, but I struggle with the implementation details, I'd like to be more sure.   (Can we have gdoc, where you document your all notation of import keyword instructions? Or maybe a meeting could clarify lot of things.)

More to one concrete issue:  Do we have source, where is explained how exactly should the "prop" be implemented? E.g. what goes like "property statement" with A0093 and what goes like property in technical sense which uses the the prop array of the general actant attribute?   (Is the metastatement the same thing as property statement?)

Are there in the any inkvisitor stage valid data, which almost canonically describe the datamodel through concrete instantiations? (Robert's sandbox?  I am browsing through the mockupdata of various stages and I tend to get confused. )

I wanted to use inkVisitor interface to validate my data-model understanding, but it can be actually even more confusing. I expected, that the interface will display everything which in the data (greater idea to see raw jason under the interface), but it seems it is not doing it always?  E.g. production inkivisitor: https://dissinet.cz/apps/inkvisitor/#territory=T107-1&statement=fc2cc13d-3ccd-4770-89c5-707fbffdd7a6

 * It has resources attached, but interface does not show their numbers.
 * whole statement should have a property-statement t:R0010_C0352 : v:R0007_L0052 #L0053 , but  I cannot find it in the interface.
![image](https://user-images.githubusercontent.com/3739529/154542159-04b40314-3a39-4044-bef7-8409e8a2d113.png)

So I guess, I cannot rely on the interface at this moment?

**Comment by davidzbiral** [comment]
@tomaham : the R0052_C0352 is completely strange. Cs and As and Ts and Rs are pan-DISSINET, no prefixes should be there. While for Locations, we unfortunately have non-unique IDs, i.e. L0001 in one batch of data to parse is a different thing than L0001 in another batch, which Adam solved so far by prefixes.

**Comment by davidzbiral** [comment]
> how exactly should the "prop" be implemented? E.g. what goes like "property statement" with A0093 and what goes like property in technical sense which uses the the prop array of the general actant attribute? (Is the metastatement the same thing as property statement?)

"property in technical sense which uses the the prop array of the general actant attribute": this we call "metaprops" (meta statements in the old deploy). I think I should change the notation "prop" to "metaprop", i.e. what is shown in "Detail" box. E.g. superclass. Would be clearer? I am going to do that.

**Comment by davidzbiral** [comment]
Are there in the any inkvisitor stage valid data, which almost canonically describe the datamodel through concrete instantiations?

**Comment by adammertel** [comment]
@tomaham I try to keep the visual guide of the data model actual and consistent with the models on master/dev branch. Sometimes, there is a change that may break this consistency, otherwise please refer to them.

**Comment by davidzbiral** [comment]
@tomaham : Is this issue solved? If so, feel free to close.

**Comment by davidzbiral** [comment]
This seems done - the imported data is correct. Closing.
