### ISSUE TITLE
Parse Manuscript table as Objects

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#629]

**Comment by adammertel** [comment]
@davidzbiral after I parse all rows in https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE as Objects, what will be the resource for statements in coding tables?

**Comment by davidzbiral** [comment]
Not sure whether I understand the question, i.e. what is the connection between this gsheet and coding tables
Only one sheet, Manuscripts, is Object entities: 
https://docs.google.com/spreadsheets/d/13eVorFf7J9R8YzO7TmJRVLzIIwRJS737r7eFbH1boyE/edit#gid=0
The sheet Texts is T entities.
The sheet Resources is R entities.
