### ISSUE TITLE
Make better error message for "Endpoint not allowed"

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#648]
If somebody tries to delete a statement in a root T they do not have the necessary rights, error message is displayed which says "Endpoint not allowed", which does not say much. Make a better error message text so that it says something reasonable.

**Comment by jancimertel** [comment]
acl entry added - endpoint is allowed by default for all users, per-actant rules are then applied (can view/can edit/can delete).
If the user doesn't have permission to delete, error  message `actant cannot be deleted by current user`.


`
