### ISSUE TITLE
Standardize Entity / Actants naming

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#650]
Entity is every record / node in the database. Actant is the connection (position subject, actant1, actant2) between Entity Statement and any other Entity. 

Am I right? @davidzbiral?

Changes in the code:
ActantDetail -> EntityDetail
ActantI -> EntityI
actants DB collection -> entities
EntityI model -> remove

**Comment by davidzbiral** [comment]
Yes, this is right, @adammertel. Thanks!

**Comment by davidzbiral** [comment]
Yes, everywhere - in db collections, JSON files...
