### ISSUE TITLE
No longer possible to drag Statement (S) entities into actant slots

### ISSUE THREAD

**Issue by rljshaw** [DISSINET/InkVisitor#670]
It is no longer possible to drag Statment entities into Actant slots (which is currently by far the easiest way of making a Statement an actant in another Statement). 

This seems to be the case in both the "inkvisitor-sandbox" and "inkvisitor" deployments.

Need this one fixing asap for teaching reasons

**Comment by davidzbiral** [comment]
Absolutely necessary, @Ptrhnk please prioritize.

**Comment by adammertel** [comment]
Should be now fixed, on all deploys modes.
