### ISSUE TITLE
Add statement at certain index not working when adding at the beginning (before btn) or end (after btn)

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#681]
context btns for add statement after / before not working at all when only one statement added

**Comment by jancimertel** [comment]
support on backend is ready (Order enumerator - First / Last ), waiting for further changes in naming (Actant -> Entity) so it can be tested altogether

**Comment by Ptrhnk** [comment]
@adammertel check and close

**Comment by Ptrhnk** [comment]
Okay adding at the end and beginning works, tested many times in one list to be sure that it's endless.

**Comment by Ptrhnk** [comment]
It was done by calculations, but I'll move it to new order enum.
