### ISSUE TITLE
In any Action type, allow declaring "NULL" (i.e. no content / no entity allowed), and "NULL or *", for any actant's entity type

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#684]
Now the default in actant entity type fields is "any", but the default should be "-" or "NULL", i.e. no actant allowed in this slot. E.g., some verbs do not have a2, and in the near future, validation should check whether someone has not entered an a2 for such verbs. Therefore, for any A type, we need to be able to declare that nothing is allowed - either by a "-" or (perhaps better, because more explicit and also used in actant valency field) a "NULL".
BTW there are many verbs only with subject, and some rarer even without subject ("it rained"; here even the subject will be NULL, and no actant will thus be allowed).

Doing this, we must treat somehow the valency value "NULL | *" in actant entity type. It means: either empty, or any entity type. I don't think the current implementation allows declaring this. I.e., we need to differentiate "any" (but some positive) from "any or empty" - for validation purposes (both human validation by coders and the future machine validation by the GUI).

**Comment by adammertel** [comment]
@Ptrhnk could you take a look at this? The simplest solution is probably changing "* any" placeholder used when nothing is selected to "no entity" and add a new "select all" option with placeholder "* any"

Here is a possible implementation:
https://codesandbox.io/embed/ecstatic-waterfall-e87xz
