### ISSUE TITLE
Display warning icon when dragging tag into suggester that does not allow that type

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#685]

**Comment by davidzbiral** [comment]
Good thing, @adammertel. Perhaps already connect this with disallowing the choice of actant of an entity type not allowed in the given chosen actant slot from Suggester search? I.e. prevent not just drag & drop but also choice from suggestions.
Definitely choosing it should not be allowed - probably with the same error message as for the misguided drag & drop.
What I do not know is whether the not allowed entity types should even be excluded from search - probably yes, but if it is difficult, this can wait for v. 1.4.
