### ISSUE TITLE
Fix the left border within the right box

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#686]
![image](https://user-images.githubusercontent.com/12932677/147875696-e0ca7541-b9f6-47fe-ac94-324322b9677a.png)
![image](https://user-images.githubusercontent.com/12932677/147875770-75536f7d-31d7-47b9-8a8a-3262bcf5e8c9.png)

**Comment by Ptrhnk** [comment]
I've already improved styling and behaviour, but Im not sure if there is a problem when border is only on expanded box.
