### ISSUE TITLE
PropGroup component should implement table with dragging option

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#698]
linked to #609 

At this moment, PropGroup component is based on a simple grid-based table and used within editor and detail. Following the best practice within actant /action table, we should use the react-table with dragging function here (instead of buttons for moving things up and down)

**Comment by Ptrhnk** [comment]
Would be nice to somehow solve it with grid because of better styling options, but I try to solve style deficit in table. There is problem with full length dynamic tags width now.

**Comment by Ptrhnk** [comment]
Closing as it's implemented in #769 (duplicity)
