### ISSUE TITLE
Restructure entity Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#705]
- Used in metaprops
- Used in normal props
- Used in statements [i.e. any other position: actants, tags]
[EDITED 23 Feb 2022 - relabeling (shorter).]

**Comment by adammertel** [comment]
@jancimertel 
IResponseDetail model extended by `usedInStatement` and `usedInStatementProps` properties,
`usedIn` property removed from IResponseActant
