### ISSUE TITLE
Finalize discussion on Statement fragments (incl. composite Statement-like Concepts)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#710]
- Statement-type composite Concepts such as "priests are greedy": should they be Concepts, decomposed just linearly into components "priests", "is", and "greedy", or should they be S entities, which allows structuring them syntactically? I think they should be S, because (1) if coded fully, they would be substatements (`S1: William believed - S2; S2: C priests - A are - C greedy`), and we would like structural (=> query) coherence on this, whether editors choose to code it fully with a substatement not using the composite, or they would use the composite.
- If S, it would be some special S' because of two (?) differences from normal S: they do not sit under any T and are not attached to any R. 
- If S', TBD whether statement templates should not be solved the same way, because neither one nor the other should be analysed as data (only their instances - i.e. S' entities used somewhere as actants, and derivatives of the template, which already have their T and R). Then the difference of S' from S (i.e. not requiring, in fact, disabling, link to T and R) might be marked by the boolean requested in #709.

Such S' could float in the same space as a normal entity does (i.e. unreferenced to a T or R).
To be solved if adopted: how to create S' (using Editor). Would require running the editor from somewhere else than a specific T.

**Comment by davidzbiral** [comment]
Copied from Slack: DZ says: "Já asi po úvaze stále jsem pro, abychom měli nějaké S', tedy S nevyžadující T a R a tvořené z editoru. Hlavní argument je strukturální stejnost konkrétní (tj. aby ten, kdo využije konkrétní kompozitum a kdo ho nevyužije, produkovali stejně strukturovanou datovou položku) a obecnou (tj. něco, co by se normálně dělalo substatementem, by se najednou nemělo dělat jiným typem entity, Conceptem, jen jako nějaký druh zkratky.
(Taky to umožní nedělat ten hack v Detailu, který taky považuji za problematický, tj. xy - has - subject - ...)
Takže asi stojím za svým návrhem zavést taková S, můžeme jim říkat S', ale rád bych to s Tebou prodiskutoval a slyšel případné nevýhody, a rád bych věděl, jestli by se nedaly spojit s templaty, protože je s nimi spojují dva významné formální rysy (podle mě i obsahové, ale pojďme uvést ty formální): (1) nenapojenost na R a T a (2) nechceme je prohledávat a zahrnovat, když děláme vyhledávací dotazy a datové projekce nad sesbíranými daty. Tudíž parsimonie velí mít je pohromadě jako S'.

**Comment by adammertel** [comment]
David, I believe that the data model is already prepared to adapt to both possibilities (composite Concept, or template Statement) so it is more up to you to decide. The disadvantage of using template statements for composites are

 - you will not have the ability to edit the actants in detail (or maybe this can be implemented later), 
 - the further analysis on ddb2 may be more complicated (but maybe I am wrong)
 - we will have to find a way to work with instances of a template statement instead of reusing the same statement (or am I wrong at this point?)

**Comment by davidzbiral** [comment]
@adammertel : 
Ad 1: The whole solution would only work if we can edit the content of S' somehow (at least for now, definitely in Editor - but probably forever in editor because only Editor has the full options). What could be the solution - will those S' have to sit under a new T created for that purpose, or do we have a different idea?
Ad 2: This is one of many DDB2 analysis issues - probably does not add much to problems we already have. I am fine with this.
Ad 3: This is the most important thing - I am afraid you are right, because we need to keep the link to the semantic relations of that S' (e.g. their superclass etc.). Which is a new feature not seen elsewhere in the data model.  It would be something like viewable but unchangeable attribute of the instance of S', saying that a given S (e.g. a given instance of "Guillelma is the Holy spirit") "clones S'1234" - and this clone relation could only be removed by unlinking the instance from the statement (technically usually if not always a substatement, i.e. statement which normally appears in the statement list under the given specific register = some T, and also as an actant in a S nearby).

We would probably give just admins the right to edit this "meta" T (content-wise special, but structurally normal).

**Comment by davidzbiral** [comment]
Agreed on meeting adammertel and davidzbiral, @adammertel please check I represent it well:
- we will introduce such statement templates;
- we will store the info on a statement (or any other entity) being created by cloning a template;
- we will copy the whole JSON structure of the template, e.g. the superclass "anticlerical attitude" for "priests are greedy", if the template has such superclass;
- but we will not maintain a permanent link (i.e. if the superclass of "priests are greedy" changes, the classification of instances = uses will not change automatically).

**Comment by adammertel** [comment]
This is probably not relevant anymore, right?

**Comment by davidzbiral** [comment]
Yes, this is solved by Statement Templates. Closed.
