### ISSUE TITLE
Data model visualization

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#711]
Very important for involving further programmers in parsing gsheets data, and for data management plan. Important part of documentation.
Replacing:
1) https://app.diagrams.net/#G1j2Vpq-zY63TT6Da3mUZLmzRTN_1TD3P5
2) https://app.diagrams.net/?state=%7B%22ids%22:%5B%221jJqyBql81_AFTUUEy7zaObR9vUXjqJIY%22%5D,%22action%22:%22open%22,%22userId%22:%22112328819777925297019%22,%22resourceKeys%22:%7B%7D%7D.

When updating no. 2 (Data model - complete.drawio), please also add names to "edges", i.e. what kind of relation e.g. a S has to an R etc.

**Comment by davidzbiral** [comment]
@adammertel : done?

**Comment by adammertel** [comment]
I think we can close this.
