### ISSUE TITLE
Levels of validation: change with message, highly recommended, recommended

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#712]
We can have two levels of being "bothered" by InkV to do some things - something like "required" vs. "recommended". E.g., "recommending" to set "sex" for any newly created Person (or even existing - when her Detail is opened?), but making valency and entity type "required" for any A type.
This is one way - another is to take everything as only recommended, but prompt editors to fill in visibly enough to put them in front of an explicit decision of filling it or avoiding to fill it in (but not allowing them to really forget by mistake).

**Comment by davidzbiral** [comment]
(Partly after discussing this with @rljshaw:)
- Some in-entity attributes are required in the sense of being pre-filled by defaults anyway. But no other required level 
- No metaprops will be required.
- We will want three levels of "recommendation": (1) even changing to some value and telling the user (e.g. #730 ), (2) prompting the user very visibly to do something - e.g. set sex metaprop for each P, (3) prompting them mildly. (Terminology of the 3 levels: TBD.)

**Comment by rljshaw** [comment]
I concur with this system

**Comment by davidzbiral** [comment]
I think the current direction of validation implementation supersedes this, but implicitly informed the direction. Closing now.
