### ISSUE TITLE
Icons for statement actions sometimes cannot be clicked upon

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#713]
Reported by @adammertel and I confirm it is not just his problem, I have it too - the icons sometimes disappear before the mouse reaches them. But not always - conditions unclear.
![obrazek](https://user-images.githubusercontent.com/55400794/149624692-f93460a4-efa6-452f-9cd9-c8529e04039a.png)

**Comment by Ptrhnk** [comment]
It will help to see whole layout when this happens. I was trying to replicate situation when buttons are not next to menu icon, but don't know how to recreate this.

**Comment by adammertel** [comment]
It happens to me also. I am not sure when, maybe this is a specific system/browser issue. The margin between the origin (menu icon) and the floating modal (button set) is a few pixels which make the interaction impossible. 
Maybe adding a few seconds timeout before the modal disappears?

**Comment by Ptrhnk** [comment]
I understand why is the interaction impossible, but position of buttons should always be next to icon. Timeout is only workaround but not fixing it. Looks more like some layout issue. Can you print-screen whole window when this happens?

**Comment by Ptrhnk** [comment]
Probably solved by CSS improvements in table. (wraping words in table header etc.)
