### ISSUE TITLE
Study InkVisitor-produced JSON file and match coding sheet parsing instructions with it

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#714]
The InkVisitor GUI will show you the variables in their structural logic, incl. the different cogwheels.
EDIT: now the deploy allows you to look at the JSON file of a statement, e.g. there, rather than the GUI - even better.

Then have a look at parsing instructions of [Kent Coding](https://docs.google.com/spreadsheets/d/1l7BLgUPx8t2SSQBGZKTH6V0BRTqBwMFLBdHirzQ-Mk4/edit#gid=1675499504) and make sure you understand what should end up where in the full data model ~ in InkVisitor interface.

**Comment by davidzbiral** [comment]
@tomaham : edited - looking at the structured JSON file of a statement does make more sense, probably.

**Comment by adammertel** [comment]
I believe it is my turn now to create visual documentation for the data model. Besides this documentation, it is probably quite hard to understand what is going on inside.

**Comment by adammertel** [comment]
@tomaham @davidzbiral 
Here are the data models for DDB1 https://drive.google.com/file/d/1bKvqEKr6JzPWryVg-vYudQy_4KvuzHS9/view?usp=sharing

All the dictionaries can be found here `InkVisitor/packages/shared/dictionaries`

**Comment by tomaham** [comment]
@vinnetu Making you part of the conversation.

**Comment by adammertel** [comment]
The visual documentation of the model was updated, considering the changes suggested in #721 721

**Comment by davidzbiral** [comment]
@tomaham : issue to be closed?
