### ISSUE TITLE
Create P, O, G, and E entities with status "approved" even without admin rights

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#721]
Some entities are pan-DISSINET and should continue to be submitted for approval to holders of admin rights: C, A types, R, T (or rather just root T if it can be differentiated), L probably (because some of them are also shared widely).

But some other entity types are highly contextual: O apples are always different apples in different depositions (just all are instantiated to C apple), E preaching of the heretics (always specific preaching events held by specific heretics, i.e. unless known to be the same, created as new E entity), just the same with Groups and Persons (few Persons will be cross-dataset). And there is no reason why to require admin approval for those - the result would be to forever have thousands of "pending" entities which nobody cares to approve. Therefore: if an editor creates P, O, E and G entity, set status as "approved" automatically, not as "pending".

TBD: non-root T. I would also like to allow approval by non-admin editors there, but would like to keep approval of root T in the hands of admins, if the two cases (root T vs. non-root T) can be differentiated.

**Comment by davidzbiral** [comment]
@rljshaw : do you agree with this feature request?

**Comment by adammertel** [comment]
I agree; this makes sense.
How about removing the status completely from everything except C, A, and R?
I do not see an added value in differentiating the 1st level T from others with T because of the status property. And most of the Ts on the 1st level is created by admin anyway.

**Comment by davidzbiral** [comment]
I think I agree - in fact I think we need approval **only for C and A**. Not even R (no reason why admins should approve of any new scan added as an R). Awaiting reaction from @rljshaw - once we have it, the implementation is approved.

**Comment by rljshaw** [comment]
Agreed from my side!

**Comment by davidzbiral** [comment]
@adammertel : approved. Only C and A will have "status", please implement.
