### ISSUE TITLE
Update IResponseDetail model and calls

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#722]
the first condition for #705

**Comment by adammertel** [comment]
@jancimertel
IResponseDetail model extended by usedInStatement and usedInStatementProps properties,
usedIn property removed from IResponseActant

**Comment by jancimertel** [comment]
done in 693 brach, tests pending, closing this issue

**Comment by adammertel** [comment]
IResponseDetail was once again extended :/

**Comment by jancimertel** [comment]
implemented independently
