### ISSUE TITLE
If prop type in user's non-default language is used, prompt user on prop type's actant involvement elvl; [EDIT: adding actant involvement elvl]

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#730]
If three conditions are met, i.e.:
1. the user has selected a default language in customization;
2. s/he uses an entity with a different label language (than the default one) as **prop type** of an in-statement (i.e. normal, non-meta) property;
3. s/he leaves the prop type's involvement elvl at elvl1-textual (rather than elvl3-inferential),
then change this prop type's involvement elvl from elvl1 to elvl3 (correct in 99% of cases meeting the 3 conditions) and signal it to the user (so that they can easily click it back - probably the way Google does, i.e. message in top right corner with the possibility to "undo": something like "The epistemic level of property type's involvement changed to "inferential". Undo").

Rationale: we are e.g. working in Latin but most prop types are in English: "occupation", "age class", etc. Having to change prop type involvement from elvl1 to elvl3 happens for almost all props and is very easy to forget, so this feature would assist greatly - in each statement normally it is 10 clicks.

Further notes:
- The overall rationale is similar to the default elvl3 that we have set in metaprops.

**Comment by davidzbiral** [comment]
@rljshaw : please review - I turned your note at the seminar into this issue.

**Comment by adammertel** [comment]
Moved to [#1707](https://github.com/DISSINET/InkVisitor/issues/1707)

**Comment by davidzbiral** [comment]
@adammertel This is now correctly implemented for automatic elvl switching from 1 to 3 in proptype involvement in in-statement props, but it is not implemented in switching in the same way the actant involvement elvl for normal actants in any role (s, a1, pa...) - see the G guests... in the screenshot.
Reopening, please implement the same thing (incl. the notification about this change at the background) also for actant involvement elvl. Ideally, edit the msg in such a way that it covers both proptype involvement elvl and actant involvement elvl. Tx!

![obrazek](https://github.com/DISSINET/InkVisitor/assets/55400794/a23cb9d8-cf2a-45a2-a009-18ecd270993b)
