### ISSUE TITLE
Create new deploy folder "data-import" with separate server, db and client

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#733]

**Comment by jancimertel** [comment]
waiting for admin to add proxy entry

**Comment by jancimertel** [comment]
conflicting npm tasks:
- i named it `import-remote-data-import`, in master there is similar `import-remote-importdata` to reflect url path `inkvisitor-data-import`

i used the one in 733 branch.

@adammertel any update from admin?

**Comment by adammertel** [comment]
I am sorry, the proxy should be working now.
