### ISSUE TITLE
Search layout / implementation

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#739]
![search layout](https://user-images.githubusercontent.com/29732281/151715879-ec087b67-e674-4e26-8631-07bdba95ec2c.jpg)

**Comment by davidzbiral** [comment]
- This seems a very strict-logic searc hwith no opportunities for "free search" - I guess a simple free search, the most used by most users e.g. in library catalogues and wherever it is available, will be most used here as well.
- Is any implementation of OR logic instead of AND planned within a variable? E.g. multichoice: statements whose author.

We need to sit down to discuss this. I have a different view of the search. E.g., I would not go through editor, author... but first through name, then further filter this name in author position only... i.e. more in the "add further filter" logic.

**Comment by davidzbiral** [comment]
Add "status" to search parameters - to find any with status "pending" or "discouraged". Implement multichoice. Attention to the design of the logic - where in multichoice it is OR, and where it is pseudo-multichoice and it is an AND.

**Comment by davidzbiral** [comment]
One major thing is the AND or OR logic. E.g., with props, you might sometimes want to find them with an AND, e.g. those everybody who is a weaver and at the same time a hereticus/a, and sometimes with an OR (e.g. a weaver or priest).

**Comment by davidzbiral** [comment]
Another major search need is to search through
- **superclasses**, e.g. find all entities who "has - C superclass - C fruit" (will find: apple, pear, cherry...);
- **class/instance** relationship, e.g. find all O which "has - C class - C apple"
- combination of both, e.g. find all O which "has - C class - [x]" where [x] - has - C superclass - C fruit.
This will be some of the most common searches. I know InkV is not a db manager, but it is a major interface between historian coders and the DDB, and so such basic queries without knowing ReQL (RethinkDB query language) will be needed. 
And I am not sure whether your granular interface has thought about superclass trees.

**Comment by davidzbiral** [comment]
Allow - probably you plan it? - searching for prop value while leaving the prop type search field unspecified.

**Comment by davidzbiral** [comment]
Add possibility to download search results in JSON.

**Comment by pondrejk** [comment]
![navrh](https://user-images.githubusercontent.com/8287578/153562457-4b488688-bb00-41fe-ae30-622c55193b5e.png)
Mockup based on this weeks discussion with D+A

**Comment by adammertel** [comment]
@davidzbiral is this ok? Do you have some ideas or comments?

**Comment by adammertel** [comment]
Based on the changes in mockup - rewrite ISearch models

**Comment by davidzbiral** [comment]
@rljshaw : Any ideas for something else needed in Search? 
See also https://docs.google.com/document/d/1Rgg5JJXQjSpl99OJ2KUo6UwBDla1vU65jlgDpiP-VY8/edit; there is an ongoing discussion how much InkV should be used to search DDB1 on top of "finding the right entity to use in my coding".

**Comment by Ptrhnk** [comment]
(for dev) consider react window - scroll handler for search results
