### ISSUE TITLE
Actant -> Entity naming

### ISSUE THREAD

**Issue by jancimertel** [DISSINET/InkVisitor#740]
rename all symbols, all fields to encompass transition from Actant -> Entity.

This should cover models, routes, db data and also the client + api calls(endpoints)

**Comment by jancimertel** [comment]
@adammertel please note, that in Position enumerator ive changed values from a1, a2 -> e1, e2.
Possibly the import script (parse) should be checked

**Comment by adammertel** [comment]
Good point, I agree

**Comment by jancimertel** [comment]
closing this issue, already in dev branch
