### ISSUE TITLE
Create folder for container components

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#741]
Components folder now has visual components with basic logic.
There are couple of components which add api calls to basic components (EntitySuggester, EntityTag, UserSuggester).
It would be nice to categorize them to some folder (e.g. Containers) as we use them across the interface.
Now It's in MainPage/containers which fits more for individual boxes.

**Comment by adammertel** [comment]
@Ptrhnk relevant anymore?

**Comment by Ptrhnk** [comment]
Solved by different categorization
