### ISSUE TITLE
Emphatize template == true attribute value for Tags, Detail, and Suggester

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#753]

**Comment by davidzbiral** [comment]
@adammertel : I do not understand this issue, can you develop?

**Comment by adammertel** [comment]
No, I forgot what was this about :D
Probably something visual? Something like make the Tags that have "template" true visually more appealing so you can recognize them easier?

**Comment by davidzbiral** [comment]
I think this was indeed about:
- display (and change) the template True/False attribute in Detail;
- add this parameter to Search;
- design a visuall way to tell these S' (S with template = True) from regular S in "tag" (this is how you call the usual element produced by e.g. suggester and displayed in editor, I think).

**Comment by pondrejk** [comment]
not much options left for tag styling, we already use field and outline color and outline style for other purposes. We can either add an additional symbol to mark a template, or play with the color background of the tag -- maybe one of these options:
![tagbg](https://user-images.githubusercontent.com/8287578/161613287-4ecd7b34-0651-4600-b1d7-d219b18a818d.png)

This approach reduces the readability of the letter, but on the other hand it should stand out without introducing new color

**Comment by davidzbiral** [comment]
Good reminder that any entity can have the template atribute = True, not just Statement templates.

I like the most the one with diagonal (3rd from end) - with the idea that it is only half-filled-in, i.e. a template. Let's go for it for templates then, @adammertel?
