### ISSUE TITLE
add `_legacyId` to the entity model

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#766]
The legacy IDs identify in a strange way any legacy data: e.g. T3 or C0001 vs. 381e9980-dc64-4004-9051-a3653cd15804.
Is it not a good idea to keep the legacy IDs for further identification, but hidden, in some "old ID" field, and assign a more DDB1-compliant ID to them?

**Comment by davidzbiral** [comment]
@adammertel : Any comment to make this moving?

**Comment by adammertel** [comment]
One solution would be to add the old id to the notes.
But then, this should not be changed in Inkvisitor as it may disrupt the continuous GSheets parsing.
Another solution is to extend the data model, but I am not sure if this is a systematic solution.

**Comment by davidzbiral** [comment]
@adammertel : In any case we must count on the fact that we will **import old data gradually**, and so an A0001 or L0001 must match the right one, already recoded to the "long" URI.
I definitely exclude putting it to notes. Too dangerous and even difficult to parse when matching new parsing batch to the entities.
Either (A) we extend the data model with some InkV invisible "Gsheets entity ID", or (B) we accept as it is, i.e. that those imported will be atypical. 
I am quite reluctant around B, because my school of data management strongly advises that the IDs do not bear any semantic information, while here it bears a lot of information: 
- entity type (there is the possibility, albeit it will be just a couple of cases, that we will need to switch entity type, and then the C, E, O etc. in the ID becomes really spurious.
- The fact that this is imported from old data is forever shown instead of being hidden only in the log etc.
Therefore, let us opt for (A) - extend the data model with an attribute "GSheets entity ID", and let us match the newly parsed gsheets data always with this ID but assign a new, full, DDB1 ID.

@tomaham : tagging you because it is important for the parsing, and for you to have your say too.

**Comment by adammertel** [comment]
Okey, so adding a new attribute to the Entity model? Something like `_lagacyId`?

**Comment by davidzbiral** [comment]
Yes, `legacyID`. Let us go forward with it. 
@tomaham , will you be able to implement this, i.e. assign somehow the db hash to the new entities when parsing and keep the old ID in `legacyID`? (Which will not be displayed in InkV.)

**Comment by tomaham** [comment]
Yes, sure.
