### ISSUE TITLE
Bug in Suggester search algorithm

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#768]
If I search for "trp started", Suggester finds nothing, while it should find three entities having these words in the label (and that can be found by "started" alone). E.g., it does not match "TRP started during", while it should.

![obrazek](https://user-images.githubusercontent.com/55400794/153352625-d8735ffc-9c25-4f44-bab9-c86489c6a242.png)

**Comment by adammertel** [comment]
@jancimertel Is there a possibility to implement a string similarity algorithm (Levenshtein distance) inside `r.filter` in the database query without causing any crucial reduction in speed?

**Comment by davidzbiral** [comment]
@adammertel I restate the need for change here. E.g. if I search for "is" Action type, it does not change it, and so the user will create a new one. **The search algorithm is too tolerant, searching too much within the entity. Change it to something which is stricter on the left**, i.e. prioritize in Suggester search results (or require) the beginning of the string. This way, when searching for "is", I will find "is" and non "misit", "subrisit" etc.

**Comment by jancimertel** [comment]
[Uploading search.mkv…]()
what about this?

**Comment by jancimertel** [comment]
[Uploading search.mkv…]()
what about this?

**Comment by jancimertel** [comment]
https://user-images.githubusercontent.com/10438157/162617494-6693afec-2cff-476f-8ddc-f3514899c4bf.mp4

what about this?

**Comment by davidzbiral** [comment]
@jancimertel : very nice, we want this :-) Can you make the same wildcard also in Suggester? I think the search algorithm should be the same in Search and in Suggester.

**Comment by davidzbiral** [comment]
Another instance of the bug: if searching for "Sentences Caux", I do not find the T entity "Sentences of Bernard of Caux and John of Saint-Pierre".

**Comment by jancimertel** [comment]
> @jancimertel : very nice, we want this :-) Can you enable the same wildcard also in Suggester? I think the search algorithm should be the same in Search and in Suggester.



> @jancimertel : very nice, we want this :-) Can you enable the same wildcard also in Suggester? I think the search algorithm should be the same in Search and in Suggester.

yes, sorry, the suggester/search should work the same way

**Comment by jancimertel** [comment]
> Another instance of the bug: if searching for "Sentences Caux", I do not find the T entity "Sentences of Bernard of Caux and John of Saint-Pierre".

This is expected behavior when using such database querying. As it has been mentioned somewhere, similar searching should be implemented in search index ie. elasticsearch. I can mimic it to some degree using only db+backend.
