### ISSUE TITLE
Remake Reference in data model into Prop (and its Part and Type in 2nd-level Props) in S-R and T-R relations

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#770]
Under each Resource for a Statement, we now have Part as a free text field, and Type primary/secondary as dictionary-based value.
But we need to remake the data model here because completely similar structures appear in Detail, where metaprops are the only reasonable place to store it. 
There, the structure must be:
`MP1: T this text - A has - C edition - R Duvernoy, 2001 |||
MP1.1: MP1 - A has - C2320 page or folio range - V 12-21
`   

For symmetry with those metaprops we need, and for fuller semantics, we need that:
- The relation between S and R becomes a prop (GUI implicit, data model explicit; Statement prop, not action prop), i.e.: Statement - has - C resource - R XYZ, of which the user should only see the "R XYZ" part in the GUI, and in the same section as now.
- 2nd-level prop is allowed underneath this prop-type relation, which will allow to hold part - with prop type C2320 page or folio range prefilled, and V as pre-selected entity type.
- Therefore, it also makes sense to make the Type primary/secondary a 2nd-level prop, but keeping the current assistance, i.e. solving it in the GUI by the simple switch. But in data model terms, it will be a 2nd-level prop.

Unfortunately needed to start working and for parsing, i.e. putting it into 1.3.0.

**Comment by adammertel** [comment]
@davidzbiral also here - please give me a call ideally to explain what is needed to be achieved.

**Comment by davidzbiral** [comment]
**Why not to go the References way in Detail of Ts**
During a call, @adammertel suggested making it coherent the other way around, i.e. under Detail of a T, have a new References section similar to what we have in Editor (see below).

This will not work completely well because there is (1) several references we need to make under a T: to (a) manuscript witness 1-n, (b) printed edition 1-N, c) digital edition 1-n, so there would be several forms of representation of a T, and we will need to extend and change the dictionaries as we go (e.g. we would like to create "digital edition in XML/TEI" as a subclass of "digital edition" as we find one). I.e., we editors would appreciate the flexibility of props here, i.e. (i) creating them as we go without asking somebody for dictionary updates, and (ii) relating the prop types semantically (e.g. "digital edition in XML" - has - superclass - digital edition; which in turn has the superclass of "edition".
![obrazek](https://user-images.githubusercontent.com/55400794/155363684-2cfb0816-358d-48f1-8962-8ba0cd0bd6ab.png)

But I understand the intention to keep the GUI and the data model close (even if we will need more assistance since 1.4 anyway, which will make the database (JSON) and the GUI diverge anyway). Therefore, OK, let us go with Adam's solution - handled in issue https://github.com/DISSINET/InkVisitor/issues/797. Closing.

**Comment by davidzbiral** [comment]
@adammertel and @davidzbiral debated this on 3 March 2022.
Results:
- In T-R relations, we will do it with metaprops, i.e. as I write (incl. 2nd-level props for page ranges etc.).
- In S-R relations, however, we will keep the current system. Adam acknowledges that it is structurally quite similar to the T-R relation set out above, but sees DDB1 as collected data database, not primary communication format, and wants it to be as easy as possible and as close as possible to an efficient GUI; he sees bringing this S-R relation in line with T-R relations as a candidate for DDB2 transformation.
We agreed on this. Closing.
