### ISSUE TITLE
New in-entity attribute: WordNet synset ID

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#787]
For A and C, implement a new in-entity attribute "WordNet synset ID". 
We have been talking with @adammertel some time back about it but never in a more specific manner. Will be important for matching same meanings of different Cs and As (different lemmata).
Actually in a multilingual database, such as ours, it would be much better to store (1) lemma-meaning relations, but store (2) semantic relations only between synsets rather than between language-specific lemma-meaning units such as a specific C or a specific A :-(

**Comment by adammertel** [comment]
I am sorry for being lost :) Could you maybe give me a call to explain me what you want to achieve so I am able to implement it into the model?

**Comment by davidzbiral** [comment]
Simplified after meeting with Adam:
For A and C entities, add two new attributes:
- WordNet lemma
- WordNet synset

**Comment by adammertel** [comment]
Duplicate to #803

**Comment by davidzbiral** [comment]
Closing this.
