### ISSUE TITLE
Update data model diagram and dictionary to match v. 1.3

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#788]
After implementing all data model changes which still go into v. 1.3, update also the (minimal) documentation in the form of the data model diagram.

**Comment by adammertel** [comment]
@tomaham @davidzbiral 
Data model [Diagram](https://app.diagrams.net/#G1bKvqEKr6JzPWryVg-vYudQy_4KvuzHS9) was updated:
 - `IReferenceStatements` model
 - `_legacyId` attribute added to IEntity model
 -  `isTemplate`, `usedTemplate` and `templateData` attributes added to IEntity model
