### ISSUE TITLE
Write short text on database backup

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#799]
For our sound sleep - necessary!
How.
Where.
How often.

**Comment by jancimertel** [comment]
On the host machine, there is a data disk mounted (/data-disks) with script + backup archives.
From now on, it will run once per day, will keep archives up to 3 days and archives created for first day of the month (2022-01-01, 2022-02-01 etc)

I've created a readme file in `/packages/database/README.md` with additional text

**Comment by jancimertel** [comment]
an important note: rethink backup cannot work with databases which contain hyphen in their name.
So we should rename inkvisitor-<suffix> to inkvisitor_<suffix>.
