### ISSUE TITLE
"Copy entity" function in Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#805]
Use case: there is a nicely filled entity. I want to make a new one similar to it, or I want to make a template out of it.

Therefore, in Detail, we need a "Copy entity" button, which will create a new ID with a full copy of the JSON: copy all attributes (incl. links to gazetteers, treebanks etc.) and metaprops.
The user can then edit: change things, add/delete metaprops etc.

When copying S, it is probably the same function as copy in Statement list - remember to keep those two places to do what probably is the same thing coherent somehow.

**Comment by davidzbiral** [comment]
@adammertel : Is this not implemented in the "duplicate" button already?

**Comment by adammertel** [comment]
Yes, the "duplicate button both in the statement list and the detail show have this function. 
I will close now, feel free to reopen if you needed something else...
