### ISSUE TITLE
Create `database_backup` folder under DISSINET GDrive and allow access to dissinet.noreply@gmail.com

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#811]
Daily backups of all databases can be then send here.

**Comment by davidzbiral** [comment]
@adammertel : not necessarily everybody having access to the DISSINET gdrive should have access to the data (against user rights). I guess, let us make it under my personal GDrive?

**Comment by davidzbiral** [comment]
@adammertel : Created in https://drive.google.com/drive/u/0/folders/1RhE9b3CsqbVLbuzcRBof5wz5_ve91LQl
The name is ddb1_backup (because there are other backups, and DDB1 is a clear name of what it is).

**Comment by adammertel** [comment]
Thanks, @davidzbiral, I created a new issue to proceed with this #817.
