### ISSUE TITLE
language enum for French, German and Italian 

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#822]
To add these languages to the system, just the enum Language dict in index.ts in ./enum  should be extended? (or more things needs to be done?)

...
  Italian = "ita",
  French = "fra",
  German = "deu"
}

DZ edit: also "Middle English" needed for , ISO code "enm".

**Comment by davidzbiral** [comment]
@tomaham: in Concepts and/or the upcoming Statement Templates (S'), label language of some will be Middle English (vs. [modern] English). Please count on this while parsing - adding "enm" requested by editing your post.

**Comment by tomaham** [comment]
@davidzbiral Well, this is more general inkVisitor responsibility- if the typescript held data model can work with  "enm" (it will allow the language as valid content of the property), then the parsing will.

**Comment by adammertel** [comment]
Extending the enums needs a change in two places:
 - `shared/enums/index.ts`, where `enum Language` needs to be extended as:
 - and `shared/dictionaries/language.ts`
 
 You can extend them anytime, but `enum Language` values should stay the same once when declared (e.g., changing the code of Czech language from "ces" to "cs") - these values are used within the database.

**Comment by adammertel** [comment]
French, German, and Italian languages were added to the dictionary. Middle English was already added.
