### ISSUE TITLE
ResponseDetail has wrong keys in entities.

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#830]
Instead of taking the id from the entity model, the `entities` uses some kind of index (?)

![image](https://user-images.githubusercontent.com/12932677/159080348-4d449eff-f3e4-4ce1-92df-d59ad70e7951.png)

**Comment by jancimertel** [comment]
fixed in #829 (b8b83e652631df89386a5b3e5c4cf63a698739d1)
