### ISSUE TITLE
Stage  inkivisitor-data-import - deploy DEV branch there

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#846]
Could you deploy the dev branch directly on the DISSINET server to the inkvisitor-data-import stage?

At the moment, at https://dissinet.cz/apps/inkvisitor-data-import/ there is some older dev version.

**Comment by adammertel** [comment]
@pondrejk could you please take a look at this? `dev` should be deployed on `data-import` the same way as it is deployed on `staging`
