### ISSUE TITLE
Suggestion:  make the version in the header logo reflect the state of the code

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#847]
Suggestion: could the version in the header logo reflect the state of the code, i.e. the branch and the last commit signature?  It would make my life and possibly some future lives easier in case of uncertainty "what version am I running now".

![image](https://user-images.githubusercontent.com/3739529/159435794-7ec9cedd-d391-4d98-9f58-553f538503c7.png)

**Comment by adammertel** [comment]
This is a great point. 
@pondrejk is it possible to set the GitHub action to update the version of the package.json each time it is merged, built, and deployed?

**Comment by pondrejk** [comment]
settling with the timestamp for now
![Screenshot from 2022-03-28 22-34-36](https://user-images.githubusercontent.com/8287578/160484641-89e21700-a4bf-4e42-aea3-13aa98461c88.png)
