### ISSUE TITLE
Question: pm2, app processes and DISSINET server

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#848]
Under what user does the automatically deployed app run on the DISSINET server?

From the docs, it seems pm2 is used? But if I understand this correctly, this ties the app and pm2 process to the user, which starts it. Do we have a setup, where it is possible to access the process externally?

E.g., can I see, restart ... etc. the app processes as tomash user on the dissinet server?
(Use case: I thought about the manual  update of the inkvisitor-data-import stage, and I realized I do not have access to the apps processes.)

Connected topic: 
https://sobus-piotr.medium.com/pm2-share-the-same-daemon-process-between-multiple-users-dd7ecae6197a

**Comment by adammertel** [comment]
@jancimertel could you please look at this?
I think, in long term, podman is a better solution, right?

**Comment by tomaham** [comment]
I could be out of the real state of things, I just read package.json file in the deployed app on the DISSINET server, where there are reference of using pm2. 
`{
  "name": "server",
  "version": "0.1.0",
  "scripts": {
    "build": "tsc --build tsconfig.prod.json",
    "lint": "tslint --project \"tsconfig.json\"",
    "start": "node -r module-alias/register ./dist/server/src --env=prod",
    "start:sandbox": "node -r module-alias/register ./dist/server/src --env=sandbox",
    "start:stage": "node -r module-alias/register ./dist/server/src --env=stage",
    "start:dev": "nodemon",
    "pm2:prod": "pm2 start npm --name \"inkvisitor-server\" -- start",
    "pm2:sandbox": "pm2 start npm --name \"inkvisitor-server-sandbox\" -- run start:sandbox",
    "pm2:stage": "pm2 start npm --name \"inkvisitor-server-staging\" -- run start:stage",
    "restart:prod": "pm2 restart inkvisitor-server",
    "stop:prod": "pm2 delete \"inkvisitor-server\"",
    "restart:sandbox": "pm2 restart inkvisitor-server-sandbox",
    "restart:stage": "pm2 restart inkvisitor-server-staging",
    "jwt": "ts-node -r tsconfig-paths/register ./src/scripts/jwt.ts",
    "test": "jest -w 1 -t"
  },`

**Comment by adammertel** [comment]
I agree with the point that `pm2` is horrible. We plan to replace it with something else - e.g., `Podman`
