### ISSUE TITLE
improve lifecycle of editor props - dont delete suggester concepts when adding other tags

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#856]

**Comment by Ptrhnk** [comment]
Wrong behavior
https://user-images.githubusercontent.com/29732281/161936805-9c9afe1e-f94e-4136-b671-f81636405d14.mov

**Comment by Ptrhnk** [comment]
Correct behavior
https://user-images.githubusercontent.com/29732281/161936926-e0c93d49-e6dd-4fb1-8ef2-a343c13f9147.mov

**Comment by Ptrhnk** [comment]
https://user-images.githubusercontent.com/29732281/161937041-212a321b-51e2-4129-ae4d-a1b25d6f8367.mov

**Comment by Ptrhnk** [comment]
https://user-images.githubusercontent.com/29732281/161937167-19f4e342-d5e9-4d30-bfb0-8ba989347681.mov

Correct behavior

**Comment by Ptrhnk** [comment]
Doesnt matter if adding new or selecting, its the same concept. We need to handle this in editor.

**Comment by Ptrhnk** [comment]
https://user-images.githubusercontent.com/29732281/161988607-07ea5bcb-f261-4c71-860d-219bda737fe0.mov

It's also closing attribute modal. This is definitely needs refactor.

**Comment by davidzbiral** [comment]
I only confirm the issue - let's fix.

**Comment by Ptrhnk** [comment]
Also #845

**Comment by Ptrhnk** [comment]
@davidzbiral 

> Screen.Recording.2022-04-06.at.15.42.42.mov 
> It's also closing attribute modal. This definitely needs refactor.

Okay I fixed closing modal by unlink or selecting existing entity from suggester. Now it only closes attr. modal when new entity is added and focus is moved to new detail in detail box.
