### ISSUE TITLE
dev at deploy data-import:   deleted territory triggers "missing id" messages

### ISSUE THREAD

**Issue by tomaham** [DISSINET/InkVisitor#866]
When territory is created and deleted,  improper "missing id" alter messages are triggered.
(When just older existing territory is deleted, this is not happening)

See gif
![MissingIdd](https://user-images.githubusercontent.com/3739529/160453315-274ee0fe-9725-44f5-b9d3-10c99ca3f002.gif)
.

**Comment by Ptrhnk** [comment]
It's on BE @jancimertel will solve it.
