### ISSUE TITLE
Find a GUI solution for interchangeable entities

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#870]
The following relations state the near-interchangeability (aka synonymy, equivalence...) of entities:
1. Ontological identification done through **C0691 identical entity** metaprop, e.g. L David's boat - has - C identical entity - O David's boat (the L can become a place of an action, and thus sit in a slot which requires an L entity, while the O can become e.g. the object of sale). Or P Pathau - has - C identical entity - P Rajmund Clergue (for identification of initially two different Ps who turned out to be the same person, or for whose identification an editor, while aware of their identity, prefers a defensive approach and wants to keep the two identities separate but identified through a statement - possibly with some certainty attribute; which is actually a good approach if there is a semantic nuance).
2. Cross-language equivalence done through **C0944 equivalent** metaprop: L Parigi (it) - has - C equivalent - L Paris (fr). This concerns any entity type.
3. In-language synonymy, also done (A) either through **C0944 equivalent** metaprop (recommended, because we thought that it is better to use the more general relation since whether it is cross-language equivalence or in-language synonymy can be told from the label_language attribute of the two entities) or (B) by **C0943 synonym** (not recommended). This third type concerns A and C. This is very important because we have a strict understanding of synonymy, i.e. synonyms are only synonyms if they share superclass trees and WordNet synset numbers (and we must be able to check this easily, or restore the tree in some future view).
4. Interchangeability defined by having the same identity in the entity's Reference relation to a Resource: e.g. GeoNames ID or, more crucially for us now, WordNet ID (but solve generally already now, i.e. not just for WordNet but for the Reference data model as a whole).

It is important for editors' to have easy, almost imposed (very visually prominent) access to the interchangeable entities so that they can: 
A. Choose the more correct (e.g., main, most suitable) entity, e.g. fr. Paris rather than it. Parigi - i.e. kinda impose fr. Paris even on those who searched for Parigi - not hard-impose but make it very visible.
B. Revise whether the semantic relations hitherto stated really hold, or needs revising, upon each use of the entity. This is especially important in Actions and Concepts, because they serve to grasp the meaning of a coded source.
C. Understand those relations because this enhances the editors' understanding of the data.

I suggest to solve this in the mouseover which shows full `label` and `detail`. Apart from these, show now, as a third "line": any entities (as further suggester element, just without mouseover option?) which meet any of the above-stated relations to our entity.

In #827, I request a good view of the superclass trees - try to solve the two somehow together. Superclass tree (taxonomy) could be another line in the detail.

EDIT: this will probably be solved as part of #1042.

**Comment by davidzbiral** [comment]
@rljshaw Please cross-check my reasoning and clarity of expression, tx!

**Comment by rljshaw** [comment]
Checked and confirmed that I agree with you summation and GUI proposal!

**Comment by davidzbiral** [comment]
@adammertel and @Ptrhnk, please read this, it is an important one for thinking about the data model and the GUI.

**Comment by davidzbiral** [comment]
We will probably solve this by **reserved semantic relations** and possibly **reserved ontological relations**.

**Comment by davidzbiral** [comment]
I think this is solved well now by the features of Relations (such as reciprocations in Detail, tooltip).
