### ISSUE TITLE
Add logo of GAČR and ERC

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#886]
Add visibly but nonobtrusively the logos of GAČR and ERC - see https://dissinet.cz/ footer. EU flag, ERC, and GAČR - those are enough.

**Comment by adammertel** [comment]
@davidzbiral is it okey to put the logos into the About popup window? #581
Or do they need to be visible all the time? 
Motivation: those logos are quite large and they may not fit into the layout easily.

**Comment by adammertel** [comment]
ERC logo
https://cdn.muni.cz/media/3299268/logo_erc-flag_eum.png?mode=crop&center=0.5,0.5&rnd=132594368580000000&width=278

GAČR logo
https://cdn.muni.cz/media/3299114/gacr-en_rgb.png?mode=crop&center=0.5,0.5&rnd=132594286110000000&width=278

**Comment by davidzbiral** [comment]
@adammertel : solution (i) is fine - into the About window.
