### ISSUE TITLE
Withdraw the 4-character limitation on search string and review search algorithm

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#887]
- Just as in Suggester, also in Search we need to search up even shorter than 4-character expressions. Withdraw the limitation there.
- Review search algorithm: I think that for transparency and user-friendliness, it should be the same as in Suggester (see related issue). You can search whole word starts, no need to search internally, e.g. "is" is _not_ meant to find "d**is**sidence" - we don't expect or request such a functionality (if we do later, it will be through some wild card character for left-side truncation, e.g. "*").

**Comment by Ptrhnk** [comment]
@jancimertel Allowed it on FE, needs to be implemented on BE now.

**Comment by jancimertel** [comment]
restriction altered, required at least 2 chars to do the search.
