### ISSUE TITLE
Territory move doesn't work

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#888]
![obrazek](https://user-images.githubusercontent.com/55400794/162569736-2ba336c7-b0e6-4e82-9f48-2b976cdf3574.png)

Perhaps this is happening because no order is assigned upon parsing and the Ts are imported? So all of them have order "0" or something like that?

v. 1.2.0 | data-import | built: Fri 08.04.2022 00:51

**Comment by jancimertel** [comment]
that has been the issue previously. currently on development it works right after the import, i suspect data-import has different dataset.

the domain looks unresponsive for some reason right now, will test it tomorrow on data-import environment

**Comment by jancimertel** [comment]
Reimported and tested - should work now. Closing now - reopen please, if issue reemerges
