### ISSUE TITLE
Resizing boxes highlights text

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#892]
Bug: if I use the resize vertical line between Detail and Editor, besides resizing, it highlights texts in the browser window. (Observed in latest Firefox.)
![obrazek](https://user-images.githubusercontent.com/55400794/162573436-f836d2dc-3c8b-4778-94fe-5fd88ae87a95.png)

**Comment by davidzbiral** [comment]
@Ptrhnk : I would probably allow copying, if it makes sense:
- label text in entity tags;
- version the app header (version & build) for easy communication where sb was testing something;
- some structured copying of the modal with prop attributes (can be done with a button).
None of this is completely vital, just seems logical to me.

**Comment by Ptrhnk** [comment]
### Allow copying:

- [ ] label text in entity tags;

- [ ] version the app header (version & build) for easy communication where sb was testing something;

- [ ] some structured copying of the modal with prop attributes (can be done with a button).

None of this is completely vital, just seems logical to me.

**Comment by Ptrhnk** [comment]
@davidzbiral I created #977 and #978 because this is about solving bug so I can close this.
