### ISSUE TITLE
V entities left border missing

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#893]
Observed in Detail, if not elsewhere.
![obrazek](https://user-images.githubusercontent.com/55400794/162573541-809e63d8-02a7-4de5-997f-4adfb6e01bb6.png)

**Comment by Ptrhnk** [comment]
I can't see where it is, is it in meta props?

**Comment by davidzbiral** [comment]
Yes, in metaprops propvalues in Detail box.

**Comment by davidzbiral** [comment]
@Ptrhnk : Hey, I think it I see the condition when it happents: it happens in prop value in _2nd-level_ metaprops.

**Comment by Ptrhnk** [comment]
@davidzbiral This is generic sign. Isn't it marked as generic? I can see it only when I put generic logical type on.

**Comment by davidzbiral** [comment]
I see. I will ask Tomáš why this is "generic" - it should be "definite".

**Comment by Ptrhnk** [comment]
@davidzbiral Ok, so its solved by data import. I'm closing it.
