### ISSUE TITLE
Do not propagate page ranges between different editions of a T (= do not propagate a 2nd-order prop between two different props)

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#894]
T entity [Register FFF](https://dissinet.cz/apps/inkvisitor-data-import/#detail=06a4644d-85a7-4d8b-ba23-0c6851346598)  shows a spurious propagation of page ranges between two different editions, i.e. edition_1, edition_2 etc. if page range of one of them is empty. (BTW It is usually empty because the whole book is the edition.) This probably shows that the parsing script spuriously propagates a 2nd-order prop between _two different_ props.

![obrazek](https://user-images.githubusercontent.com/55400794/162573644-c24d84de-bc7f-4fce-8511-bed5f8e6a9e8.png)

Here, in source data, the page range 290-298 is only given for edition_2, i.e. [Blaquière & Dossat, 1968](https://www.zotero.org/groups/446972/david_zbiral_bibliography/items/itemKey/6W5S9CE9/). It should not be propagated to edition_1 which has page range empty.

BTW: By contrast, parsing manuscript witness M22, M23 and M24 (see screenshot above) is correct, because it is a _multiple in one cell_, i.e. there, propagating the folio number in 2nd-order is correct - cf. the difference between the two notations:

(A) _One and the same_ manuscript witness running through three books with multiple used:
![obrazek](https://user-images.githubusercontent.com/55400794/162573768-3af23a30-9857-41c6-b4c9-31dceb7c3865.png)

Versus (B): _Two different_ editions in different cells:
![obrazek](https://user-images.githubusercontent.com/55400794/162573836-49c91d63-91d4-49d1-8e3c-da6e0b356871.png)

(BTW The use of multiple for multi-volume manuscript in (A) will disappear soon in a new batch; this lengthy explanation was only to say that **propagating 2nd-order props for page range between _two different_ editions should not happen, while propagation of a 2nd-order prop of _the same_ prop should affect all the "decomposed" props coming from a multiple**.)

**Comment by tomaham** [comment]
Fixed. This was a nasty one...  As a side effect, there is a new log table for props , https://docs.google.com/spreadsheets/d/1UpbJckLrRYTCz7wcEYhhcc-ihJxiUENx1unCCQqE4TE/edit#gid=581544631  .
