### ISSUE TITLE
Change the default label of root T from "everything" to "root"

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#898]

**Comment by adammertel** [comment]
@davidzbiral this is only about the label of the root T, right? 
@tomaham this is maybe relevant for you.

**Comment by davidzbiral** [comment]
@adammertel: yes, about the label of the highest node in the hierarchy.

**Comment by adammertel** [comment]
@davidzbiral thanks. This is changed on my side
@tomaham please check it also and close it after then :)
