### ISSUE TITLE
Leave the entity tag with its label displayed when scrolling down through Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#899]
It often happens that you scroll down through the Detail of an entity and when returning to the window or reading further, you don't know any more what entity you are looking at, and thus need to scroll up again to check. Therefore, redesign the placement of the entity tag. My suggestion would be to put the entity tag not under but side by side with the heading "Detail". It reads nicely (as if "Detail of entity 'Process against the Guglielmites'.) 

Another added value of not hiding the entity tag by scrolling down the Detail box is good access to draging&dropping the entity directly - after the user has studied what it is - without forcing him to scroll back up.

![obrazek](https://user-images.githubusercontent.com/55400794/162580230-94402270-8d02-4b1c-9672-6e3cb7ae05f5.png)

I understand it poses the question of where to put the duplicate, remove, and refresh buttons, so I tag you @adammertel to consider the best solution, but you can transfer to somebody else.

**Comment by Ptrhnk** [comment]
@davidzbiral That's a good idea! I think we can left buttons as they are and simply left whole row displayed.

**Comment by davidzbiral** [comment]
@Ptrhnk I agree.
