### ISSUE TITLE
If an R entity is created from the suggester under Statement / References, display it in the Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#902]
Normally, when I create a new entity from the Suggester, it is immediately displayed in the Detail, which is desired behaviour.
Make this happen also when I create an R entity from the References R slot - for some reason this is not happening.
![obrazek](https://user-images.githubusercontent.com/55400794/162580793-3c2a2b21-29e0-4b25-8a82-30e02cf4cda6.png)

**Comment by Ptrhnk** [comment]
Yes, but it's desired only when you create it from suggester in editor right? Cause when you create it from detail and switch to it, it will interrupt you work I guess.

**Comment by Ptrhnk** [comment]
@davidzbiral implemented as I wrote, if you don't agree it's easy to change now.

**Comment by davidzbiral** [comment]
@Ptrhnk You are probably right. In the near future, Detail will have tabs, and so the R will open in Detail even if created from Detail - just in a different tab. The user will remain where they are, but a new tab will be added with the created R entity. Can you please note this down (as a new issue?) where you have the new Detail with tabs?
