### ISSUE TITLE
Bad handling of unauthenticated access

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#905]
If I access an InkV entity link, e.g. [this one](https://dissinet.cz/apps/inkvisitor-data-import/#detail=0360e403-f8aa-44a7-95e0-677885401b80), from a browser window where I am not logged in, I should get to the login page. Instead, I get an empty InkV window and duplicates of one and the same error message.

Of course, after authentication, bring the users to the entity they wanted, not to the basic window.

Error message: if this error message is still needed (I doubt it though, if you take the user to the login page, none is needed), please give more detail here than just "Unauthorized". E.g. "User not logged in" (or whatever is the most common in this situation). Avoid the word "unauthorized"; whether they are authorized, you do not yet know - the user may be morally authorized, just he hasn't proven it yet by inputing their credentials.

![obrazek](https://user-images.githubusercontent.com/55400794/162602485-e5f4af82-4213-461a-9e9a-d9265b61d9bc.png)

**Comment by Ptrhnk** [comment]
@davidzbiral I'm not able to replicate it now, looks like it's already fixed. Can you check again to confirm please?
I tried to open it in new browser for the first time and behavior was correct.

**Comment by davidzbiral** [comment]
This does not happen at this point, probably it was some error just in an older version and is now fixed.
