### ISSUE TITLE
Search box: 2 characters not working

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#906]
Thanks for changing the minimum of 4 characters to 2 in Search. But there is a bug: if I search the verb "is", I do not find the A type "is" in Search. (In Suggester, I now do find it. I was suggesting that the basic search algorithm in Search should be the same as in Suggester: it is the least confusing to the user, who should not be left wondering why what he finds one way he doesn't the other way.)

**Comment by jancimertel** [comment]
linked to #887, #768 

backend works the same for both queries with basic input (search only by string).

**Comment by Ptrhnk** [comment]
@jancimertel It needs check, FE is sending requests to BE, but results only come when the whole word match.

**Comment by Ptrhnk** [comment]
It's ok my false. Work with wildcard char at the end of word.
