### ISSUE TITLE
Entity tag: small mismatch between border and content in Chrome

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#907]
At 125% size in my Chrome (Chrome at 100% and 150%, as well as Firefox at all sizes, is fine), the border line of the entity tag does not match the content - some white line appears, and the vertical line separating the entity type abbreviation from the label does not go all the way down.

![obrazek](https://user-images.githubusercontent.com/55400794/162603045-cc63ab6d-c305-409e-a4b3-d5a898739cfc.png)

**Comment by pondrejk** [comment]
Seems like a known issue in chrome -- due to rounding on subpixel calculations (https://stackoverflow.com/questions/64478453/rendering-rounding-issue-in-chrome-when-zooming), not sure we can do anything about it, apart from waiting on a a fix in some newer chrome version
