### ISSUE TITLE
Pagination of entity uses in Detail

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#911]
Good job that entity uses in Detail are paginated. But I think the pagination would be better with much less rows per "page" - pagination is done to avoid scrolling (or almost), no? And here I must press PgDn exactly 50 times before I get to the Previous/Next page button.
![obrazek](https://user-images.githubusercontent.com/55400794/162604593-666cf0af-0c18-4332-9ea2-de2f1a449acc.png)

**Comment by Ptrhnk** [comment]
Will be solved by react table
