### ISSUE TITLE
Make "Used in" in Detail more informative

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#912]
Now there is a lot of unused space. I want to see the structure in which an entity is used - something more similar to the Statements box (statements list). Let us use the syntax from left to right - for props and metaprops it will be origin - proptype - propvalue, for statements exactly the same display as in Statements, just with the entity in focus (i.e. the one displayed in Detail) perhaps somehow highlighted (with an additional border or something). In all three cases (Metaprops, statements, props) with an easy access to editing the given relation.

**Comment by adammertel** [comment]
@Ptrhnk 
Branch `fix-912`

All relevant entities should be in `entities` property of `IResponseDetail`
Now, we use the component `EntityDetailBoxTable`, but you have to break this into three / two separate components. But it's up to your consideration.

**Statements** section should mimic the table from the statement list component with the same columns - except for the dragging function, expander, and the context menu button. The "edit statement" button should be at the end of the table row. => Statement tag, Subject tags, Actions tags, Object tags (all the other actants than subject), Text, and the edit button. Entity tags should be in the short version (no label).

**Statement Prop** and **Meta Prop** sections should consist of a similar table with columns "Origin", "Type" and "Value". Each column should have one Entity tag in the longer version (with label). The edit button is not relevant while the user can use the double-click action. 

Ideally, try to find a way how to highlight the Entity tag that is at the moment opened in the Detail.

**Comment by davidzbiral** [comment]
I approve - let's implement.
