### ISSUE TITLE
Fix default logical operator in metaprops

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#923]
- Verify from where "=" comes.
- Default logical operator should be "and".

Logical operator jumps between AND and "=".

**Comment by Ptrhnk** [comment]
@davidzbiral @tomaham It's probably problem with import data. As I create new rows there is always AND operator.

**Comment by tomaham** [comment]
@Ptrhnk I will check the problem.

**Comment by tomaham** [comment]
I have fixed the default, made a new parsing batch and imported it to the stage.

The "Import batch [development] 2022-04-20 16:14:46.895512"  should be fixed.

**Comment by Ptrhnk** [comment]
Ok, I'll mark it as resolved.
