### ISSUE TITLE
In metaprops property type, the only allowed elvl is 3 "inferential"

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#925]

**Comment by Ptrhnk** [comment]
@davidzbiral Should be only one possibility allowed there? Or now is only one working?

**Comment by davidzbiral** [comment]
@Ptrhnk: Sorry for an unclear expression. For property type, the only allowed elvl should be "inferential". This is so e.g. in the [sandbox deploy](https://dissinet.cz/apps/inkvisitor-sandbox/) (see how the dropdown is grayed out):
![obrazek](https://user-images.githubusercontent.com/55400794/164374617-f9ad6293-8b28-4022-adb0-6c3bc672dbbb.png)
Please reintroduce it.

This only concerns the property type (not the property value or the property relation itself).

**Comment by Ptrhnk** [comment]
OK I changed default onCreate to Inferential. But It's importat to handle this in import data
@tomaham Can you check this in data somehow, this should be default and also only option here.
@davidzbiral @tomaham I'm thinking how to solve situation when it's not in the data set to inferential.
First idea was check it automatically when you open attr. modal with some notification that it was set to Inferential and "apply changes" button need to be pressed.
Any Ideas?

**Comment by davidzbiral** [comment]
This is included in the broader issue #975. Closing.
