### ISSUE TITLE
don't open detail after attribute modal suggester entity creation

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#926]
It is closing the modal with attributes editor.

**Comment by Ptrhnk** [comment]
@davidzbiral This is a question how to behave. I think it's not good to open detail with new entity and let attribute modal from detail opened as well. This can create inconsistency.
Possible usage:
1) Open detail of new created entity after created in attr. modal with closing modal.
2) Don't open new detail and let the modal open.

**Comment by davidzbiral** [comment]
@Ptrhnk: Yes: if an entity is being created in the modal window, only display it in the Detail box after the user closes the modal and the entity is successfully created (e.g. by pressing Ctrl+Enter).

**Comment by Ptrhnk** [comment]
But there is diference between creating entity and confirming modal. Not sure if it's clear right now. Entity can be created before confirming modal or how it's implemented now - there's different lifecycle for creating / assigning entities and confirming changes in dropdowns. Maybe it's topic for discussion. Should entity be created after modal is confirmed?
I also tag @adammertel for discussion if needed.

**Comment by davidzbiral** [comment]
OK, then even seeing the video, I do not understand what's the situation or problem. I must see it life (videocall or meeting with Adam - which I would like to plan soon, I will write on Slack).

**Comment by Ptrhnk** [comment]
Only choose existing from suggester in modal.
