### ISSUE TITLE
Enhance the geocoding module

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#931]
Can come now or only in the 2nd version of the geocoding module:
- enable other than point geometries (HGA only works with the point geometry): polyline (e.g., rivers), polygons (e.g., states, dioceses);
- implement other geocoding services - cf. [HGA GitHub](https://github.com/adammertel/historical-geocoding-assistant/].

Note: boundaries of states etc. can change while the "identity" (Location ID) of the state remains the same, i.e. we sometimes need to attach second-order property of time to the coordinate pair property.

**Comment by adammertel** [comment]
A duplicate to #313?

**Comment by davidzbiral** [comment]
@adammertel No, the idea was that #313 is the basic functionality, while the current issue is enhanced functions. But of course, both can be done at a time.

**Comment by davidzbiral** [comment]
I now close in favour of #313 and include the features there, because this is scheduled in the same milestone.
