### ISSUE TITLE
Notification vs. Drag and drop

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#934]
There's a problem with DnD (drag & drop) and notifications. I'll try to explain it but it's complicated dev situtation. Javascript code is running mostly synchronously (not possible to do 2 operations at one time). So there is part of the code from DnD that is not running when notification is shown, because there is timeOut function in notification which is kind of "blocking" it. It would be propably possible to solve, but it's a bit problematic situation to handle. If you got more problems with it, we can make it priortity I guess. Not sure if to say it to other historians. Also restricting some notifications will help as a workaround (e.g. same as in editor we probably don't need notifications for new territory as it's shown after creation).

**Comment by davidzbiral** [comment]
@Ptrhnk : I indeed think that new territory needs not to be notified.

I now see another issue which might cause trouble - the tag is now quite far from the mouse, in the new version: #935.

**Comment by Ptrhnk** [comment]
No, this issue is about that when notification is on, it's not possible  to catch anyting draggable.

**Comment by davidzbiral** [comment]
@Ptrhnk : I am thinking about some imposed validation edits as notifications in 1.4.0, with an "undo" link, and so they will need to be displayed longer => this will become a problem. Good to solve it.

**Comment by Ptrhnk** [comment]
Possible solution.
Needs to be somehow implemented with library we use

function timeout(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}
async function sleep(fn, ...args) {
    await timeout(3000);
    return fn(...args);
}

**Comment by adammertel** [comment]
Fixed by library update
