### ISSUE TITLE
Can you apply template to a template? 

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#953]

**Comment by davidzbiral** [comment]
@adammertel : It would be a way of copying (duplicating) a template (and then editing it), if you think it is a good way - I am not sure it is. Other than that, no - it is better to make something "non-templatish" a template.

**Comment by adammertel** [comment]
Thanks for a quick reply. I am sorry, I should have appended an example.
Imagine, you created a template "Person" with many many properties and you like it. Then you realize, you want to use this template for creating the template "Person:Woman" or "Person:Monk" where a few properties will be changed / added ....

But yes, duplicating a template is basically the same as applying a template to a template.
In general, I have no strong opinion on this.

**Comment by davidzbiral** [comment]
@adammertel : I think the better way to create a template from a non-template is to duplicate the entity I like, edit it a little bit, and tag it as template. But it is probably simpler to allow "apply template" without exception. The crucial question is, what "apply template" does with existing stuff, i.e. how does it add to / overwrite what is there. This is more important, and it will also help me answer whether "apply template to template" should be allowed.
