### ISSUE TITLE
After any statement in the list is duplicated and error occured

### ISSUE THREAD

**Issue by adammertel** [DISSINET/InkVisitor#971]
But the application works and the model is cloned correctly

getting
`GET http://localhost:4000/api/v1/entities/detail/aebfacf0-a5a0-477b-a36d-2b22ff77d13d 500 (Internal Server Error)`
and 
`{result: false, error: 'InternalServerError', message: 'unknown error occured'}` 

@jancimertel could you please try to track back this error message? I was not succesfull.

**Comment by jancimertel** [comment]
in case of internal server error, the error stack should be printed to stderr on server.
in this case i believe you haven't imported the db (probably missing new index - template index ?). is it possible?

Nonetheless, after trying this request i received 200

![image](https://user-images.githubusercontent.com/10438157/166314468-39be2441-9d8e-45c1-876d-99a5e7a87f70.png)

please try it again after db reimport, im closing this now.
