### ISSUE TITLE
Default elvl in metaprops: prop elvl = 3, proptype elvl = 3, and propvalue elvl = 3

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#975]
In any prop, we have three elvl slots: for the whole property, for the proptype, and for the propvalue. As per [this Slack discussion](https://dissinet.slack.com/archives/CFF247QFK/p1650987023801219), we now think about this differently than before in **metaprops**: metaprops are by definition at elvl3 in all of their 3 slots: prop elvl = 3, proptype elvl = 3, and propvalue elvl = 3.

Please set this as the only possible value in all three slots for metaprops. (Does not concern in-statement props - there, make no change.)

(@Ptrhnk : this includes - and thus superseeds - #925. I have closed that one.) 

(For @tomaham and @rljshaw : of course, some data parsed from gsheets as metaprops "should not have been created as metaprops" in the full approach, but they simply are, i.e. they are not referred to any text, and thus they will be elvl3 all the same - this is the correct way, there is no other correct way. We must build this towards the data model we want.)

A separate issue #976 created for parsing scripts to set this.

**Comment by Ptrhnk** [comment]
@davidzbiral Ok, still my question from previous issue persists:
I'm thinking how to solve situation when it's not in the data set to inferential.
First idea was check it automatically when you open attr. modal with some notification that it was set to Inferential and "apply changes" button need to be pressed.
Any Ideas?

**Comment by davidzbiral** [comment]
@Ptrhnk I have seen that the solution concerns even normal props, not just metaprops in data-import deploy 28.04.2022 14:01, which is completely undesired behaviour. This defaulting elvl = 3 should only concern _metaprops_, not in-statement props.
![obrazek](https://user-images.githubusercontent.com/55400794/165973030-2633167d-6823-4460-80f8-dd1c5651895d.png)

**Comment by Ptrhnk** [comment]
Okay, I just didn't now that this is not called meta props. Cause it was or at least is in our dev architecture. I'll fix it.

**Comment by Ptrhnk** [comment]
@davidzbiral What does it mean all three slots, do you mean just hierarchically the three levels?

**Comment by davidzbiral** [comment]
@Ptrhnk : by 3 elvl "slots", I mean what is in the title: prop elvl, proptype elvl, and propvalue elvl.

Metaprops and normal (in-statement) props are different. I do not know (@adammertel ?) whether it is good or not to have it as the same IProp object or not - this is up to you guys.

**Comment by Ptrhnk** [comment]
Yes, I understand it now. It's possible to manage with current requirements.

**Comment by davidzbiral** [comment]
@adammertel : Why reopened?

**Comment by adammertel** [comment]
> @adammertel : Why reopened?

Sorry i thought this is a different issue :)
