### ISSUE TITLE
Setting metaprop attributes to default values in data parsing

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#976]
In any prop, we have three elvl slots: for the whole property, for the proptype, and for the propvalue. As per [this Slack discussion](https://dissinet.slack.com/archives/CFF247QFK/p1650987023801219), we now think about this differently than before in **metaprops**: metaprops are by definition at elvl3 in all of their 3 slots: prop elvl = 3, proptype elvl = 3, and propvalue elvl = 3.

@tomaham : Please set this through the parsing scripts. (Does not concern in-statement props parsed form coding sheets; there, make no change.)

(For @tomaham and @rljshaw : of course, some data parsed from gsheets as metaprops "should not have been created as metaprops" in the full approach, but they simply are, i.e. they are not referred to any text, and thus they will be elvl3 all the same - this is the correct way, there is no other correct way. We must build this towards the data model we want.)

A separate issue #975 created for GUI implementation of this.

**Comment by davidzbiral** [comment]
@tomaham : Is this solved?

**Comment by davidzbiral** [comment]
@tomaham : This seems to be handled because now metaprops only allow "logic" and "certainty", no? Please tell me.

**Comment by tomaham** [comment]
@davidzbiral 
The iprop object contain elvl . I am not aware the metaprops only allow log and certainty.
![image](https://user-images.githubusercontent.com/3739529/197349130-e794b727-1b6b-41f3-a768-3a20c621f960.png)

**Comment by tomaham** [comment]
@davidzbiral And it was not solved, I had in the code still "1", I have corrected it to "3" (inferential).

**Comment by davidzbiral** [comment]
OK, @tomaham, so only the GUI hides this! The genealogy is as follows: we thought leaving the same IProp object for both instatement props and metaprops, and just hide some values in GUI. So the user cannot store them. But this does not prevent us from storing them through a script.
This has reasons: we or another project might want to go back to the full attribute list in metaprops. But we therefore must fix the default values in metaprops. 
@tomaham, are you aware how to get the defaults for each of these attributes?

**Comment by tomaham** [comment]
The defaults I use are
` 'IProp':{
            'bundleEnd':False,'bundleStart':False, 'certainty':'0', 'children':[], 'elvl':'3', 'id':'', 'logic':'1', 'mood':[], 'moodvariant':'1', 'bundleOperator':'a', 'type': {'entityId':'','elvl':'3','logic':'1','partitivity':'1','virtuality':'1'},'value':{'entityId':'','elvl':'3', 'logic':'1', 'partitivity':'1', 'virtuality':'1'}
        },`
        
You can check the numbers-meaning in https://github.com/DISSINET/InkVisitor/blob/dev/packages/shared/enums/entities.ts

**Comment by tomaham** [comment]
Should be corrected in Import batch [development] 2022-10-22 18:54:22.598885

**Comment by davidzbiral** [comment]
@adammertel: I do not understand, in the defaults, why the default of "mood" in metaprops is nothing (empty) rather than 1 "indicative". I think it should be "indicative", no?

**Comment by tomaham** [comment]
Should be corrected in Import batch [development] 2022-10-29 19:26:27.397363 .

**Comment by tomaham** [comment]
But it feels weird. Mood is an array...

**Comment by davidzbiral** [comment]
@tomaham: that is true, there can be mood combinations. E.g. question & possibility. But the default exists nonetheless, and it is "indication". @adammertel , could you comment on the default here?

**Comment by adammertel** [comment]
@davidzbiral @tomaham the default value in the FE constructor is [Indication] indeed, but I see that on the BE the default value is an empty array - I am going to fix this.

**Comment by davidzbiral** [comment]
@tomaham: Does this have any implication for parsing? It seemed empty, we need Indication.

**Comment by tomaham** [comment]
This should be solved, the default for constructed JSON objects is an indication.   ( I fixed this some time ago and signalled in a message in this stream.)

**Comment by davidzbiral** [comment]
OK, thanks. Closing.
