### ISSUE TITLE
Copy text in entity tags

### ISSUE THREAD

**Issue by Ptrhnk** [DISSINET/InkVisitor#977]
From discussion in #892 
@davidzbiral If it's possible to highlight text in tags, then you'll be able to drag drop only by grepping the square around Entity letter. 
Or maybe can be realized by button.
I created this for further discussion.

**Comment by adammertel** [comment]
If it is not complicated, I would suggest "copy text" when the Text part of the Tag is clicked, and "drag" when the Entity letter part is clicked.
I believe that the text copy function is more minor that it really does not need a separate button.
Also, the "click on the text" event may copy to the clipboard a standardized text, e.g., `[Class] label (id)`
What do you think @davidzbiral

**Comment by davidzbiral** [comment]
Actually, I do not need copy-pasting the entity tag text - I can copy-paste from label button. Closing.

**Comment by Ptrhnk** [comment]
Yes! From detail, cool.
