### ISSUE TITLE
Error message when creating new prop

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#991]
I get an error message when I tried to create a new prop - actually often 5+ of the same error message. I don't understand what the error should be and why this appears. Could you please fix?
![obrazek](https://user-images.githubusercontent.com/55400794/165972413-b195a174-91ac-4a9e-b052-3b8fafa8ccb4.png)

**Comment by Ptrhnk** [comment]
There is not possible to create anything on staging because server is down for some reason. @jancimertel or @adammertel can you check?

**Comment by Ptrhnk** [comment]
@davidzbiral Maybe we can try to think about some solution how to recognize unresponsible server to tell users

**Comment by jancimertel** [comment]
i think the issue could mean that there is different version of FE and BE/DB
Which environment is this? Ive tested it now on staging/sandbox.

**Comment by jancimertel** [comment]
the error is telling enough in this case - the endpoint simply does not exist.
now i remember there is data-import env, i will deploy it manually there

**Comment by davidzbiral** [comment]
I am testing everything in data-import deploy.
