### ISSUE TITLE
Allow copy-paste of version & build from application's header and add deploy identification

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#995]
You guys sometimes ask in what deploy I was testing things. Allow copy-paste here. A button is OK!

I also suggest that you add, in the header, a self-identification of the deploy, e.g. its URL, to allow users/testers to really clearly identify where they have observed something, and make it part of the button-copy-pasted text.

**Comment by Ptrhnk** [comment]
https://github.com/DISSINET/InkVisitor/issues/892#issuecomment-1110059971
Here you can see issues I've created from highlight disabling.

**Comment by Ptrhnk** [comment]
My current idea is make version sign clickable and copy text on click (so there's no button or highlighting needed). Maybe with tooltip which can say something like "click to copy version".

**Comment by davidzbiral** [comment]
Yes it's fine - edited. Sorry, I missed #978 and created this (partial) duplicate.
