### ISSUE TITLE
Subterritory DnD doesn't work

### ISSUE THREAD

**Issue by davidzbiral** [DISSINET/InkVisitor#999]
![inkv-subterritory-move](https://user-images.githubusercontent.com/55400794/166105163-cc2b8362-1198-45f7-a4a2-ae68c1ca1b98.gif)

**Comment by davidzbiral** [comment]
![inkv-subterritory-move](https://user-images.githubusercontent.com/55400794/166105134-de6d0373-3450-4335-a1ab-ddaea80460eb.gif)

**Comment by davidzbiral** [comment]
Can be done in another way - so depending on how difficult it is to fix, move to the proper milestone.

**Comment by Ptrhnk** [comment]
But you are only able to dnd children inside one parent so you dont have any possibility to change order here.

**Comment by davidzbiral** [comment]
@Ptrhnk OK, maybe it makes sense to leave it as it is.
But handle somehow the result - I think that the "no drop" sign should appear. Instead, this is how the screen remains after a failed attempt - all territories disappear until page reload:
![obrazek](https://user-images.githubusercontent.com/55400794/166105281-6f129344-4e00-44c0-b357-4ed68952e923.png)

**Comment by Ptrhnk** [comment]
@davidzbiral Ok, I see now, that it's possible to invoke an error with this behavior.

**Comment by Ptrhnk** [comment]
But you really have some problem with cursor. It would be nice to be able to analyze it somehow. Are you working in zoom in mode in browser?

**Comment by davidzbiral** [comment]
I would put it differently - the app has problem with my cursor :-D Now at 120%. Shown now in the GIF in #935.
